import type { NextRequest } from "next/server";
import { NextResponse } from "next/server";
import { z } from "zod";
import { getAcquisitionWebhookService } from "@/modules/acquisition-api/application/acquisition-webhook-service";
import { handleRouteError } from "@/shared/core/errors/route-error-handler";
import { enforceRateLimit, readLimitedBuffer, requestClientKey, sensitiveEndpointPolicies } from "@/shared/core/http/request-hardening";
export const dynamic = "force-dynamic"; export const runtime = "nodejs";
const paramsSchema = z.object({ workspaceSlug: z.string().regex(/^[a-z0-9][a-z0-9-]{1,79}$/), connectionKey: z.string().regex(/^[a-z][a-z0-9-]{2,63}$/) });
export async function GET(request: NextRequest, context: { params: Promise<{ workspaceSlug: string; connectionKey: string }> }) { try { await enforceRateLimit("acquisition-webhook", requestClientKey(request), sensitiveEndpointPolicies.whatsAppWebhook); const params = paramsSchema.parse(await context.params); const query = z.object({ "hub.mode": z.string(), "hub.verify_token": z.string().min(1).max(500), "hub.challenge": z.string().min(1).max(200) }).parse(Object.fromEntries(request.nextUrl.searchParams)); const challenge = await getAcquisitionWebhookService().verifyMetaChallenge({ ...params, mode: query["hub.mode"], token: query["hub.verify_token"], challenge: query["hub.challenge"] }); return new NextResponse(challenge, { status: 200, headers: { "Content-Type": "text/plain", "Cache-Control": "no-store" } }); } catch (error) { return handleRouteError(error); } }
export async function POST(request: NextRequest, context: { params: Promise<{ workspaceSlug: string; connectionKey: string }> }) { try { await enforceRateLimit("acquisition-webhook", requestClientKey(request), sensitiveEndpointPolicies.whatsAppWebhook); const params = paramsSchema.parse(await context.params); const rawBody = (await readLimitedBuffer(request, 256 * 1024)).toString("utf8"); const signature = request.headers.get("x-hub-signature-256") ?? request.headers.get("typeform-signature") ?? request.headers.get("x-politizai-signature") ?? undefined; const timestamp = request.headers.get("x-politizai-timestamp") ?? undefined; return NextResponse.json({ result: await getAcquisitionWebhookService().receive({ ...params, rawBody, headers: { ...(signature ? { signature } : {}), ...(timestamp ? { timestamp } : {}) } }) }, { headers: { "Cache-Control": "no-store" } }); } catch (error) { return handleRouteError(error); } }
