import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { PageHeader } from "@/components/layout/page-header";
import { EmptyState } from "@/components/ui/empty-state";
import { Button } from "@/components/ui/button";
import { DataTableShell, SectionHeader, Surface, StatCard } from "@/components/ui/surface";
import { JourneyPanel } from "@/components/lifecycle/journey-panel";
import { getAccountService } from "@/modules/accounts/application/account-service";
import type { AccountDetail } from "@/modules/accounts/domain/account-contracts";
import { requirePageAuthentication } from "@/modules/auth/http/authentication-guards";
import { AccessDeniedError } from "@/modules/users/permissions/authorization-errors";
import { getLifecycleService } from "@/modules/lifecycle/application/lifecycle-service";

export const dynamic = "force-dynamic";
const money = (value: string) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(Number(value) / 100);

export default async function AccountPage({ params, searchParams }: Readonly<{ params: Promise<{ accountId: string }>; searchParams: Promise<Record<string, string | string[] | undefined>> }>) {
  const context = await requirePageAuthentication(); const { accountId } = await params; const query = await searchParams; let account: AccountDetail; let journey;
  try { [account, journey] = await Promise.all([getAccountService().get(context, accountId, { page: typeof query.page === "string" ? query.page : undefined }), getLifecycleService().getJourney(context, { entityType: "ACCOUNT", entityId: accountId })]); }
  catch (error) { if (error instanceof AccessDeniedError) redirect("/acesso-negado"); if (error instanceof Error && error.message.includes("não encontrada")) notFound(); throw error; }
  const next = account.customerSuccess.find((item) => item.state === "ACTIVE") ?? null;
  return <main className="page-canvas page-canvas-wide"><PageHeader eyebrow="Account 360" title={account.name} description={account.legalName ?? "Organização canônica confirmada no workspace."} meta={`Revisão ${account.revision} · ${account.status}`} />
    <section className="entity-hero"><div><span className="status-badge" data-tone={account.quality === "CONFIRMED" ? "success" : "warning"}>{account.quality}</span><h2>{next?.nextAction ?? "Revisar relacionamento da conta"}</h2><p>{next ? "Próxima ação persistida da carteira de Customer Success." : "Não há próxima ação de Customer Success disponível para esta conta."}</p></div><Button asChild><Link href={next ? `/customer-success?accountId=${account.id}` : `/oportunidades?accountId=${account.id}`}>{next ? "Abrir carteira" : "Ver oportunidades"}</Link></Button></section>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><StatCard label="Contatos" value={account.people.length} /><StatCard label="Leads" value={account.leads.length} /><StatCard label="Oportunidades" value={account.opportunities.length} /><StatCard label="MRR ativo" value={money(account.subscriptions.reduce((sum, item) => sum + BigInt(item.mrrCents), 0n).toString())} /><StatCard label="Sinais / churn" value={`${account.expansionSignals} / ${account.churnEvents}`} /></div>
    <div className="entity-layout"><div className="space-y-5"><JourneyPanel journey={journey} />
      <Surface><SectionHeader title="Pessoas e comitê de compra" description="Relações múltiplas e papéis temporais permanecem preservados." />{account.people.length ? <DataTableShell className="mt-4"><table><thead><tr><th>Contato</th><th>Papel</th><th>Influência</th><th>Autoridade</th></tr></thead><tbody>{account.people.map((person) => <tr key={person.roleId}><td><Link href={`/contatos/${person.contactId}`}>{person.name}</Link><small className="block text-muted-foreground">{person.roleTitle ?? "Sem título"}</small></td><td>{person.roleType}</td><td>{person.influence}</td><td>{person.authority}</td></tr>)}</tbody></table></DataTableShell> : <EmptyState compact title="Nenhuma pessoa vinculada" description="A ausência de vínculo foi preservada; nenhum contato foi inferido." />}</Surface>
      <Surface><SectionHeader title="Negócios e receita" description="Oportunidades, contratos, assinaturas e cobranças são fatos distintos." /><div className="entity-groups"><div><h3>Oportunidades</h3>{account.opportunities.map((item) => <Link href={`/oportunidades?opportunityId=${item.id}`} key={item.id}><span>{item.name}</span><strong>{money(item.amountCents)}</strong></Link>)}</div><div><h3>Contratos e assinaturas</h3>{account.contracts.map((item) => <Link href={`/contratos?contractId=${item.id}`} key={item.id}><span>{item.number}</span><strong>{item.status}</strong></Link>)}{account.subscriptions.map((item) => <Link href={`/receita?subscriptionId=${item.id}`} key={item.id}><span>{item.number}</span><strong>{money(item.mrrCents)} MRR</strong></Link>)}</div><div><h3>Solicitações e onboarding</h3>{account.requests.map((item) => <Link href={item.href} key={item.id}><span>{item.subject}</span><strong>{item.status}</strong></Link>)}{account.onboarding.map((item) => <Link href={item.href} key={item.id}><span>{item.nextAction}</span><strong>{item.status}</strong></Link>)}</div></div></Surface>
      <Surface><SectionHeader title="Timeline da conta" description="Eventos canônicos agregados com proveniência e links para o fato de origem." />{account.timeline.length ? <ol className="entity-timeline">{account.timeline.map((item) => <li key={item.id}><time>{new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(new Date(item.occurredAt))}</time><div><strong>{item.title}</strong><small>{item.provenance} · {item.type}</small></div>{item.href ? <Link href={item.href}>Abrir fato</Link> : null}</li>)}</ol> : <EmptyState compact title="Timeline vazia" description="Nenhum evento canônico está relacionado a esta conta." />}{account.hasMoreTimeline ? <Button asChild className="mt-4" variant="secondary"><Link href={`?page=${account.timelinePage + 1}`}>Próxima página</Link></Button> : null}</Surface>
    </div><aside className="space-y-4"><Surface tone="accent"><SectionHeader title="Identidade" /><dl className="entity-facts"><div><dt>Documento</dt><dd>{account.originalDocument ?? "Não informado"}</dd></div><div><dt>Domínio</dt><dd>{account.originalDomain ?? "Não informado"}</dd></div><div><dt>Segmento / porte</dt><dd>{account.segment} · {account.size}</dd></div><div><dt>Conta pai</dt><dd>{account.parent?.name ?? "Nenhuma"}</dd></div></dl></Surface><Surface><SectionHeader title="Ownership atual" />{account.ownership.length ? <ul className="entity-mini-list">{account.ownership.map((item) => <li key={item.id}><strong>{item.function}</strong><span>{item.responsible}</span></li>)}</ul> : <p className="mt-3 text-sm text-muted-foreground">Sem ownership funcional vigente.</p>}</Surface><Surface><SectionHeader title="Renovação" />{account.renewals.length ? <ul className="entity-mini-list">{account.renewals.map((item) => <li key={item.id}><Link href={item.href}><strong>{item.status}</strong><span>{item.risk} · {new Intl.DateTimeFormat("pt-BR").format(new Date(item.targetDate))}</span></Link></li>)}</ul> : <p className="mt-3 text-sm text-muted-foreground">Nenhuma renovação registrada.</p>}</Surface></aside></div>
  </main>;
}
