packages:
  - .

allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true
  unrs-resolver: true
overrides:
  deepmerge-ts: 8.0.0
  mysql2: 3.23.1
minimumReleaseAgeExclude:
  - '@types/node@22.20.2'
  - '@types/react-dom@19.3.0'
  - '@types/react@19.3.0'
  - react-dom@19.3.0
  - react@19.3.0
  - scheduler@0.28.0
  - zod@4.6.1
