import type { Prisma, PrismaClient, RevenueMovementSource, RevenueMovementType, SubscriptionHistoryEvent, SubscriptionStatus } from "@/generated/prisma/client";
import type { AuthenticatedContext } from "@/modules/auth/application/authenticated-context";
import { createSubscriptionSchema, normalizedMrr, subscriptionActionSchema } from "@/modules/revenue/domain/revenue-contracts";
import { getAuthorizationService } from "@/modules/users/permissions/authorization-service";
import { PermissionKeys } from "@/modules/users/permissions/permission-keys";
import { getDatabaseClient } from "@/shared/core/database/client";
import { ApplicationError } from "@/shared/core/errors/application-error";

function fail(message: string, code="INVALID_REVENUE_OPERATION", statusCode=409): never { throw new ApplicationError(message,{code,statusCode,expose:true}); }
const resource = (workspaceId:string,id?:string,ownerMemberId?:string) => ({workspaceId,resourceType:"Subscription",...(id ? {resourceId:id} : {}),...(ownerMemberId ? {ownerMemberId} : {})});

export function createRevenueService(database: PrismaClient=getDatabaseClient(), authorization=getAuthorizationService()) {
  async function nextNumber(tx:Prisma.TransactionClient, workspaceId:string, now:Date) {
    await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtextextended(${`subscription-number:${workspaceId}`},0))`;
    const rows=await tx.$queryRaw<{allocated:bigint}[]>`INSERT INTO subscription_number_sequences ("workspaceId","nextValue","updatedAt") VALUES (${workspaceId}::uuid,2,NOW()) ON CONFLICT ("workspaceId") DO UPDATE SET "nextValue"=subscription_number_sequences."nextValue"+1,"updatedAt"=NOW() RETURNING "nextValue"-1 allocated`;
    return `SUB-${now.getUTCFullYear()}-${rows[0]!.allocated.toString().padStart(6,"0")}`;
  }
  async function history(tx:Prisma.TransactionClient,s:{id:string;workspaceId:string;status:SubscriptionStatus},event:SubscriptionHistoryEvent,previous:SubscriptionStatus|null,actorId:string,reason:string,payload?:object) {
    const count=await tx.subscriptionHistory.count({where:{workspaceId:s.workspaceId,subscriptionId:s.id}});
    await tx.subscriptionHistory.create({data:{workspaceId:s.workspaceId,subscriptionId:s.id,sequence:count+1,event,previousStatus:previous,newStatus:s.status,reason,actorId,...(payload ? {payload} : {})}});
    await tx.auditLog.create({data:{workspaceId:s.workspaceId,actorId,action:`subscription.${event.toLowerCase()}`,origin:"API",entityType:"Subscription",entityId:s.id,changes:{previousStatus:previous,newStatus:s.status,reason},metadata:{appendOnlyHistory:true}}});
  }
  async function movement(tx:Prisma.TransactionClient,s:{id:string;workspaceId:string;accountId:string},input:{type:RevenueMovementType;delta:bigint;effectiveAt:Date;actorId:string;reason:string;idempotencyKey:string;source?:RevenueMovementSource;reversesMovementId?:string;correlationId?:string}) {
    const replay=await tx.revenueMovement.findUnique({where:{workspaceId_idempotencyKey:{workspaceId:s.workspaceId,idempotencyKey:input.idempotencyKey}}}); if(replay) return replay;
    const last=await tx.revenueMovement.findFirst({where:{workspaceId:s.workspaceId,subscriptionId:s.id},orderBy:{sequence:"desc"}});
    const row=await tx.revenueMovement.create({data:{workspaceId:s.workspaceId,subscriptionId:s.id,accountId:s.accountId,sequence:(last?.sequence??0)+1,type:input.type,deltaMrrCents:input.delta,currency:"BRL",effectiveAt:input.effectiveAt,actorId:input.actorId,reason:input.reason,source:input.source??"HUMAN_ACTION",idempotencyKey:input.idempotencyKey,correlationId:input.correlationId??input.idempotencyKey,...(input.reversesMovementId ? {reversesMovementId:input.reversesMovementId} : {})}});
    const balance=await tx.revenueMovement.aggregate({where:{workspaceId:s.workspaceId,subscriptionId:s.id,effectiveAt:{lte:new Date()}},_sum:{deltaMrrCents:true}}); if((balance._sum.deltaMrrCents??0n)<0n) fail("O movimento produziria MRR negativo.");
    return row;
  }
  return {
    async list(context:AuthenticatedContext, cutoff=new Date()) { await authorization.assertAuthorized(context,PermissionKeys.REVENUE_READ,{...resource(context.workspaceId),memberId:context.memberId}); const rows=await database.subscription.findMany({where:{workspaceId:context.workspaceId},orderBy:{updatedAt:"desc"}}); const visible=[]; for(const row of rows) if((await authorization.authorize(context,PermissionKeys.REVENUE_READ,resource(context.workspaceId,row.id,row.ownerMemberId))).allowed) visible.push(row); const movements=await database.revenueMovement.findMany({where:{workspaceId:context.workspaceId,subscriptionId:{in:visible.map(item=>item.id)},effectiveAt:{lte:cutoff}},orderBy:[{effectiveAt:"asc"},{sequence:"asc"},{id:"asc"}]}); const mrr=movements.reduce((s,m)=>s+m.deltaMrrCents,0n); return {subscriptions:visible,mrrCents:mrr,arrCents:mrr*12n,cutoff:cutoff.toISOString(),currency:"BRL",timeZone:"America/Sao_Paulo",formula:"MRR = soma dos deltas efetivos até o corte; ARR = MRR × 12"}; },
    async summary(context:AuthenticatedContext,from:Date,to:Date) { const listed=await this.list(context,to); const ids=listed.subscriptions.map(s=>s.id); const rows=await database.revenueMovement.groupBy({by:["type"],where:{workspaceId:context.workspaceId,subscriptionId:{in:ids},effectiveAt:{gte:from,lt:to}},_sum:{deltaMrrCents:true},_count:{_all:true}}); const movements=Object.fromEntries(rows.map(r=>[r.type,{deltaMrrCents:r._sum.deltaMrrCents??0n,count:r._count._all}])); const statusCounts=Object.fromEntries((await database.subscription.groupBy({by:["status"],where:{workspaceId:context.workspaceId,id:{in:ids}},_count:{_all:true}})).map(r=>[r.status,r._count._all])); return {...listed,interval:{from:from.toISOString(),to:to.toISOString(),semantics:"[from,to)"},movements,statusCounts,netNewMrrCents:rows.reduce((sum,r)=>sum+(r._sum.deltaMrrCents??0n),0n)}; },
    async detail(context:AuthenticatedContext,id:string) { const s=await database.subscription.findFirst({where:{id,workspaceId:context.workspaceId}}); if(!s) fail("Assinatura não encontrada.","NOT_FOUND",404); await authorization.assertAuthorized(context,PermissionKeys.REVENUE_READ,resource(context.workspaceId,id,s.ownerMemberId)); return {subscription:s,history:await database.subscriptionHistory.findMany({where:{workspaceId:context.workspaceId,subscriptionId:id},orderBy:{sequence:"desc"}}),ledger:await database.revenueMovement.findMany({where:{workspaceId:context.workspaceId,subscriptionId:id},orderBy:[{effectiveAt:"desc"},{sequence:"desc"}]})}; },
    async create(context:AuthenticatedContext,raw:unknown) { const input=createSubscriptionSchema.parse(raw); return database.$transaction(async tx=>{const c=await tx.commercialContract.findFirst({where:{id:input.contractId,workspaceId:context.workspaceId,status:"ACCEPTED"}}); if(!c?.currentVersionId) fail("Somente contrato aceito e versionado pode originar assinatura."); await authorization.assertAuthorized(context,PermissionKeys.REVENUE_MANAGE,resource(context.workspaceId,undefined,c.ownerMemberId)); const existing=await tx.subscription.findFirst({where:{workspaceId:context.workspaceId,contractId:c.id}}); if(existing)return existing; const v=await tx.contractVersion.findFirstOrThrow({where:{workspaceId:context.workspaceId,id:c.currentVersionId}}); const line=await tx.contractLineSnapshot.findFirst({where:{workspaceId:context.workspaceId,contractVersionId:v.id},orderBy:{position:"asc"}}); const s=await tx.subscription.create({data:{workspaceId:context.workspaceId,subscriptionNumber:await nextNumber(tx,context.workspaceId,new Date()),accountId:c.accountId,contractId:c.id,currentContractVersionId:v.id,ownerMemberId:c.ownerMemberId,accountNameSnapshot:v.accountNameSnapshot,contractNumberSnapshot:c.contractNumber,productNameSnapshot:line?.productNameSnapshot??v.opportunityNameSnapshot,currency:"BRL",quantity:input.quantity,recurringPriceCents:input.recurringPriceCents,billingInterval:input.billingInterval,currentMrrCents:0,startsAt:input.startsAt,endsAt:input.endsAt,createdByActorId:context.actorId,updatedByActorId:context.actorId}}); await history(tx,s,"CREATED",null,context.actorId,"Assinatura criada explicitamente a partir de contrato aceito."); return s;}); },
    async action(context:AuthenticatedContext,id:string,raw:unknown){const input=subscriptionActionSchema.parse(raw); return database.$transaction(async tx=>{await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtextextended(${`subscription:${context.workspaceId}:${id}`},0))`; let s=await tx.subscription.findFirst({where:{id,workspaceId:context.workspaceId}}); if(!s)fail("Assinatura não encontrada.","NOT_FOUND",404); const key=input.action==="REVERSE"?PermissionKeys.REVENUE_CORRECT:PermissionKeys.REVENUE_EVENTS_RECORD; await authorization.assertAuthorized(context,key,resource(context.workspaceId,id,s.ownerMemberId)); const previous=s.status;
      if(input.action==="ACTIVATE"){if(s.status!=="DRAFT")fail("Somente rascunho pode ser ativado."); const mrr=normalizedMrr(s.quantity,s.recurringPriceCents,s.billingInterval); await movement(tx,s,{type:"NEW",delta:mrr,effectiveAt:input.effectiveAt,actorId:context.actorId,reason:input.reason,idempotencyKey:input.idempotencyKey}); s=await tx.subscription.update({where:{id:s.id},data:{status:"ACTIVE",currentMrrCents:mrr,revision:{increment:1},updatedByActorId:context.actorId}}); await history(tx,s,"ACTIVATED",previous,context.actorId,input.reason);}
      else if(input.action==="SCHEDULE_CHANGE"){if(!["ACTIVE","CANCELLATION_SCHEDULED"].includes(s.status))fail("Alteração exige assinatura ativa."); const mrr=normalizedMrr(input.quantity,input.recurringPriceCents,input.billingInterval); await tx.subscriptionScheduledChange.create({data:{workspaceId:s.workspaceId,subscriptionId:s.id,effectiveAt:input.effectiveAt,quantity:input.quantity,recurringPriceCents:input.recurringPriceCents,billingInterval:input.billingInterval,normalizedMrrCents:mrr,reason:input.reason,createdByActorId:context.actorId}}); await history(tx,s,"CHANGE_SCHEDULED",previous,context.actorId,input.reason);}
      else if(input.action==="APPLY_CHANGE"){const change=await tx.subscriptionScheduledChange.findFirst({where:{id:input.changeId,workspaceId:s.workspaceId,subscriptionId:s.id,status:"PENDING"}}); if(!change||change.effectiveAt>new Date())fail("Alteração inexistente ou ainda não efetiva."); const delta=change.normalizedMrrCents-s.currentMrrCents; await movement(tx,s,{type:delta>=0n?"EXPANSION":"CONTRACTION",delta,effectiveAt:change.effectiveAt,actorId:context.actorId,reason:change.reason,idempotencyKey:input.idempotencyKey}); await tx.subscriptionScheduledChange.update({where:{id:change.id},data:{status:"APPLIED",appliedAt:new Date(),appliedByActorId:context.actorId}}); s=await tx.subscription.update({where:{id:s.id},data:{quantity:change.quantity,recurringPriceCents:change.recurringPriceCents,billingInterval:change.billingInterval,currentMrrCents:change.normalizedMrrCents,revision:{increment:1},updatedByActorId:context.actorId}}); await history(tx,s,"CHANGE_APPLIED",previous,context.actorId,change.reason);}
      else if(input.action==="RENEW"){if(s.status!=="ACTIVE")fail("Renovação exige assinatura ativa."); await movement(tx,s,{type:"RENEWAL",delta:0n,effectiveAt:input.effectiveAt,actorId:context.actorId,reason:input.reason,idempotencyKey:input.idempotencyKey}); await history(tx,s,"RENEWED",previous,context.actorId,input.reason);}
      else if(input.action==="SCHEDULE_CANCELLATION"){if(s.status!=="ACTIVE")fail("Cancelamento exige assinatura ativa."); s=await tx.subscription.update({where:{id:s.id},data:{status:"CANCELLATION_SCHEDULED",cancellationEffectiveAt:input.effectiveAt,revision:{increment:1},updatedByActorId:context.actorId}}); await history(tx,s,"CANCELLATION_SCHEDULED",previous,context.actorId,input.reason);}
      else if(input.action==="CHURN"){if(!["ACTIVE","CANCELLATION_SCHEDULED"].includes(s.status))fail("Churn exige assinatura ativa."); if(s.cancellationEffectiveAt&&input.effectiveAt<s.cancellationEffectiveAt)fail("Churn não pode anteceder o cancelamento agendado."); await movement(tx,s,{type:"CHURN",delta:-s.currentMrrCents,effectiveAt:input.effectiveAt,actorId:context.actorId,reason:input.reason,idempotencyKey:input.idempotencyKey}); s=await tx.subscription.update({where:{id:s.id},data:{status:"CHURNED",currentMrrCents:0,revision:{increment:1},updatedByActorId:context.actorId}}); await history(tx,s,"CHURNED",previous,context.actorId,input.reason);}
      else if(input.action==="REACTIVATE"){if(s.status!=="CHURNED")fail("Reativação exige assinatura churned."); const mrr=normalizedMrr(s.quantity,s.recurringPriceCents,s.billingInterval); await movement(tx,s,{type:"REACTIVATION",delta:mrr,effectiveAt:input.effectiveAt,actorId:context.actorId,reason:input.reason,idempotencyKey:input.idempotencyKey}); s=await tx.subscription.update({where:{id:s.id},data:{status:"ACTIVE",currentMrrCents:mrr,cancellationEffectiveAt:null,revision:{increment:1},updatedByActorId:context.actorId}}); await history(tx,s,"REACTIVATED",previous,context.actorId,input.reason);}
      else {const original=await tx.revenueMovement.findFirst({where:{id:input.movementId,workspaceId:s.workspaceId,subscriptionId:s.id}}); if(!original||original.type==="REVERSAL")fail("Movimento original inválido."); await movement(tx,s,{type:"REVERSAL",delta:-original.deltaMrrCents,effectiveAt:original.effectiveAt,actorId:context.actorId,reason:input.reason,idempotencyKey:input.idempotencyKey,source:"CORRECTION",reversesMovementId:original.id,correlationId:original.correlationId}); if(input.replacement)await movement(tx,s,{type:input.replacement.type,delta:input.replacement.deltaMrrCents,effectiveAt:input.replacement.effectiveAt,actorId:context.actorId,reason:input.reason,idempotencyKey:`${input.idempotencyKey}:replacement`,source:"CORRECTION",correlationId:original.correlationId}); await history(tx,s,"MOVEMENT_CORRECTED",previous,context.actorId,input.reason);}
      return s;});}
  };
}
export const getRevenueService=()=>createRevenueService();
