import { enterDemoCompany } from "./helpers/company-hub";
import { expect, test, type Page } from "@playwright/test";
import { DEMO_SEED_PASSWORD, DEMO_USERS, } from "@/modules/settings/application/demo-seed-service";

async function login(page:Page,email:string){await page.goto("/login");await page.getByLabel("E-mail").fill(email);await page.getByLabel("Senha").fill(DEMO_SEED_PASSWORD);await page.getByRole("button",{name:"Entrar"}).click(); await enterDemoCompany(page);await expect(page).toHaveURL(/\/$/);}

test("carteira de Customer Success mostra saúde explicável e ação",async({page})=>{await login(page,DEMO_USERS[0]!.email);await page.goto("/customer-success");await expect(page.getByRole("heading",{name:"Customer Success",level:1})).toBeVisible();await expect(page.getByText("Saúde explicável").first()).toBeVisible();await expect(page.getByText("Dados insuficientes",{exact:true}).first()).toBeVisible();await expect(page.getByRole("button",{name:"Recalcular saúde"}).first()).toBeVisible();});

test("visualizador lê a carteira sem mutação e sem overflow em desktop e mobile",async({page},testInfo)=>{await login(page,DEMO_USERS.at(-1)!.email);for(const viewport of [{width:1440,height:900},{width:390,height:844}]){await page.setViewportSize(viewport);await page.goto("/customer-success");await expect(page.getByRole("heading",{name:"Customer Success",level:1})).toBeVisible();await expect(page.getByRole("button",{name:"Recalcular saúde"})).toHaveCount(0);await expect(page.getByText("Reatribuir carteira")).toHaveCount(0);const dimensions=await page.evaluate(()=>({clientWidth:document.documentElement.clientWidth,scrollWidth:document.documentElement.scrollWidth}));expect(dimensions.scrollWidth).toBeLessThanOrEqual(dimensions.clientWidth);await page.screenshot({path:testInfo.outputPath(`customer-success-${viewport.width}x${viewport.height}.png`),fullPage:true});}});
