import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { PageHeader } from "@/components/layout/page-header";
import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/ui/empty-state";
import { DataTableShell, SectionHeader, Surface, StatCard } from "@/components/ui/surface";
import { requirePageAuthentication } from "@/modules/auth/http/authentication-guards";
import { AccessDeniedError } from "@/modules/users/permissions/authorization-errors";
import { getWorkspaceExperienceService } from "@/modules/workspace-experience/application/workspace-experience-service";
import { ApplicationError } from "@/shared/core/errors/application-error";

export const dynamic = "force-dynamic";
export default async function ContactPage({ params, searchParams }: Readonly<{ params: Promise<{ contactId: string }>; searchParams: Promise<Record<string, string | string[] | undefined>> }>) {
  const context = await requirePageAuthentication(); const { contactId } = await params; const query = await searchParams; let contact;
  try { contact = await getWorkspaceExperienceService().getContact360(context, contactId, { page: typeof query.page === "string" ? query.page : undefined, pageSize: 20 }); }
  catch (error) { if (error instanceof AccessDeniedError) redirect("/acesso-negado"); if (error instanceof ApplicationError && error.code === "NOT_FOUND") notFound(); throw error; }
  return <main className="page-canvas page-canvas-wide"><PageHeader eyebrow="Contact 360" title={contact.preferredName} description={contact.jobTitle ?? "Identidade canônica do contato"} meta={`${contact.status} · ${contact.quality}`} />
    {contact.primaryAction ? <Surface className="entity-hero" tone="accent"><div><span className="status-badge" data-tone={contact.primaryAction.urgency === "CRITICAL" ? "danger" : "info"}>{contact.primaryAction.urgency === "CRITICAL" ? "Ação necessária" : "Próxima ação"}</span><h2>{contact.primaryAction.title}</h2><p>{contact.primaryAction.reason}</p></div><Button asChild><Link href={contact.primaryAction.href}>{contact.primaryAction.cta}</Link></Button></Surface> : null}
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Contas" value={contact.accounts.length} /><StatCard label="Leads" value={contact.leads.length} /><StatCard label="Oportunidades" value={contact.opportunities.length} /><StatCard label="Conversas" value={contact.conversations.length} /></div>
    <div className="entity-layout"><div className="space-y-5"><Surface><SectionHeader title="Contas e comitê" description="Um contato pode participar de várias contas e decisões sem mesclagem." />{contact.accounts.length ? <DataTableShell className="mt-4"><table><thead><tr><th>Conta</th><th>Papel</th><th>Influência</th><th>Validade</th></tr></thead><tbody>{contact.accounts.map((item) => <tr key={item.roleId}><td><Link href={`/contas/${item.accountId}`}>{item.accountName}</Link></td><td>{item.roleType}</td><td>{item.influence} · {item.authority}</td><td>{item.validTo ? "Encerrado" : "Ativo"}</td></tr>)}</tbody></table></DataTableShell> : <EmptyState compact title="Sem conta vinculada" description="Nenhuma relação de conta foi confirmada." />}</Surface>
      <Surface><SectionHeader title="Leads, oportunidades e reuniões" /><div className="entity-groups"><div><h3>Leads</h3>{contact.leads.map((item) => <Link href={item.href} key={item.id}><span>{item.name}</span><strong>{item.status}</strong></Link>)}</div><div><h3>Oportunidades</h3>{contact.opportunities.map((item) => <Link href={item.href} key={item.id}><span>{item.name}</span><strong>{item.status}</strong></Link>)}</div><div><h3>Reuniões</h3>{contact.meetings.map((item) => <Link href={item.href} key={item.id}><span>{item.title}</span><strong>{item.status}</strong></Link>)}</div></div></Surface>
      <Surface><SectionHeader title="Timeline do contato" description="Fatos imutáveis paginados; correções permanecem eventos separados." />{contact.timeline.length ? <ol className="entity-timeline">{contact.timeline.map((item) => <li key={item.id}><time>{new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(new Date(item.occurredAt))}</time><div><strong>{item.title}</strong><small>{item.provenance} · {item.type}</small></div>{item.href ? <Link href={item.href}>Abrir fato</Link> : null}</li>)}</ol> : <EmptyState compact title="Timeline vazia" description="Nenhum evento canônico foi encontrado." />}{contact.hasMoreTimeline ? <Button asChild className="mt-4" variant="secondary"><Link href={`?page=${contact.page + 1}`}>Próxima página</Link></Button> : null}</Surface>
    </div><aside className="space-y-4"><Surface tone="accent"><SectionHeader title="Contato e privacidade" /><dl className="entity-facts"><div><dt>Nome legal</dt><dd>{contact.legalName ?? "Não informado"}</dd></div>{contact.points.map((point) => <div key={point.id}><dt>{point.type}{point.primary ? " principal" : ""}</dt><dd>{point.maskedValue} · {point.doNotContact ? "não contatar" : point.verification}</dd></div>)}</dl></Surface><Surface><SectionHeader title="Consentimentos" />{contact.consents.length ? <ul className="entity-mini-list">{contact.consents.map((item) => <li key={item.id}><strong>{item.channel}: {item.state}</strong><span>{item.reasonCode}</span></li>)}</ul> : <p className="mt-3 text-sm text-muted-foreground">Ausência de consentimento registrado; não equivale a autorização.</p>}</Surface><Surface><SectionHeader title="Conversas" />{contact.conversations.length ? <ul className="entity-mini-list">{contact.conversations.map((item) => <li key={item.id}><Link href={item.href}><strong>{item.subject ?? item.channel}</strong><span>{item.status}</span></Link></li>)}</ul> : <p className="mt-3 text-sm text-muted-foreground">Nenhuma conversa autorizada.</p>}</Surface></aside></div>
  </main>;
}
