"use client";

import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";

import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/ui/empty-state";
import { StatusBadge, type StatusTone } from "@/components/ui/status-badge";
import { DataTableShell, SectionHeader, StatCard, Surface } from "@/components/ui/surface";
import type { MergePreview } from "@/modules/data-quality/domain/data-quality-contracts";

type Screen = Awaited<ReturnType<ReturnType<typeof import("@/modules/data-quality/application/data-quality-service").getDataQualityService>["getScreen"]>>;
type Candidate = Screen["candidates"][number];
const inputClass = "h-10 rounded-[var(--radius-control)] border border-border bg-card px-3 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring";
const labels: Record<string, string> = { OPEN: "Aberta", IN_REVIEW: "Em revisão", RESOLVED: "Resolvida", DISMISSED: "Descartada", INFO: "Informativa", WARNING: "Atenção", HIGH: "Alta", CRITICAL: "Crítica", CONTACT: "Contato", ACCOUNT: "Conta", LEAD: "Lead", OPPORTUNITY: "Oportunidade", INVOICE: "Cobrança", STRONG: "Forte", POSSIBLE: "Possível", ACTIVE: "Ativa", PAUSED: "Pausada", RETIRED: "Encerrada", DRAFT: "Rascunho", MATCHED: "Conciliado", MISMATCH: "Divergente", MISSING: "Ausente", STALE: "Desatualizado", PARTIAL: "Parcial", UNAVAILABLE: "Indisponível", READY: "Pronto", APPLIED: "Aplicado", REVERSED: "Revertido", BLOCKED: "Bloqueado" };
const tone = (value: string): StatusTone => value === "CRITICAL" || value === "MISMATCH" || value === "BLOCKED" ? "danger" : value === "HIGH" || value === "WARNING" || value === "PARTIAL" || value === "POSSIBLE" ? "warning" : value === "MATCHED" || value === "RESOLVED" || value === "REVERSED" ? "success" : value === "OPEN" || value === "ACTIVE" || value === "READY" ? "info" : "neutral";
const requestKey = (kind: string) => `crm61:${kind}:${crypto.randomUUID()}`;

export function DataQualityWorkspace({ initial }: Readonly<{ initial: Screen }>) {
  const router = useRouter();
  const [pending, setPending] = useState(false);
  const [notice, setNotice] = useState<{ kind: "success" | "error"; text: string } | null>(null);
  const [preview, setPreview] = useState<MergePreview | null>(null);
  const [candidate, setCandidate] = useState<Candidate | null>(null);
  const [decisions, setDecisions] = useState<Record<string, "SOURCE" | "SURVIVOR">>({});

  async function action(payload: unknown, success: string, refresh = true) {
    setPending(true); setNotice(null);
    try {
      const response = await fetch("/api/data-quality", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) });
      const body = await response.json().catch(() => ({})) as { result?: unknown; error?: { message?: string } };
      if (!response.ok) throw new Error(body.error?.message ?? "Operação não concluída.");
      setNotice({ kind: "success", text: success });
      if (refresh) router.refresh();
      return body.result;
    } catch (error) {
      setNotice({ kind: "error", text: error instanceof Error ? error.message : "Falha inesperada." });
      return null;
    } finally { setPending(false); }
  }

  async function scan(mode: "DRY_RUN" | "EXECUTE") {
    await action({ action: "SCAN", data: { mode, idempotencyKey: requestKey(`scan:${mode}`) } }, mode === "DRY_RUN" ? "Diagnóstico concluído sem criar ocorrências." : "Varredura concluída; ocorrências e evidências foram persistidas.");
  }

  async function openPreview(item: Candidate, survivorEntityId: string) {
    const result = await action({ action: "PREVIEW_MERGE", data: { candidateId: item.id, survivorEntityId } }, "Prévia atualizada. Nenhum dado foi alterado.", false) as MergePreview | null;
    if (!result) return;
    setCandidate(item); setPreview(result); setDecisions(Object.fromEntries(result.fields.map((field) => [field.fieldPath, field.recommended])));
  }

  async function createPlan(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!preview || !candidate) return;
    const form = new FormData(event.currentTarget);
    const result = await action({ action: "CREATE_MERGE_PLAN", data: { candidateId: candidate.id, survivorEntityId: preview.survivor.id, reason: String(form.get("reason")), previewFingerprint: preview.previewFingerprint, decisions: Object.entries(decisions).map(([fieldPath, strategy]) => ({ fieldPath, strategy })) } }, preview.blockers.length ? "Plano bloqueado registrado com as razões encontradas." : "Plano de merge criado; aplique-o somente após nova conferência.");
    if (result) { setPreview(null); setCandidate(null); }
  }

  async function issue(event: FormEvent<HTMLFormElement>, issueId: string, expectedRevision: number) {
    event.preventDefault(); const form = new FormData(event.currentTarget);
    await action({ action: "ISSUE", data: { issueId, action: form.get("action"), reason: form.get("reason"), expectedRevision } }, "Ocorrência atualizada com evento e auditoria.");
  }

  return <div className="space-y-5">
    {notice ? <p className={notice.kind === "error" ? "feedback feedback-error" : "feedback feedback-success"} role={notice.kind === "error" ? "alert" : "status"}>{notice.text}</p> : null}
    <section aria-label="Resumo de qualidade" className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
      <StatCard label="Ocorrências abertas" value={initial.counts.OPEN ?? 0} hint="Fato detectado por regra ativa" tone={(initial.counts.OPEN ?? 0) ? "warning" : "success"} />
      <StatCard label="Em revisão" value={initial.counts.IN_REVIEW ?? 0} hint="Responsabilidade assumida" tone="info" />
      <StatCard label="Duplicidades abertas" value={initial.candidates.length} hint="Nenhum merge é automático" tone={initial.candidates.length ? "warning" : "success"} />
      <StatCard label="Reconciliações divergentes" value={initial.reconciliations.filter((item) => item.status === "MISMATCH").length} hint="Ledger versus projeção" tone={initial.reconciliations.some((item) => item.status === "MISMATCH") ? "danger" : "success"} />
    </section>

    <Surface tone="accent"><SectionHeader title="Varredura determinística" description="O diagnóstico não usa IA. A execução cria ocorrências idempotentes, candidatos e snapshots de reconciliação." action={initial.permissions.manage ? <div className="flex flex-wrap gap-2"><Button disabled={pending} onClick={() => scan("DRY_RUN")} variant="secondary">Pré-visualizar</Button><Button disabled={pending} onClick={() => scan("EXECUTE")}>Executar varredura</Button></div> : null} />{initial.latestScan ? <p className="helper-text mt-3">Última execução: {labels[initial.latestScan.mode] ?? initial.latestScan.mode} · {initial.latestScan.scannedCount} registros · {initial.latestScan.detectedCount} ocorrências · checkpoint {initial.latestScan.checkpoint}</p> : <p className="helper-text mt-3">Nenhuma varredura registrada neste workspace.</p>}</Surface>

    <Surface><SectionHeader title="Fila de ocorrências" description="Evidência mínima, responsável explícito e resolução via serviço de domínio." />
      <form action="/qualidade-dados" className="mt-4 flex flex-wrap gap-2"><select aria-label="Status" className={inputClass} defaultValue={initial.filters.status} name="status"><option value="ALL">Todos os status</option>{["OPEN", "IN_REVIEW", "RESOLVED", "DISMISSED"].map((value) => <option key={value} value={value}>{labels[value]}</option>)}</select><select aria-label="Severidade" className={inputClass} defaultValue={initial.filters.severity} name="severity"><option value="ALL">Todas as severidades</option>{["CRITICAL", "HIGH", "WARNING", "INFO"].map((value) => <option key={value} value={value}>{labels[value]}</option>)}</select><select aria-label="Entidade" className={inputClass} defaultValue={initial.filters.entityType} name="entityType"><option value="ALL">Todas as entidades</option>{["CONTACT", "ACCOUNT", "LEAD", "OPPORTUNITY", "INVOICE"].map((value) => <option key={value} value={value}>{labels[value]}</option>)}</select><Button type="submit" variant="secondary">Filtrar</Button></form>
      {initial.issues.length === 0 ? <EmptyState className="mt-4" title="Nenhuma ocorrência neste recorte" description="Ausência de ocorrência significa apenas que nenhuma regra ativa encontrou evidência no universo consultado." /> : <div className="mt-4 space-y-3">{initial.issues.map((item) => <article className="rounded-[var(--radius-panel)] border border-border bg-[var(--surface-subtle)] p-4" key={item.id}><header className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap gap-2"><StatusBadge tone={tone(item.severity)}>{labels[item.severity]}</StatusBadge><StatusBadge tone={tone(item.status)}>{labels[item.status]}</StatusBadge><StatusBadge>{labels[item.entityType] ?? item.entityType}</StatusBadge></div><h3 className="mt-2 font-semibold">{item.title}</h3><p className="mt-1 text-sm text-muted-foreground">{item.evidenceSummary}</p></div><p className="text-right text-xs text-muted-foreground">Prioridade {item.priority}/100<br />Regra {item.rule?.key ?? "indisponível"} v{item.rule?.version ?? "—"}</p></header><dl className="mt-3 grid gap-2 text-sm sm:grid-cols-3"><div><dt className="font-semibold">Registro</dt><dd className="break-all text-muted-foreground">{item.entityId}</dd></div><div><dt className="font-semibold">Prazo</dt><dd className="text-muted-foreground">{item.dueAt ? new Intl.DateTimeFormat("pt-BR", { timeZone: initial.timeZone, dateStyle: "short", timeStyle: "short" }).format(new Date(item.dueAt)) : "Sem SLA configurado"}</dd></div><div><dt className="font-semibold">Correção esperada</dt><dd className="text-muted-foreground">{item.rule?.remediation ?? "Consultar a regra."}</dd></div></dl>{initial.permissions.resolve && !["RESOLVED", "DISMISSED"].includes(item.status) ? <form className="mt-3 flex flex-wrap gap-2" onSubmit={(event) => issue(event, item.id, item.revision)}><input aria-label="Motivo ou comentário" className={`${inputClass} min-w-64 flex-1`} minLength={3} name="reason" placeholder="Evidência da decisão" required /><select aria-label="Ação" className={inputClass} name="action"><option value="ASSIGN_TO_ME">Assumir</option><option value="COMMENT">Comentar</option><option value="RESOLVE">Resolver</option><option value="DISMISS">Descartar falso positivo</option></select><Button disabled={pending} type="submit" variant="secondary">Registrar</Button></form> : null}</article>)}</div>}
    </Surface>

    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.3fr)_minmax(20rem,.7fr)]"><Surface><SectionHeader title="Possíveis duplicidades" description="Sinais fortes e possíveis permanecem separados de uma decisão humana." />{initial.candidates.length === 0 ? <EmptyState className="mt-4" compact title="Nenhum candidato aberto" description="Execute uma varredura para avaliar identificadores normalizados." /> : <div className="mt-4 space-y-3">{initial.candidates.map((item) => <article className="rounded-[var(--radius-control)] border border-border p-3" key={item.id}><div className="flex flex-wrap items-center justify-between gap-2"><div><StatusBadge tone={tone(item.strength)}>{labels[item.strength]}</StatusBadge><p className="mt-2 text-sm font-semibold">{labels[item.entityType]} · confiança {item.confidenceBps === null ? "não calculada" : `${(item.confidenceBps / 100).toFixed(0)}%`}</p><p className="mt-1 break-all text-xs text-muted-foreground">{item.leftEntityId}<br />{item.rightEntityId}</p></div>{initial.permissions.merge ? <div className="flex flex-col gap-2"><Button disabled={pending} onClick={() => openPreview(item, item.leftEntityId)} size="sm" variant="secondary">Manter primeiro</Button><Button disabled={pending} onClick={() => openPreview(item, item.rightEntityId)} size="sm" variant="secondary">Manter segundo</Button><Button disabled={pending} onClick={() => { const reason = window.prompt("Por que estes registros não são duplicados?"); if (reason && reason.trim().length >= 8) void action({ action: "DECIDE_CANDIDATE", data: { candidateId: item.id, decision: "NOT_DUPLICATE", reason, expectedRevision: item.revision } }, "Candidato encerrado como registros distintos."); }} size="sm" variant="ghost">Não são duplicados</Button></div> : null}</div></article>)}</div>}</Surface><Surface tone="subtle"><SectionHeader title="Regras ativas" description="Definições publicadas são imutáveis; mudanças exigem nova versão." /><ul className="mt-4 space-y-2">{initial.rules.length ? initial.rules.map((rule) => <li className="rounded-[var(--radius-control)] bg-card p-3 text-sm" key={rule.id}><div className="flex items-center justify-between gap-2"><strong>{rule.title}</strong><StatusBadge tone={tone(rule.status)}>{labels[rule.status]}</StatusBadge></div><p className="mt-1 text-muted-foreground">{rule.dimension} · v{rule.version} · SLA {rule.slaSeconds === null ? "não definido" : `${rule.slaSeconds}s`}</p></li>) : <li className="text-sm text-muted-foreground">As regras padrão serão publicadas na primeira execução confirmada.</li>}</ul></Surface></div>

    {preview ? <Surface tone={preview.blockers.length ? "critical" : "accent"}><SectionHeader title="Prévia de merge" description={`Origem: ${preview.source.label} · sobrevivente: ${preview.survivor.label}`} action={<Button onClick={() => setPreview(null)} variant="ghost">Fechar prévia</Button>} /><div className="mt-4 grid gap-4 lg:grid-cols-[1fr_20rem]"><form className="space-y-3" onSubmit={createPlan}>{preview.fields.map((field) => <fieldset className="rounded-[var(--radius-control)] border border-border p-3" key={field.fieldPath}><legend className="px-1 text-sm font-semibold">{field.label}</legend><label className="mt-1 flex gap-2 text-sm"><input checked={decisions[field.fieldPath] === "SURVIVOR"} name={field.fieldPath} onChange={() => setDecisions((current) => ({ ...current, [field.fieldPath]: "SURVIVOR" }))} type="radio" />Sobrevivente: {field.survivorValue ?? "ausente"}</label><label className="mt-2 flex gap-2 text-sm"><input checked={decisions[field.fieldPath] === "SOURCE"} name={field.fieldPath} onChange={() => setDecisions((current) => ({ ...current, [field.fieldPath]: "SOURCE" }))} type="radio" />Origem: {field.sourceValue ?? "ausente"}</label></fieldset>)}<label className="block text-sm font-semibold">Motivo do plano<textarea className="mt-1 min-h-24 w-full rounded-[var(--radius-control)] border border-border bg-card p-3 font-normal" minLength={8} name="reason" required /></label><Button disabled={pending} type="submit">Registrar plano</Button></form><aside><h3 className="font-semibold">Impacto relacional</h3><dl className="mt-2 space-y-2 text-sm">{Object.entries(preview.relationships).map(([key, value]) => <div className="flex justify-between gap-3" key={key}><dt>{key}</dt><dd className="font-semibold tabular-nums">{value}</dd></div>)}</dl><h3 className="mt-5 font-semibold">Bloqueios</h3>{preview.blockers.length ? <ul className="mt-2 list-disc space-y-2 pl-5 text-sm text-destructive">{preview.blockers.map((item) => <li key={item}>{item}</li>)}</ul> : <p className="mt-2 text-sm text-muted-foreground">Nenhum bloqueio atual. O plano ainda exige aplicação explícita.</p>}</aside></div></Surface> : null}

    <div className="grid gap-5 lg:grid-cols-2"><Surface><SectionHeader title="Planos e reversibilidade" description="Aplicação e rollback usam fingerprint, lock, ledger relacional e transação serializável." />{initial.plans.length === 0 ? <EmptyState className="mt-4" compact title="Nenhum merge planejado" description="A prévia deve ser registrada antes de qualquer alteração." /> : <ul className="mt-4 space-y-3">{initial.plans.map((plan) => <li className="rounded-[var(--radius-control)] border border-border p-3" key={plan.id}><div className="flex flex-wrap items-center justify-between gap-2"><div><StatusBadge tone={tone(plan.status)}>{labels[plan.status]}</StatusBadge><p className="mt-2 text-sm">{labels[plan.entityType]} · <span className="break-all">{plan.sourceEntityId}</span> → <span className="break-all">{plan.survivorEntityId}</span></p><p className="mt-1 text-xs text-muted-foreground">{plan.reason}</p></div>{plan.status === "READY" && initial.permissions.merge ? <Button disabled={pending} onClick={() => { if (window.confirm("Confirmar o merge? IDs e fatos históricos serão preservados, e somente vínculos seguros serão movidos.")) void action({ action: "APPLY_MERGE", data: { mergePlanId: plan.id, expectedRevision: plan.revision, idempotencyKey: requestKey("merge"), confirmation: "CONFIRMAR MERGE" } }, "Merge aplicado com ledger reversível e auditoria."); }}>Aplicar merge</Button> : plan.status === "APPLIED" && initial.permissions.rollback ? <Button disabled={pending} onClick={() => { const reason = window.prompt("Motivo da reversão (mínimo 8 caracteres):"); if (reason && reason.trim().length >= 8 && window.confirm("Confirmar reversão? Ela será bloqueada se os registros mudaram após o merge.")) void action({ action: "ROLLBACK_MERGE", data: { mergePlanId: plan.id, expectedRevision: plan.revision, idempotencyKey: requestKey("rollback"), reason, confirmation: "CONFIRMAR REVERSÃO" } }, "Merge revertido conforme o ledger original."); }} variant="secondary">Reverter</Button> : null}</div></li>)}</ul>}</Surface><Surface><SectionHeader title="Reconciliação financeira" description="O ledger de pagamentos é fato; o valor pago da cobrança é uma projeção comparável." />{initial.reconciliations.length === 0 ? <EmptyState className="mt-4" compact title="Sem snapshots" description="Execute a varredura confirmada para persistir resultados datados." /> : <DataTableShell className="mt-4"><table><thead><tr><th>Status</th><th>Entidade</th><th>Data-base</th></tr></thead><tbody>{initial.reconciliations.map((item) => <tr key={item.id}><td><StatusBadge tone={tone(item.status)}>{labels[item.status]}</StatusBadge></td><td><span className="block text-sm">{item.summary}</span><small className="break-all text-muted-foreground">{item.entityId ?? "Sem entidade"}</small></td><td>{new Intl.DateTimeFormat("pt-BR", { timeZone: item.timeZone, dateStyle: "short", timeStyle: "short" }).format(new Date(item.asOf))}</td></tr>)}</tbody></table></DataTableShell>}</Surface></div>
  </div>;
}
