import { createHash } from "node:crypto";
import type { PrismaClient } from "@/generated/prisma/client";
import { DEMO_WORKSPACE_SLUG } from "@/modules/settings/application/demo-seed-service";

function stableId(key:string){const hex=createHash("sha256").update(`politizai:crm53:${key}`).digest("hex").slice(0,32);return `${hex.slice(0,8)}-${hex.slice(8,12)}-5${hex.slice(13,16)}-8${hex.slice(17,20)}-${hex.slice(20)}`;}
export async function seedCustomerServiceDemoData(database:PrismaClient){
 const workspace=await database.workspace.findUniqueOrThrow({where:{slug:DEMO_WORKSPACE_SLUG}});const actor=await database.actor.findFirstOrThrow({where:{workspaceId:workspace.id,type:"SYSTEM"}});const owner=await database.workspaceMember.findFirstOrThrow({where:{workspaceId:workspace.id,status:"ACTIVE",deletedAt:null,role:{key:"closer"}},include:{teamMemberships:{where:{deletedAt:null},take:1}}});const policy=await database.customerServiceSlaPolicyVersion.findFirstOrThrow({where:{workspaceId:workspace.id,status:"PUBLISHED"},orderBy:{version:"desc"}});const accounts=await database.account.findMany({where:{workspaceId:workspace.id,deletedAt:null},orderBy:{name:"asc"},take:4});const now=new Date();
 const scenarios=[
  {status:"RESOLVED" as const,subject:"Confirmar acesso da equipe",category:"ACTIVATION" as const,priority:"NORMAL" as const,created:-48,response:-47,resolved:-30,next:2,resolution:"Acesso validado com o cliente."},
  {status:"OPEN" as const,subject:"Dúvida sobre adoção do fluxo",category:"ADOPTION" as const,priority:"HIGH" as const,created:-4,response:null,resolved:null,next:-1,resolution:null},
  {status:"IN_PROGRESS" as const,subject:"Revisar cobrança percebida",category:"BILLING" as const,priority:"URGENT" as const,created:-30,response:-29,resolved:null,next:-2,resolution:null},
  {status:"RESOLVED" as const,subject:"Ajuste no acompanhamento de entrega",category:"DELIVERY" as const,priority:"HIGH" as const,created:-72,response:-68,resolved:-20,next:1,resolution:"Ajuste confirmado e comunicado ao cliente."},
 ];
 for(const [index,scenario] of scenarios.entries()){const account=accounts[index];if(!account)continue;const id=stableId(`request:${account.id}`);const createdAt=new Date(now.getTime()+scenario.created*3_600_000);const respondedAt=scenario.response===null?null:new Date(now.getTime()+scenario.response*3_600_000);const resolvedAt=scenario.resolved===null?null:new Date(now.getTime()+scenario.resolved*3_600_000);const exists=await database.customerRequest.findUnique({where:{workspaceId_idempotencyKey:{workspaceId:workspace.id,idempotencyKey:`crm53:demo:request:${account.id}`}},select:{id:true}});if(!exists){await database.customerRequest.create({data:{id,workspaceId:workspace.id,accountId:account.id,channel:"MANUAL",subject:scenario.subject,description:"Cenário fictício controlado para demonstrar atendimento ao cliente.",category:scenario.category,priority:scenario.priority,status:scenario.status,ownerMemberId:owner.id,teamId:owner.teamMemberships[0]?.teamId??null,queueId:null,slaPolicyVersionId:policy.id,firstResponseDueAt:new Date(createdAt.getTime()+policy.firstResponseMinutes*60_000),resolutionDueAt:new Date(createdAt.getTime()+policy.resolutionMinutes*60_000),firstRespondedAt:respondedAt,firstResponseSeconds:respondedAt?Math.floor((respondedAt.getTime()-createdAt.getTime())/1000):null,firstResponseBreached:respondedAt?respondedAt>new Date(createdAt.getTime()+policy.firstResponseMinutes*60_000):null,resolvedAt,resolutionSeconds:resolvedAt?Math.floor((resolvedAt.getTime()-createdAt.getTime())/1000):null,resolutionBreached:resolvedAt?resolvedAt>new Date(createdAt.getTime()+policy.resolutionMinutes*60_000):null,nextActionDescription:scenario.status==="RESOLVED"?"Validar satisfação registrada":"Executar retorno ao cliente",nextActionAt:new Date(now.getTime()+scenario.next*3_600_000),resolutionNote:scenario.resolution,idempotencyKey:`crm53:demo:request:${account.id}`,createdByActorId:actor.id,updatedByActorId:actor.id,createdAt,updatedAt:createdAt}});await database.customerRequestEvent.create({data:{id:stableId(`event:${id}`),workspaceId:workspace.id,requestId:id,accountId:account.id,sequence:1,type:"CREATED",newStatus:scenario.status,reason:"Cenário fictício controlado CRM-53.",safeMetadata:{demo:true},actorId:actor.id,idempotencyKey:`crm53:demo:event:${account.id}`,occurredAt:createdAt}});}}
 const csat=await database.customerSurveyDefinition.findFirstOrThrow({where:{workspaceId:workspace.id,type:"CSAT"}});const nps=await database.customerSurveyDefinition.findFirstOrThrow({where:{workspaceId:workspace.id,type:"NPS"}});for(const [index,account] of accounts.entries()){const definition=index<2?csat:nps;const version=await database.customerSurveyVersion.findFirstOrThrow({where:{workspaceId:workspace.id,definitionId:definition.id,status:"PUBLISHED"}});const request=await database.customerRequest.findUnique({where:{workspaceId_idempotencyKey:{workspaceId:workspace.id,idempotencyKey:`crm53:demo:request:${account.id}`}}});const invitationId=stableId(`invite:${account.id}:${definition.type}`);const answered=index!==1;await database.customerSurveyInvitation.upsert({where:{workspaceId_idempotencyKey:{workspaceId:workspace.id,idempotencyKey:`crm53:demo:invite:${account.id}:${definition.type}`}},create:{id:invitationId,workspaceId:workspace.id,accountId:account.id,requestId:definition.type==="CSAT"&&request?.resolvedAt?request.id:null,surveyVersionId:version.id,channel:"MANUAL",status:answered?"RESPONDED":"CREATED",simulated:true,expiresAt:new Date(now.getTime()+7*86_400_000),respondedAt:answered?new Date(now.getTime()-3_600_000):null,idempotencyKey:`crm53:demo:invite:${account.id}:${definition.type}`,createdByActorId:actor.id,createdAt:new Date(now.getTime()-2*3_600_000)},update:{}});if(answered){const value=index===0?5:index===2?4:9;const classification=definition.type==="NPS"?(value<=6?"DETRACTOR":value<=8?"PASSIVE":"PROMOTER"):(value>=4?"SATISFIED":"DISSATISFIED");const prior=await database.customerSurveyResponse.findUnique({where:{workspaceId_idempotencyKey:{workspaceId:workspace.id,idempotencyKey:`crm53:demo:response:${account.id}:${definition.type}`}},select:{id:true}});if(!prior)await database.customerSurveyResponse.create({data:{id:stableId(`response:${account.id}:${definition.type}`),workspaceId:workspace.id,invitationId,accountId:account.id,surveyVersionId:version.id,value,classification,comment:value<=4?"Cenário fictício: cliente solicitou acompanhamento.":"Cenário fictício: atendimento claro.",channel:"MANUAL",answeredAt:new Date(now.getTime()-3_600_000),idempotencyKey:`crm53:demo:response:${account.id}:${definition.type}`,createdByActorId:actor.id}});}}
 return {requests:scenarios.length,invitations:accounts.length,responses:accounts.length-1};
}
