import Link from "next/link";
import { redirect } from "next/navigation";
import { PageHeader } from "@/components/layout/page-header";
import { requirePageAuthentication } from "@/modules/auth/http/authentication-guards";
import { getRevenueService } from "@/modules/revenue/application/revenue-service";
import { AccessDeniedError } from "@/modules/users/permissions/authorization-errors";
export const dynamic="force-dynamic";
const money=(c:bigint)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(c)/100);
export default async function RevenuePage(){const context=await requirePageAuthentication();let screen;try{screen=await getRevenueService().list(context);}catch(e){if(e instanceof AccessDeniedError)redirect("/acesso-negado");throw e;}return <main className="page-canvas page-canvas-wide"><PageHeader eyebrow="Receita recorrente" title="Assinaturas e ledger" description="MRR reconstruído exclusivamente por movimentos efetivos, sem integração contábil ou de pagamento." meta={`${context.displayName} · ${screen.timeZone}`}/><section className="metric-grid"><article className="metric-card"><span>MRR ativo</span><strong>{money(screen.mrrCents)}</strong><small>Corte {new Date(screen.cutoff).toLocaleString("pt-BR",{timeZone:screen.timeZone})}</small></article><article className="metric-card"><span>ARR</span><strong>{money(screen.arrCents)}</strong><small>MRR × 12</small></article><article className="metric-card"><span>Assinaturas</span><strong>{screen.subscriptions.length}</strong><small>Dentro do seu escopo</small></article></section><section className="surface-panel"><h2>Assinaturas</h2>{screen.subscriptions.length===0?<div className="empty-state"><strong>Nenhuma assinatura registrada</strong><p>Crie uma explicitamente a partir de um contrato aceito. Aceite contratual não ativa receita automaticamente.</p></div>:<div className="table-scroll"><table><thead><tr><th>Número</th><th>Conta</th><th>Produto</th><th>Status</th><th>MRR atual</th><th>Início</th></tr></thead><tbody>{screen.subscriptions.map(s=><tr key={s.id}><td><Link href={`/receita/${s.id}`}>{s.subscriptionNumber}</Link></td><td>{s.accountNameSnapshot}</td><td>{s.productNameSnapshot}</td><td>{s.status}</td><td>{money(s.currentMrrCents)}</td><td>{s.startsAt.toLocaleDateString("pt-BR",{timeZone:screen.timeZone})}</td></tr>)}</tbody></table></div>}</section><p className="helper-text">{screen.formula}. Valores em BRL; competência por data efetiva.</p></main>}
