import { randomUUID } from "node:crypto";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { PrismaClient } from "@/generated/prisma/client";
import type { AuthenticatedContext } from "@/modules/auth/application/authenticated-context";
import { createCustomerServiceBackfillService } from "@/modules/customer-service/application/customer-service-backfill-service";
import { createCustomerServiceService } from "@/modules/customer-service/application/customer-service-service";
import { seedDemoDatabase } from "@/modules/settings/application/demo-seed-service";
import { createAuthorizationService } from "@/modules/users/permissions/authorization-service";
import { createPostgresAdapter } from "@/shared/core/database/postgres-adapter";

const connectionString=process.env.DATABASE_URL;if(!connectionString)throw new Error("DATABASE_URL is required for CRM-53 tests.");if(!/^politizai_test_[a-z0-9_]+$/.test(process.env.PRISMA_TEST_SCHEMA??""))throw new Error("CRM-53 requires an ephemeral politizai_test_* schema.");
const database=new PrismaClient({adapter:createPostgresAdapter(connectionString,{max:12})});const authorization=createAuthorizationService({database});let clock=new Date("2053-02-01T12:00:00.000Z");const service=createCustomerServiceService({database,authorization,now:()=>clock});let workspaceId:string;let admin:AuthenticatedContext;let closer:AuthenticatedContext;let viewer:AuthenticatedContext;let accountId:string;let teamId:string;
async function context(email:string){const member=await database.workspaceMember.findFirstOrThrow({where:{workspaceId,user:{normalizedEmail:email}},include:{role:true,user:true}});const actor=await database.actor.findFirstOrThrow({where:{workspaceId,userId:member.userId,type:"HUMAN"}});return {sessionId:randomUUID(),workspaceId,workspaceSlug:"politizai",userId:member.userId,memberId:member.id,actorId:actor.id,roleId:member.roleId,roleKey:member.role.key,roleName:member.role.name,displayName:member.user.displayName} satisfies AuthenticatedContext;}
beforeAll(async()=>{workspaceId=(await seedDemoDatabase(database,{DATABASE_URL:connectionString,NODE_ENV:"test"})).workspaceId;[admin,closer,viewer]=await Promise.all([context("admin@demo.politizai.local"),context("closer1@demo.politizai.local"),context("viewer@demo.politizai.local")]);teamId=(await database.teamMember.findFirstOrThrow({where:{workspaceId,workspaceMemberId:closer.memberId,deletedAt:null}})).teamId;accountId=(await database.account.create({data:{workspaceId,name:"Cliente CRM-53 Fictício",normalizedName:"cliente crm 53 ficticio",origin:"SEED",quality:"CONFIRMED",createdByActorId:admin.actorId,updatedByActorId:admin.actorId}})).id;await database.customerPortfolioAssignment.create({data:{workspaceId,accountId,ownerMemberId:closer.memberId,teamId,reason:"Carteira fictícia do teste CRM-53.",nextActionDescription:"Acompanhar atendimento fictício.",nextActionAt:new Date("2053-02-02T12:00:00Z"),validFrom:clock,idempotencyKey:"crm53:portfolio:001",createdByActorId:admin.actorId}});});afterAll(async()=>database.$disconnect());
const openInput=()=>({accountId,channel:"MANUAL" as const,subject:"Dúvida de ativação",description:"Cliente precisa confirmar o primeiro acesso.",category:"ACTIVATION" as const,priority:"HIGH" as const,ownerMemberId:closer.memberId,teamId,nextActionDescription:"Responder ao cliente",nextActionAt:new Date("2053-02-01T15:00:00.000Z"),idempotencyKey:"crm53:request:001"});

describe("CRM-53 solicitações, SLA e satisfação",()=>{
 it("abre uma única solicitação sob concorrência e congela a versão do SLA",async()=>{const[first,second]=await Promise.all([service.open(closer,openInput()),service.open(closer,openInput())]);expect(second.id).toBe(first.id);expect(first.slaPolicyVersionId).toBeTruthy();expect(first.firstResponseDueAt.toISOString()).toBe("2053-02-01T13:00:00.000Z");expect(await database.customerRequestEvent.count({where:{workspaceId,requestId:first.id,type:"CREATED"}})).toBe(1);});
 it("registra primeira resposta uma única vez e resolve com segundos reproduzíveis",async()=>{const request=await database.customerRequest.findUniqueOrThrow({where:{workspaceId_idempotencyKey:{workspaceId,idempotencyKey:"crm53:request:001"}}});clock=new Date("2053-02-01T12:30:00.000Z");const responded=await service.act(closer,request.id,{action:"FIRST_RESPONSE",expectedRevision:request.revision,reason:"Resposta humana registrada no atendimento.",idempotencyKey:"crm53:first-response:001"});expect(responded.firstResponseSeconds).toBe(1800);expect(responded.firstResponseBreached).toBe(false);const repeated=await service.act(closer,request.id,{action:"FIRST_RESPONSE",expectedRevision:responded.revision,reason:"Tentativa repetida da primeira resposta.",idempotencyKey:"crm53:first-response:002"});expect(repeated.revision).toBe(responded.revision);clock=new Date("2053-02-01T14:00:00.000Z");const resolved=await service.act(closer,request.id,{action:"RESOLVE",expectedRevision:responded.revision,reason:"Acesso confirmado com o cliente responsável.",resolutionNote:"Primeiro acesso validado com sucesso.",idempotencyKey:"crm53:resolve:001"});expect(resolved.resolutionSeconds).toBe(7200);expect(resolved.resolutionBreached).toBe(false);});
 it("rejeita transição inválida, exige revisão atual e permite reabertura motivada",async()=>{const request=await database.customerRequest.findUniqueOrThrow({where:{workspaceId_idempotencyKey:{workspaceId,idempotencyKey:"crm53:request:001"}}});await expect(service.act(closer,request.id,{action:"START",expectedRevision:request.revision,reason:"Transição inválida após resolução registrada.",idempotencyKey:"crm53:invalid:001"})).rejects.toMatchObject({code:"INVALID_TRANSITION"});await expect(service.act(closer,request.id,{action:"REOPEN",expectedRevision:1,reason:"Reabertura com revisão desatualizada.",nextActionDescription:"Retomar análise",nextActionAt:new Date("2053-02-02T12:00:00Z"),idempotencyKey:"crm53:stale:001"})).rejects.toMatchObject({code:"REVISION_CONFLICT"});const reopened=await service.act(closer,request.id,{action:"REOPEN",expectedRevision:request.revision,reason:"Cliente informou que o acesso voltou a falhar.",nextActionDescription:"Revalidar acesso com o cliente",nextActionAt:new Date("2053-02-02T12:00:00Z"),idempotencyKey:"crm53:reopen:001"});expect(reopened.status).toBe("IN_PROGRESS");expect(reopened.resolvedAt).toBeNull();});
 it("versiona pesquisas, valida escala, classifica NPS e preserva resposta append-only",async()=>{const invitation=await service.invite(closer,{accountId,requestId:null,surveyType:"NPS",channel:"MANUAL",expiresAt:new Date("2053-02-10T12:00:00Z"),idempotencyKey:"crm53:invite:nps:001"});const response=await service.respondSurvey(closer,{invitationId:invitation.id,value:6,comment:"Cenário fictício de acompanhamento.",answeredAt:new Date("2053-02-01T15:00:00Z"),idempotencyKey:"crm53:response:nps:001"});expect(response.classification).toBe("DETRACTOR");expect((await service.respondSurvey(closer,{invitationId:invitation.id,value:6,comment:"Cenário fictício de acompanhamento.",answeredAt:new Date("2053-02-01T15:00:00Z"),idempotencyKey:"crm53:response:nps:001"})).id).toBe(response.id);await expect(service.respondSurvey(closer,{invitationId:invitation.id,value:11,answeredAt:new Date("2053-02-01T15:00:00Z"),supersedesId:response.id,idempotencyKey:"crm53:response:nps:invalid"})).rejects.toThrow();await expect(database.customerSurveyResponse.update({where:{id:response.id},data:{value:10}})).rejects.toThrow();});
 it("reconcilia métricas e nega mutação ao visualizador e contexto cruzado",async()=>{const result=await service.screen(closer,{from:"2053-02-01T00:00:00Z",to:"2053-02-03T00:00:00Z"});expect(result.total).toBe(1);expect(result.metrics.open).toBe(1);expect(result.satisfaction.find(item=>item.type==="NPS")).toMatchObject({value:-100,validResponses:1,responseRate:1});const surveyDrilldown=await service.screen(closer,{surveyType:"NPS"});expect(surveyDrilldown.items.map(item=>item.accountId)).toEqual([accountId]);const overdueDrilldown=await service.screen(closer,{sla:"RESOLUTION_OVERDUE"});expect(overdueDrilldown.items.every(item=>item.resolutionOverdue)).toBe(true);await expect(service.open(viewer,{...openInput(),idempotencyKey:"crm53:viewer:denied"})).rejects.toThrow();await expect(service.detail({...admin,workspaceId:randomUUID()},result.items[0]!.id)).rejects.toThrow();});
 it("backfill apenas sinaliza ambiguidade, faz replay e não fabrica solicitações",async()=>{const ambiguous=await database.account.create({data:{workspaceId,name:"Conta ambígua CRM-53",normalizedName:"conta ambigua crm 53",origin:"SEED",quality:"CONFIRMED",createdByActorId:admin.actorId,updatedByActorId:admin.actorId}});await database.conversation.create({data:{workspaceId,accountId:ambiguous.id,assigneeMemberId:closer.memberId,channel:"INTERNAL",status:"OPEN",subject:"Conversa sem prova de solicitação",createdByActorId:admin.actorId,updatedByActorId:admin.actorId}});const backfill=createCustomerServiceBackfillService({database,authorization,now:()=>clock});const before=await database.customerRequest.count({where:{workspaceId}});const dry=await backfill.run(admin,{mode:"DRY_RUN",runKey:"crm53:backfill:dry:001"});const replay=await backfill.run(admin,{mode:"DRY_RUN",runKey:"crm53:backfill:dry:001"});expect(dry.reviewCount).toBe(1);expect(replay.replay).toBe(true);expect(await database.customerRequest.count({where:{workspaceId}})).toBe(before);});
});
