import { randomUUID } from "node:crypto";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { PrismaClient } from "@/generated/prisma/client";
import type { AuthenticatedContext } from "@/modules/auth/application/authenticated-context";
import { createCustomerSuccessBackfillService } from "@/modules/customer-success/application/customer-success-backfill-service";
import { createCustomerSuccessService } from "@/modules/customer-success/application/customer-success-service";
import { createPostSaleOperatingReviewService } from "@/modules/customer-success/application/post-sale-operating-review-service";
import { seedDemoDatabase } from "@/modules/settings/application/demo-seed-service";
import { createAuthorizationService } from "@/modules/users/permissions/authorization-service";
import { createPostgresAdapter } from "@/shared/core/database/postgres-adapter";

const connectionString = process.env.DATABASE_URL;
if (!connectionString) throw new Error("DATABASE_URL is required for CRM-52 tests.");
if (!/^politizai_test_[a-z0-9_]+$/.test(process.env.PRISMA_TEST_SCHEMA ?? "")) throw new Error("CRM-52 requires an ephemeral politizai_test_* schema.");
const database = new PrismaClient({ adapter: createPostgresAdapter(connectionString, { max: 12 }) });
const authorization = createAuthorizationService({ database });
const clock = new Date("2052-04-15T15:00:00.000Z");
const service = createCustomerSuccessService({ database, authorization, now: () => clock });
const operatingReview = createPostSaleOperatingReviewService({ database, authorization, now: () => clock });
let workspaceId:string; let admin:AuthenticatedContext; let closer:AuthenticatedContext; let viewer:AuthenticatedContext; let accountId:string;

async function context(email:string){const member=await database.workspaceMember.findFirstOrThrow({where:{workspaceId,user:{normalizedEmail:email}},include:{role:true,user:true}});const actor=await database.actor.findFirstOrThrow({where:{workspaceId,userId:member.userId,type:"HUMAN"}});return {sessionId:randomUUID(),workspaceId,workspaceSlug:"politizai",userId:member.userId,memberId:member.id,actorId:actor.id,roleId:member.roleId,roleKey:member.role.key,roleName:member.role.name,displayName:member.user.displayName} satisfies AuthenticatedContext;}

beforeAll(async()=>{workspaceId=(await seedDemoDatabase(database,{DATABASE_URL:connectionString,NODE_ENV:"test"})).workspaceId;[admin,closer,viewer]=await Promise.all([context("admin@demo.politizai.local"),context("closer1@demo.politizai.local"),context("viewer@demo.politizai.local")]);accountId=(await database.account.create({data:{workspaceId,name:"Conta CS Fictícia",normalizedName:"conta cs ficticia",origin:"SEED",quality:"CONFIRMED",createdByActorId:admin.actorId,updatedByActorId:admin.actorId}})).id;});
afterAll(async()=>database.$disconnect());

describe("CRM-52 carteira, plano e saúde",()=>{
 it("atribui sob concorrência, preserva histórico e não duplica replay",async()=>{const input={accountId,ownerMemberId:closer.memberId,teamId:null,queueId:null,priority:1,nextActionDescription:"Confirmar objetivo de sucesso",nextActionAt:new Date("2052-04-16T15:00:00.000Z"),reason:"Responsável de Customer Success confirmado.",idempotencyKey:"crm52:portfolio:001"};const[first,second]=await Promise.all([service.assignPortfolio(admin,input),service.assignPortfolio(admin,input)]);expect(second.id).toBe(first.id);expect(await database.customerPortfolioAssignment.count({where:{workspaceId,accountId,validTo:null}})).toBe(1);expect(await database.customerSuccessEvent.count({where:{workspaceId,accountId,type:"PORTFOLIO_ASSIGNED"}})).toBe(1);});
 it("impede visualizador de mutar e respeita escopo do closer",async()=>{await expect(service.assignPortfolio(viewer,{accountId,ownerMemberId:viewer.memberId,priority:2,nextActionDescription:"Tentar alteração",nextActionAt:new Date("2052-04-16T15:00:00.000Z"),reason:"Tentativa sem autorização suficiente.",idempotencyKey:"crm52:denied:001"})).rejects.toThrow();expect((await service.screen(closer)).items.map(item=>item.accountId)).toContain(accountId);});
 it("cria plano versionado, exige dependência/evidência e mantém histórico",async()=>{const plan=await service.createPlan(closer,{accountId,title:"Plano de adoção",objective:"Comprovar adoção e primeiro resultado observado.",targetAt:new Date("2052-05-15T15:00:00.000Z"),nextActionDescription:"Validar objetivo",nextActionAt:new Date("2052-04-16T15:00:00.000Z"),reason:"Plano acordado explicitamente com o responsável.",idempotencyKey:"crm52:plan:001"});expect(plan.templateVersionId).not.toBeNull();const replay=await service.createPlan(closer,{accountId,title:"Plano de adoção",objective:"Comprovar adoção e primeiro resultado observado.",targetAt:new Date("2052-05-15T15:00:00.000Z"),nextActionDescription:"Validar objetivo",nextActionAt:new Date("2052-04-16T15:00:00.000Z"),reason:"Plano acordado explicitamente com o responsável.",idempotencyKey:"crm52:plan:001"});expect(replay.id).toBe(plan.id);const milestones=await database.successPlanMilestone.findMany({where:{workspaceId,planId:plan.id},orderBy:{position:"asc"}});expect(milestones).toHaveLength(3);await expect(service.actOnPlan(closer,plan.id,{action:"COMPLETE_MILESTONE",expectedRevision:milestones[1]!.revision,milestoneId:milestones[1]!.id,evidence:"Adoção observada.",reason:"Tentativa fora da dependência definida.",idempotencyKey:"crm52:milestone:invalid"})).rejects.toMatchObject({code:"DEPENDENCY_REQUIRED"});await service.actOnPlan(closer,plan.id,{action:"COMPLETE_MILESTONE",expectedRevision:milestones[0]!.revision,milestoneId:milestones[0]!.id,evidence:"Objetivo confirmado pelo cliente.",reason:"Evidência validada pelo responsável da carteira.",idempotencyKey:"crm52:milestone:001"});expect(await database.customerSuccessEvent.count({where:{workspaceId,accountId,type:"MILESTONE_COMPLETED"}})).toBe(1);});
 it("registra dados insuficientes sem converter ausência em nota negativa e preserva snapshots",async()=>{const first=await service.assessHealth(closer,{accountId,cutoffAt:clock,idempotencyKey:"crm52:health:001"});expect(first.status).toBe("INSUFFICIENT");expect(first.score).toBeNull();expect(first.missingSignalCount).toBeGreaterThan(0);const replay=await service.assessHealth(closer,{accountId,cutoffAt:clock,idempotencyKey:"crm52:health:001"});expect(replay.id).toBe(first.id);const second=await service.assessHealth(closer,{accountId,cutoffAt:new Date(clock.getTime()+1000),idempotencyKey:"crm52:health:002"});expect(second.supersedesId).toBe(first.id);await expect(database.customerHealthAssessment.update({where:{id:first.id},data:{explanation:"mutação indevida"}})).rejects.toThrow();expect(await database.customerHealthEvidence.count({where:{workspaceId,assessmentId:first.id}})).toBe(5);});
 it("acompanha adoção, entregáveis, capacidade, solicitações, saúde, resultado e riscos persistidos",async()=>{const review=await operatingReview.accountReview(closer,accountId);expect(review.account.id).toBe(accountId);expect(review.adoption).toMatchObject({total:3,completed:1});expect(review.capacity.formula).toContain("carteiras ativas + planos abertos + solicitações abertas");expect(review).toHaveProperty("deliverables");expect(review).toHaveProperty("requests");expect(review).toHaveProperty("health");expect(review).toHaveProperty("satisfaction");expect(review).toHaveProperty("result.evidencedMilestones",1);expect(Array.isArray(review.risks)).toBe(true);const screen=await service.screen(closer);expect(screen.items.find(item=>item.accountId===accountId)?.operatingReview.account.id).toBe(accountId);expect(Array.isArray(screen.alerts)).toBe(true);expect(screen.metrics.postSaleAlerts).toBe(screen.alerts.length);});
 it("alerta quando a satisfação do cliente cai",async()=>{const definition=await database.customerSurveyDefinition.create({data:{workspaceId,key:"csat-alert",name:"CSAT de relacionamento",type:"CSAT",createdByActorId:admin.actorId,updatedByActorId:admin.actorId}});const version=await database.customerSurveyVersion.create({data:{workspaceId,definitionId:definition.id,version:1,status:"PUBLISHED",question:"Como está sua satisfação?",minValue:1,maxValue:5,effectiveFrom:new Date("2052-01-01T00:00:00.000Z"),publishedAt:new Date("2052-01-01T00:00:00.000Z"),createdByActorId:admin.actorId}});await database.customerSurveyDefinition.update({where:{id:definition.id},data:{currentVersionId:version.id}});for(const [suffix,value,answeredAt] of [["previous",5,"2052-04-01T12:00:00.000Z"],["latest",2,"2052-04-14T12:00:00.000Z"]] as const){const invitation=await database.customerSurveyInvitation.create({data:{workspaceId,accountId,surveyVersionId:version.id,channel:"EMAIL",status:"RESPONDED",expiresAt:new Date("2052-05-01T00:00:00.000Z"),respondedAt:new Date(answeredAt),idempotencyKey:`crm52:survey:${suffix}`,createdByActorId:admin.actorId}});await database.customerSurveyResponse.create({data:{workspaceId,invitationId:invitation.id,accountId,surveyVersionId:version.id,value,classification:"TEST",channel:"EMAIL",answeredAt:new Date(answeredAt),idempotencyKey:`crm52:response:${suffix}`,createdByActorId:admin.actorId}});}const review=await operatingReview.accountReview(closer,accountId);expect(review.satisfaction[0]).toMatchObject({type:"CSAT",latestValue:2,previousValue:5,declining:true,deltaPoints:-75});const screen=await service.screen(closer);expect(screen.alerts).toEqual(expect.arrayContaining([expect.objectContaining({accountId,type:"SATISFACTION_DROP",severity:"HIGH"})]));});
 it("bloqueia referência cruzada entre workspaces por constraint composta",async()=>{const other=await database.workspace.create({data:{slug:`crm52-other-${randomUUID().slice(0,8)}`,name:"Outro workspace"}});const actor=await database.actor.create({data:{workspaceId:other.id,type:"SYSTEM",key:"system",displayName:"Sistema externo"}});const queue=await database.queue.create({data:{workspaceId:other.id,key:"general",name:"Fila externa",isGeneral:true,createdByActorId:actor.id,updatedByActorId:actor.id}});await expect(database.customerPortfolioAssignment.create({data:{workspaceId:other.id,accountId,queueId:queue.id,ownerMemberId:null,state:"REVIEW_REQUIRED",reason:"Referência cruzada deve falhar.",priority:2,validFrom:clock,idempotencyKey:"cross-workspace",createdByActorId:actor.id,updatedAt:clock}})).rejects.toThrow();});
 it("backfill nasce em dry-run, faz replay e não inventa responsável",async()=>{const backfill=createCustomerSuccessBackfillService({database,authorization,now:()=>clock});const dry=await backfill.run(admin,{mode:"DRY_RUN",runKey:"crm52:backfill:dry:001"});const replay=await backfill.run(admin,{mode:"DRY_RUN",runKey:"crm52:backfill:dry:001"});expect(dry.replay).toBe(false);expect(replay.replay).toBe(true);});
});
