import { randomUUID } from "node:crypto";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { PrismaClient } from "@/generated/prisma/client";
import type { AuthenticatedContext } from "@/modules/auth/application/authenticated-context";
import type { ServiceActorContext } from "@/modules/auth/application/service-actor-context";
import { createGeographicIntelligenceService } from "@/modules/geography/application/geographic-intelligence-service";
import { createLeadIntakeService } from "@/modules/leads/application/lead-intake-service";
import { getMetricsService } from "@/modules/metrics/application/metrics-service";
import { seedDemoDatabase } from "@/modules/settings/application/demo-seed-service";
import { AccessDeniedError } from "@/modules/users/permissions/authorization-errors";
import { createAuthorizationService } from "@/modules/users/permissions/authorization-service";
import { createPostgresAdapter } from "@/shared/core/database/postgres-adapter";

const connectionString=process.env.DATABASE_URL;if(!connectionString)throw new Error("DATABASE_URL is required.");
if(!/^politizai_test_[a-z0-9_]+$/.test(process.env.PRISMA_TEST_SCHEMA??""))throw new Error("CRM-42 integration test requires an ephemeral schema.");
const database=new PrismaClient({adapter:createPostgresAdapter(connectionString,{max:16})});const authorization=createAuthorizationService({database});const now=new Date("2046-05-20T15:00:00.000Z");let workspaceId:string;let manager:AuthenticatedContext;let viewer:AuthenticatedContext;let system:ServiceActorContext;let sourceKey:string;const leadIds:string[]=[];
async function context(email:string){const member=await database.workspaceMember.findFirstOrThrow({where:{workspaceId,user:{normalizedEmail:email}},include:{role:true,user:true}});const actor=await database.actor.findFirstOrThrow({where:{workspaceId,userId:member.userId,type:"HUMAN"}});return{sessionId:randomUUID(),workspaceId,workspaceSlug:"politizai",userId:member.userId,memberId:member.id,actorId:actor.id,roleId:member.roleId,roleKey:member.role.key,roleName:member.role.name,displayName:member.user.displayName}satisfies AuthenticatedContext;}

beforeAll(async()=>{workspaceId=(await seedDemoDatabase(database,{DATABASE_URL:connectionString,NODE_ENV:"test"})).workspaceId;[manager,viewer]=await Promise.all([context("gestor@demo.politizai.local"),context("viewer@demo.politizai.local")]);const actor=await database.actor.findFirstOrThrow({where:{workspaceId,key:"system"}});system={workspaceId,actorId:actor.id,actorType:"SYSTEM",actorKey:actor.key};sourceKey=(await database.leadSource.findFirstOrThrow({where:{workspaceId,deletedAt:null}})).key;const intake=createLeadIntakeService({database,authorization,now:()=>now});for(let index=0;index<7;index++){const result=await intake.intake({channel:"MANUAL",idempotencyKey:`crm42-lead-${index}-${randomUUID()}`,fullName:`Lead geográfico ${index}`,phone:`1198888${String(1000+index)}`,email:`geo-${index}-${randomUUID()}@example.test`,city:index<6?"São Paulo":undefined,stateCode:index<6?"SP":undefined,sourceKey,rawPayload:{fixture:"crm42",explicitLocation:index<6}},system);if(result.outcome==="REJECTED")throw new Error("Fixture CRM-42 rejeitada");leadIds.push(result.leadId);}});
afterAll(()=>database.$disconnect());

function service(){return createGeographicIntelligenceService({database,authorization,metrics:getMetricsService(),now:()=>now});}

describe("CRM-42 inteligência geográfica",()=>{
  it("aplica RBAC, dry-run, execução e rerun idempotente sem coordenadas inventadas",async()=>{await expect(service().runBackfill(viewer,{mode:"DRY_RUN",idempotencyKey:`denied-${randomUUID()}`})).rejects.toBeInstanceOf(AccessDeniedError);const dry=await service().runBackfill(manager,{mode:"DRY_RUN",idempotencyKey:"crm42-dry-run-fixture"});expect(dry).toMatchObject({mode:"DRY_RUN",createdCount:0,status:"SUCCEEDED"});expect(dry.validCount).toBeGreaterThanOrEqual(6);const execute=await service().runBackfill(manager,{mode:"EXECUTE",idempotencyKey:"crm42-execute-fixture"});expect(execute.createdCount).toBeGreaterThanOrEqual(6);expect(execute.membershipsCreated).toBeGreaterThanOrEqual(6);const replay=await service().runBackfill(manager,{mode:"EXECUTE",idempotencyKey:"crm42-execute-fixture"});expect(replay).toMatchObject({id:execute.id,idempotentReplay:true});const membershipCount=await database.territoryMembership.count({where:{workspaceId,targetType:"LEAD",targetId:{in:leadIds}}});const rerun=await service().runBackfill(manager,{mode:"EXECUTE",idempotencyKey:"crm42-execute-second-run"});expect(rerun).toMatchObject({createdCount:0,membershipsCreated:0,idempotentReplay:false});expect(rerun.existingCount).toBeGreaterThanOrEqual(6);expect(await database.territoryMembership.count({where:{workspaceId,targetType:"LEAD",targetId:{in:leadIds}}})).toBe(membershipCount);const locations=await database.geographicLocation.findMany({where:{workspaceId}});expect(locations.every(row=>row.latitude===null&&row.longitude===null)).toBe(true);expect(await database.geographicProfile.count({where:{workspaceId,targetType:"LEAD",targetId:{in:leadIds}}})).toBe(6);});

  it("preserva fato append-only e abre revisão para divergência sem overwrite",async()=>{const leadId=leadIds[0]!;const before=await database.geographicProfile.findUniqueOrThrow({where:{workspaceId_targetType_targetId:{workspaceId,targetType:"LEAD",targetId:leadId}}});const result=await service().recordObservation(manager,{targetType:"LEAD",targetId:leadId,location:{countryCode:"BR",stateCode:"RJ",city:"Rio de Janeiro",precision:"CITY",sourceType:"MANUAL_CONFIRMED",evidenceClass:"USER_CONFIRMED",confidenceBps:10000,verified:true},observedAt:now.toISOString(),idempotencyKey:"crm42-conflicting-observation",expectedRevision:before.revision,evidence:{source:"integration_fixture"}});expect(result.reviewRequired).toBe(true);const after=await database.geographicProfile.findUniqueOrThrow({where:{workspaceId_targetType_targetId:{workspaceId,targetType:"LEAD",targetId:leadId}}});expect(after.currentObservationId).toBe(before.currentObservationId);expect(await database.geographicDataIssue.count({where:{workspaceId,targetId:leadId,status:"OPEN"}})).toBe(1);const observation=await database.geographicObservation.findUniqueOrThrow({where:{id:result.observationId}});await expect(database.geographicObservation.update({where:{id:observation.id},data:{confidenceBps:1}})).rejects.toThrow(/append-only/);await expect(service().recordObservation(manager,{targetType:"LEAD",targetId:randomUUID(),location:{countryCode:"BR",stateCode:"SP",precision:"STATE",sourceType:"MANUAL_CONFIRMED",evidenceClass:"USER_CONFIRMED",confidenceBps:10000,verified:true},observedAt:now.toISOString(),idempotencyKey:`cross-${randomUUID()}`})).rejects.toMatchObject({code:"GEOGRAPHIC_TARGET_NOT_FOUND"});});

  it("transforma divergência do legado em revisão sem sobrescrever o perfil confirmado",async()=>{const intake=createLeadIntakeService({database,authorization,now:()=>now});const created=await intake.intake({channel:"MANUAL",idempotencyKey:`crm42-conflict-lead-${randomUUID()}`,fullName:"Lead com divergência geográfica",phone:"11977776666",email:`conflict-${randomUUID()}@example.test`,city:"São Paulo",stateCode:"SP",sourceKey,rawPayload:{fixture:"crm42-conflict"}},system);if(created.outcome==="REJECTED")throw new Error("Fixture de conflito rejeitada");await service().recordObservation(manager,{targetType:"LEAD",targetId:created.leadId,location:{countryCode:"BR",stateCode:"RJ",city:"Rio de Janeiro",precision:"CITY",sourceType:"MANUAL_CONFIRMED",evidenceClass:"USER_CONFIRMED",confidenceBps:10000,verified:true},observedAt:now.toISOString(),idempotencyKey:"crm42-confirmed-rj",evidence:{source:"integration_fixture"}});const before=await database.geographicProfile.findUniqueOrThrow({where:{workspaceId_targetType_targetId:{workspaceId,targetType:"LEAD",targetId:created.leadId}},include:{location:true}});const result=await service().runBackfill(manager,{mode:"EXECUTE",idempotencyKey:"crm42-conflict-backfill"});expect(result.conflictCount).toBeGreaterThanOrEqual(1);const after=await database.geographicProfile.findUniqueOrThrow({where:{workspaceId_targetType_targetId:{workspaceId,targetType:"LEAD",targetId:created.leadId}},include:{location:true}});expect(after.location.canonicalKey).toBe(before.location.canonicalKey);expect(after.location.stateCode).toBe("RJ");expect(await database.geographicDataIssue.count({where:{workspaceId,targetId:created.leadId,issueCode:"BACKFILL_LOCATION_CONFLICT",status:"OPEN"}})).toBe(1);});

  it("publica versão, detecta sobreposição ambígua e resolve território sem mudar owner",async()=>{const lead=await database.lead.findUniqueOrThrow({where:{id:leadIds[1]!}});const ownerBefore=lead.ownerMemberId;const published=await service().publishTerritory(manager,{code:"SP-PRIORITARIO",name:"São Paulo prioritário",type:"STATE",priority:900,countryCode:"BR",stateCode:"SP",effectiveFrom:"2046-01-01T00:00:00.000Z",reason:"Cobertura territorial do teste CRM-42"});expect(published.territory.version).toBe(1);const preview=await service().previewTerritory(manager,{code:"SP-EMPATE",name:"São Paulo empate",type:"STATE",priority:900,countryCode:"BR",stateCode:"SP",effectiveFrom:"2046-01-01T00:00:00.000Z",reason:"Validação de sobreposição CRM-42"});expect(preview.ambiguous).toBe(true);await expect(service().publishTerritory(manager,{code:"SP-EMPATE",name:"São Paulo empate",type:"STATE",priority:900,countryCode:"BR",stateCode:"SP",effectiveFrom:"2046-01-01T00:00:00.000Z",reason:"Validação de sobreposição CRM-42"})).rejects.toMatchObject({code:"TERRITORY_AMBIGUOUS"});const resolved=await service().resolveTerritory(manager,{targetType:"LEAD",targetId:lead.id,idempotencyKey:"crm42-resolve-sp"});expect(resolved.membership?.territoryId).toBe(published.territory.id);expect((await service().resolveTerritory(manager,{targetType:"LEAD",targetId:lead.id,idempotencyKey:"crm42-resolve-sp"})).idempotentReplay).toBe(true);expect((await database.lead.findUniqueOrThrow({where:{id:lead.id}})).ownerMemberId).toBe(ownerBefore);});

  it("reconcilia mapa e tabela, suprime grupos pequenos e expõe ausência sem zero falso",async()=>{const intake=createLeadIntakeService({database,authorization,now:()=>now});await intake.intake({channel:"MANUAL",idempotencyKey:`crm42-rr-${randomUUID()}`,fullName:"Lead de amostra protegida",phone:"95988887777",email:`rr-${randomUUID()}@example.test`,city:"Boa Vista",stateCode:"RR",sourceKey,rawPayload:{fixture:"crm42-small-group"}},system);await service().runBackfill(manager,{mode:"EXECUTE",idempotencyKey:"crm42-small-group-backfill"});const screen=await service().getScreen(manager,{from:"2046-05-01T00:00:00-03:00",to:"2046-06-01T00:00:00-03:00",metric:"LEADS",sourceIds:[],campaignIds:[],creativeIds:[]});const sp=screen.regions.find(row=>row.stateCode==="SP");expect(sp?.belowMinimum).toBe(false);expect(sp?.value).toBeGreaterThanOrEqual(6);expect(sp?.totals?.leads).toBeGreaterThanOrEqual(6);expect(sp?.drilldownUrl).toContain("/leads?state=SP");const rr=screen.regions.find(row=>row.stateCode==="RR");expect(rr).toMatchObject({belowMinimum:true,sampleSize:null,value:null,totals:null});const rrScreen=await service().getScreen(manager,{from:"2046-05-01T00:00:00-03:00",to:"2046-06-01T00:00:00-03:00",metric:"LEADS",stateCode:"RR",sourceIds:[],campaignIds:[],creativeIds:[]});expect(rrScreen.acquisition.sources.every(row=>row.count===null&&row.belowMinimum)).toBe(true);expect(screen.summary.withoutLocation).toBeGreaterThanOrEqual(1);expect(screen.minimumGroupSize).toBe(5);expect(screen.externalGeocoding).toBe("DEFERRED");expect(screen.unavailableMetrics).toEqual(["CPL","CAC","ROAS"]);await expect(service().getScreen({...manager,workspaceId:randomUUID()},{from:"2046-05-01T00:00:00-03:00",to:"2046-06-01T00:00:00-03:00",sourceIds:[],campaignIds:[],creativeIds:[]})).rejects.toBeInstanceOf(AccessDeniedError);});

  it("inativa território com RBAC e preserva o histórico",async()=>{const territory=await database.territory.findFirstOrThrow({where:{workspaceId,code:"SP-PRIORITARIO"},orderBy:{version:"desc"}});await expect(service().setTerritoryStatus(viewer,{territoryId:territory.id,status:"INACTIVE",reason:"Tentativa sem autorização no teste"})).rejects.toBeInstanceOf(AccessDeniedError);const result=await service().setTerritoryStatus(manager,{territoryId:territory.id,status:"INACTIVE",reason:"Encerramento controlado da regra no teste"});expect(result).toMatchObject({changed:true,territory:{status:"INACTIVE"}});expect(await database.territoryMembership.count({where:{workspaceId,territoryId:territory.id}})).toBeGreaterThan(0);expect(await database.auditLog.count({where:{workspaceId,entityId:territory.id,action:"geography.territory.inactivated"}})).toBe(1);});
});
