import { randomUUID } from "node:crypto";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { PrismaClient } from "@/generated/prisma/client";
import type { AuthenticatedContext } from "@/modules/auth/application/authenticated-context";
import { createMediaPerformanceService } from "@/modules/marketing/application/media-performance-service";
import { seedDemoDatabase } from "@/modules/settings/application/demo-seed-service";
import { AccessDeniedError } from "@/modules/users/permissions/authorization-errors";
import { createPostgresAdapter } from "@/shared/core/database/postgres-adapter";

const connectionString=process.env.DATABASE_URL;if(!connectionString)throw new Error("DATABASE_URL is required.");
const database=new PrismaClient({adapter:createPostgresAdapter(connectionString,{max:12})});const now=new Date("2046-04-21T15:00:00.000Z");let workspaceId:string;let manager:AuthenticatedContext;let viewer:AuthenticatedContext;
async function context(email:string){const member=await database.workspaceMember.findFirstOrThrow({where:{workspaceId,user:{normalizedEmail:email}},include:{role:true,user:true}});const actor=await database.actor.findFirstOrThrow({where:{workspaceId,userId:member.userId,type:"HUMAN"}});return{sessionId:randomUUID(),workspaceId,workspaceSlug:"politizai",userId:member.userId,memberId:member.id,actorId:actor.id,roleId:member.roleId,roleKey:member.role.key,roleName:member.role.name,displayName:member.user.displayName}satisfies AuthenticatedContext;}
beforeAll(async()=>{workspaceId=(await seedDemoDatabase(database,{DATABASE_URL:connectionString,NODE_ENV:"test"})).workspaceId;[manager,viewer]=await Promise.all([context("gestor@demo.politizai.local"),context("viewer@demo.politizai.local")]);});afterAll(()=>database.$disconnect());
const csv=(spend=10000)=>`date,channelKey,channelName,accountKey,accountName,campaignKey,campaignName,creativeKey,creativeName,currency,timeZone,spendCents,impressions,reach,clicks,linkClicks,landingPageViews,reportedLeads,reportedPurchases,reportedRevenueCents\n2046-04-20,meta,Meta Ads,politizai,Conta Politizai,campanha-local,Campanha local,criativo-a,Criativo A,BRL,America/Sao_Paulo,${spend},1000,800,100,80,70,10,2,50000`;
describe("CRM-39 mídia paga local",()=>{
 it("aplica RBAC granular e isolamento",async()=>{const service=createMediaPerformanceService({database,now:()=>now});await expect(service.getScreen(viewer)).resolves.toMatchObject({permissions:{canImport:false}});await expect(service.previewImport(viewer,{fileName:"x.csv",csv:csv(),idempotencyKey:`viewer-${randomUUID()}`})).rejects.toBeInstanceOf(AccessDeniedError);await expect(service.getScreen({...manager,workspaceId:randomUUID()})).rejects.toBeInstanceOf(AccessDeniedError);});
 it("faz preview, confirmação, replay, correção e rollback append-only",async()=>{const service=createMediaPerformanceService({database,now:()=>now});const preview=await service.previewImport(manager,{fileName:"midia.csv",csv:csv(),idempotencyKey:`preview-${randomUUID()}`});expect(preview).toMatchObject({validCount:1,rejectedCount:0});const key=`confirm-${randomUUID()}`;const confirmed=await service.confirmImport(manager,{previewRunId:preview.id,idempotencyKey:key});expect(confirmed.createdCount).toBe(1);expect((await service.confirmImport(manager,{previewRunId:preview.id,idempotencyKey:key})).idempotentReplay).toBe(true);const correctionPreview=await service.previewImport(manager,{fileName:"midia-correcao.csv",csv:csv(12000),idempotencyKey:`preview-${randomUUID()}`});const correction=await service.confirmImport(manager,{previewRunId:correctionPreview.id,idempotencyKey:`confirm-${randomUUID()}`});expect(correction.supersededCount).toBe(1);const facts=await database.marketingPerformanceFact.findMany({where:{workspaceId}});expect(facts).toHaveLength(2);await expect(database.marketingPerformanceFact.update({where:{id:facts[0]!.id},data:{spendCents:1n}})).rejects.toThrow(/append-only/);const rolled=await service.rollbackImport(manager,{importRunId:correction.id,reason:"Correção de teste",idempotencyKey:`rollback-${randomUUID()}`});expect(rolled.createdCount).toBe(1);const screen=await service.getScreen(manager,{periodStart:"2046-04-20T00:00:00-03:00",periodEnd:"2046-04-21T23:59:59-03:00"});expect(screen.totals.spendCents).toBe(10000);const staleRollback=await service.rollbackImport(manager,{importRunId:confirmed.id,reason:"Importação já superada",idempotencyKey:`rollback-${randomUUID()}`});expect(staleRollback.createdCount).toBe(0);expect((await database.marketingPerformanceFact.findMany({where:{workspaceId}}))).toHaveLength(3);});
 it("vincula legado só por ID e reconcilia sem alterar CRM",async()=>{const service=createMediaPerformanceService({database,now:()=>now});const dry=await service.backfillHierarchy(manager,{mode:"DRY_RUN",idempotencyKey:`dry-${randomUUID()}`});expect(dry.createdCount).toBe(0);const executed=await service.backfillHierarchy(manager,{mode:"EXECUTE",idempotencyKey:`exec-${randomUUID()}`});expect(executed.candidateCount).toBeGreaterThan(0);expect(await database.marketingCampaign.count({where:{workspaceId,legacyAcquisitionCampaignId:{not:null}}})).toBeGreaterThan(0);const reconciliation=await service.reconcile(manager,{periodStart:new Date("2046-04-20T00:00:00-03:00"),periodEnd:new Date("2046-04-22T00:00:00-03:00"),idempotencyKey:`reconcile-${randomUUID()}`});expect(reconciliation.status).toMatch(/COMPLETED|PARTIAL/);});
});
