import type { RevenueMetricDefinition } from "@/modules/metrics/domain/revenue-metrics-contracts";

const common = Object.freeze({
  version: 1,
  timeZoneRule: "Período civil no timezone congelado do workspace; persistência em timestamptz.",
  asOfRule: "Inclui apenas fatos com timestamp oficial anterior ou igual ao corte solicitado.",
  supportedFilters: ["SDR", "closer", "equipe", "origem", "campanha", "criativo", "prioridade", "produto"],
  cancellationRule: "Cancelados não contam; fatos encerrados permanecem no histórico quando a definição os exige.",
  reversalRule: "Correções append-only são aplicadas pelo movimento reversor; o fato original não é apagado.",
  duplicateRule: "IDs canônicos e chaves idempotentes contam o fato uma única vez.",
  comparisonRule: "Período anterior equivalente, com os mesmos filtros, escopo e timezone.",
  permission: "metrics.read" as const,
});

function definition(input: Omit<RevenueMetricDefinition, keyof typeof common | "version" | "permission" | "supportedDateBases"> & { supportedDateBases?: readonly string[] }): RevenueMetricDefinition {
  return Object.freeze({ ...common, ...input, supportedDateBases: input.supportedDateBases ?? [input.factTimestamp] });
}

export const REVENUE_METRICS_REGISTRY_VERSION = "crm57.2";

export const revenueMetricRegistry: readonly RevenueMetricDefinition[] = Object.freeze([
  definition({ id: "acquisition.spend", name: "Investimento em mídia", description: "Custo confirmado de mídia no período.", objective: "Controlar aquisição paga.", unit: "CENTS", sourceOfTruth: ["MarketingPerformanceFact"], numerator: "Soma de spendCents da revisão confirmada vigente", denominator: null, formula: "Σ investimento confirmado", factTimestamp: "periodStart/periodEnd", periodRule: "Fatos com interseção no período; sem rateio de fatos que cruzem limites.", cohortRule: null, supportedDimensions: ["canal", "campanha", "grupo", "anúncio", "criativo"], coverageRule: "Somente WORKSPACE; moeda BRL e revisão confirmada.", limitations: ["Importações parciais produzem estado PARTIAL.", "Fatos que cruzam limites não são rateados."], drilldownRule: "Uma linha por fato vigente de mídia.", desiredDirection: "CONTEXT" }),
  definition({ id: "acquisition.cpl", name: "CPL", description: "Investimento dividido por leads recebidos elegíveis.", objective: "Medir eficiência de aquisição.", unit: "CENTS", sourceOfTruth: ["MarketingPerformanceFact", "LeadFormSubmission"], numerator: "Investimento confirmado em centavos", denominator: "Leads recebidos", formula: "investimento / leads", factTimestamp: "MarketingPerformanceFact.periodStart e LeadFormSubmission.submittedAt", periodRule: "Mesmo intervalo semiaberto para custo e leads.", cohortRule: "Leads recebidos no período.", supportedDimensions: ["canal", "campanha", "criativo"], coverageRule: "Exige leitura WORKSPACE e custo confirmado; ausência de leads é NO_DENOMINATOR.", limitations: ["Não equivale a CAC."], drilldownRule: "Fatos de custo e leads que formam numerador e denominador.", desiredDirection: "DOWN" }),
  definition({ id: "acquisition.cac", name: "CAC de aquisição", description: "Investimento elegível por nova conta atribuída.", objective: "Medir custo de aquisição sem fingir custo comercial completo.", unit: "CENTS", sourceOfTruth: ["MarketingPerformanceFact", "AttributionRun", "AttributionCredit", "AttributionConversion"], numerator: "Investimento confirmado", denominator: "Contas distintas com WON e crédito atribuível", formula: "investimento / novas contas atribuídas", factTimestamp: "periodStart e AttributionConversion.occurredAt", periodRule: "Mesmo período e modelo de atribuição.", cohortRule: "Contas com primeira conversão WON atribuída no período.", supportedDimensions: ["canal", "campanha", "criativo"], coverageRule: "Cobertura do AttributionRun; ausência de conta é NO_DENOMINATOR.", limitations: ["Não inclui custo comercial; por isso o nome explicita aquisição."], drilldownRule: "Fatos de mídia, conversões e créditos.", desiredDirection: "DOWN" }),
  definition({ id: "acquisition.attributed_revenue", name: "Receita atribuída", description: "Crédito do modelo aplicado ao valor da conversão.", objective: "Relacionar aquisição e venda sem afirmar causalidade.", unit: "CENTS", sourceOfTruth: ["AttributionConversion", "AttributionCredit", "AttributionRun"], numerator: "Σ valueCents × creditBps / 10.000", denominator: null, formula: "receita vendida × crédito persistido", factTimestamp: "AttributionConversion.occurredAt", periodRule: "Conversões ativas no período e execução selecionada.", cohortRule: "Conversões WON elegíveis.", supportedDimensions: ["canal", "campanha", "criativo"], coverageRule: "Cobertura do run sempre visível; UNKNOWN não vira receita atribuída.", limitations: ["Atribuição é correlação conforme modelo, não causalidade."], drilldownRule: "Conversões, créditos e touchpoints do run.", desiredDirection: "CONTEXT" }),
  definition({ id: "acquisition.roas", name: "ROAS", description: "Receita atribuída sobre investimento confirmado.", objective: "Medir retorno atribuído da mídia.", unit: "BASIS_POINTS", sourceOfTruth: ["MarketingPerformanceFact", "AttributionCredit", "AttributionConversion"], numerator: "Receita atribuída", denominator: "Investimento confirmado", formula: "receita atribuída / investimento × 10.000", factTimestamp: "periodStart e conversion.occurredAt", periodRule: "Mesmo período, dimensão e modelo.", cohortRule: "Conversões WON atribuídas.", supportedDimensions: ["canal", "campanha", "criativo"], coverageRule: "NO_DENOMINATOR sem investimento; PARTIAL quando o run é parcial.", limitations: ["ROAS não prova incrementalidade."], drilldownRule: "Custos, conversões e créditos.", desiredDirection: "UP" }),
  definition({ id: "acquisition.attribution_coverage", name: "Cobertura de atribuição", description: "Conversões com crédito válido sobre conversões elegíveis.", objective: "Mostrar quanto da leitura de aquisição é confiável.", unit: "BASIS_POINTS", sourceOfTruth: ["AttributionRun"], numerator: "attributedCount", denominator: "conversionCount", formula: "conversões atribuídas / elegíveis", factTimestamp: "AttributionRun.finishedAt", periodRule: "Execução mais recente compatível com o período e asOf.", cohortRule: "Conversões da execução.", supportedDimensions: ["modelo"], coverageRule: "Usa coverageBps persistido.", limitations: ["Execução parcial permanece PARTIAL."], drilldownRule: "Créditos da execução, incluindo UNKNOWN.", desiredDirection: "UP" }),
  definition({ id: "sales.leads", name: "Leads recebidos", description: "Novas identidades recebidas no período.", objective: "Medir entrada do funil.", unit: "COUNT", sourceOfTruth: ["LeadFormSubmission"], numerator: "Submissões com intakeOutcome CREATED", denominator: null, formula: "contagem distinta de leads criados", factTimestamp: "submittedAt", periodRule: "Intervalo semiaberto [início, fim).", cohortRule: "Lead cuja primeira conversão criou a identidade.", supportedDimensions: ["origem", "campanha", "criativo", "prioridade"], coverageRule: "Cobertura completa no universo autorizado.", limitations: ["Conversões duplicadas não são novos leads."], drilldownRule: "Leads canônicos criados no período.", desiredDirection: "CONTEXT" }),
  definition({ id: "sales.win_rate", name: "Win rate", description: "Ganhos sobre oportunidades decididas.", objective: "Medir conversão comercial.", unit: "BASIS_POINTS", sourceOfTruth: ["OpportunityOutcomeSnapshot"], numerator: "Oportunidades ganhas", denominator: "Oportunidades ganhas + perdidas", formula: "ganhas / decididas × 10.000", factTimestamp: "occurredAt", periodRule: "Decisões no intervalo semiaberto.", cohortRule: "Oportunidades decididas no período.", supportedDimensions: ["closer", "equipe", "produto"], coverageRule: "NO_DENOMINATOR quando não há decisão.", limitations: ["Não mede coorte por criação da oportunidade."], drilldownRule: "Snapshots imutáveis de ganho e perda.", desiredDirection: "UP" }),
  definition({ id: "sales.opportunity_value", name: "Valor de oportunidades", description: "Valor das oportunidades pela data-base selecionada.", objective: "Comparar coorte criada e resultado ganho sem misturar seus timestamps.", unit: "CENTS", sourceOfTruth: ["Opportunity", "OpportunityOutcomeSnapshot"], numerator: "Σ Opportunity.amountCents no universo da data-base", denominator: null, formula: "Σ valor das oportunidades distintas", factTimestamp: "CREATED_AT ou WON_AT", supportedDateBases: ["CREATED_AT", "WON_AT"], periodRule: "CREATED_AT usa Opportunity.createdAt; WON_AT usa OpportunityOutcomeSnapshot.occurredAt com status WON.", cohortRule: "Oportunidades distintas na data-base selecionada.", supportedDimensions: ["oferta", "ICP", "estágio", "owner", "equipe", "produto"], coverageRule: "WON_AT exige snapshot canônico de ganho; oportunidade sem valor contribui zero explícito.", limitations: ["Mudar a data-base muda a coorte e deve ser exibido na leitura."], drilldownRule: "Oportunidades e snapshot de ganho que compõem o valor.", desiredDirection: "CONTEXT" }),
  definition({ id: "sales.bookings", name: "Bookings", description: "Valor total dos contratos aceitos no período.", objective: "Separar venda contratada de caixa recebido.", unit: "CENTS", sourceOfTruth: ["CommercialContract", "ContractVersion"], numerator: "Soma de ContractVersion.totalCents aceita", denominator: null, formula: "Σ valor total contratado", factTimestamp: "acceptedAt", periodRule: "Contratos aceitos no intervalo.", cohortRule: "Contratos aceitos.", supportedDimensions: ["closer", "equipe", "produto"], coverageRule: "Somente versão corrente aceita e BRL.", limitations: ["Bookings não é receita contábil nem pagamento."], drilldownRule: "Contratos aceitos e sua versão oficial.", desiredDirection: "UP" }),
  definition({ id: "sales.tcv", name: "TCV contratado", description: "TCV das versões de contrato aceitas.", objective: "Medir valor total contratado.", unit: "CENTS", sourceOfTruth: ["ContractVersion"], numerator: "Soma de tcvCents", denominator: null, formula: "Σ TCV contratado", factTimestamp: "CommercialContract.acceptedAt", periodRule: "Aceites no período.", cohortRule: "Contratos aceitos.", supportedDimensions: ["closer", "equipe", "produto"], coverageRule: "Versão corrente aceita.", limitations: ["Não equivale a caixa ou MRR."], drilldownRule: "Versões aceitas por contrato.", desiredDirection: "UP" }),
  definition({ id: "sales.contracted_mrr", name: "MRR contratado", description: "MRR de novos contratos aceitos.", objective: "Separar contratação de ativação.", unit: "CENTS", sourceOfTruth: ["ContractVersion"], numerator: "Soma de mrrCents", denominator: null, formula: "Σ MRR das versões aceitas", factTimestamp: "CommercialContract.acceptedAt", periodRule: "Aceites no período.", cohortRule: "Contratos aceitos.", supportedDimensions: ["closer", "equipe", "produto"], coverageRule: "Versão corrente aceita.", limitations: ["Pode diferir do MRR ativo por ativação/cancelamento."], drilldownRule: "Contratos aceitos.", desiredDirection: "UP" }),
  definition({ id: "revenue.opening_mrr", name: "MRR inicial", description: "Saldo do ledger antes do início do período.", objective: "Abrir a ponte de MRR.", unit: "CENTS", sourceOfTruth: ["RevenueMovement"], numerator: "Soma de deltaMrrCents antes do período", denominator: null, formula: "Σ movimentos efetivos antes do início", factTimestamp: "effectiveAt", periodRule: "Corte imediatamente anterior ao início.", cohortRule: "Assinaturas com saldo positivo no início.", supportedDimensions: ["owner", "equipe", "conta"], coverageRule: "Ledger append-only em BRL.", limitations: [], drilldownRule: "Movimentos que compõem o saldo inicial.", desiredDirection: "CONTEXT" }),
  definition({ id: "revenue.closing_mrr", name: "MRR ativo final", description: "Saldo do ledger no corte final.", objective: "Medir recorrência ativa reproduzível.", unit: "CENTS", sourceOfTruth: ["RevenueMovement"], numerator: "Soma de todos os deltaMrrCents até o corte", denominator: null, formula: "Σ movimentos efetivos até asOf", factTimestamp: "effectiveAt", periodRule: "Até min(fim do período, asOf).", cohortRule: "Todas as assinaturas elegíveis.", supportedDimensions: ["owner", "equipe", "conta"], coverageRule: "Ledger append-only em BRL.", limitations: [], drilldownRule: "Movimentos que compõem o saldo final.", desiredDirection: "UP" }),
  definition({ id: "revenue.arr", name: "ARR", description: "MRR ativo final anualizado.", objective: "Exibir run rate anual de recorrência.", unit: "CENTS", sourceOfTruth: ["RevenueMovement"], numerator: "MRR ativo final × 12", denominator: null, formula: "closing MRR × 12", factTimestamp: "effectiveAt", periodRule: "Mesmo corte do MRR final.", cohortRule: null, supportedDimensions: ["owner", "equipe", "conta"], coverageRule: "Disponível quando MRR final é reproduzível.", limitations: ["Não é receita reconhecida."], drilldownRule: "Mesmo drilldown do MRR final.", desiredDirection: "UP" }),
  ...([[
    "revenue.new_mrr", "New MRR", "NEW", "Nova recorrência ativada", "UP",
  ], ["revenue.expansion_mrr", "Expansion MRR", "EXPANSION", "Expansão efetiva", "UP"], ["revenue.reactivation_mrr", "Reactivation MRR", "REACTIVATION", "Recorrência reativada", "UP"], ["revenue.contraction_mrr", "Contraction MRR", "CONTRACTION", "Redução efetiva", "DOWN"], ["revenue.churned_mrr", "Churned MRR", "CHURN", "Recorrência encerrada", "DOWN"]] as const).map(([id, name, type, description, desiredDirection]) => definition({ id, name, description, objective: "Explicar a movimentação do MRR.", unit: "CENTS", sourceOfTruth: ["RevenueMovement"], numerator: `Soma ${type} no período`, denominator: null, formula: `Σ |deltaMrrCents| de ${type}`, factTimestamp: "effectiveAt", periodRule: "Movimentos efetivos no intervalo e até asOf.", cohortRule: null, supportedDimensions: ["owner", "equipe", "conta"], coverageRule: "Ledger append-only em BRL.", limitations: [], drilldownRule: `Movimentos ${type} do período.`, desiredDirection })),
  definition({ id: "revenue.net_new_mrr", name: "Net New MRR", description: "Variação líquida do MRR no período.", objective: "Reconciliar crescimento recorrente.", unit: "CENTS", sourceOfTruth: ["RevenueMovement"], numerator: "New + Expansion + Reactivation − Contraction − Churn + ajustes", denominator: null, formula: "MRR final − MRR inicial", factTimestamp: "effectiveAt", periodRule: "Movimentos efetivos no intervalo.", cohortRule: null, supportedDimensions: ["owner", "equipe", "conta"], coverageRule: "A ponte deve fechar exatamente.", limitations: ["Reversões e renewals sem delta aparecem como ajustes."], drilldownRule: "Todos os movimentos do período.", desiredDirection: "UP" }),
  definition({ id: "retention.grr", name: "GRR", description: "Retenção bruta da coorte inicial, sem expansão.", objective: "Medir preservação da base recorrente.", unit: "BASIS_POINTS", sourceOfTruth: ["RevenueMovement"], numerator: "MRR inicial − contraction − churn", denominator: "MRR inicial da coorte", formula: "max(0, inicial − reduções) / inicial", factTimestamp: "effectiveAt", periodRule: "Coorte ativa no início e movimentos até o corte.", cohortRule: "Assinaturas com MRR positivo no início.", supportedDimensions: ["owner", "equipe", "coorte de ativação"], coverageRule: "NO_DENOMINATOR sem MRR inicial.", limitations: ["Expansão é excluída por definição."], drilldownRule: "Assinaturas e movimentos da coorte inicial.", desiredDirection: "UP" }),
  definition({ id: "retention.nrr", name: "NRR", description: "Retenção líquida da coorte inicial.", objective: "Medir preservação e expansão da base.", unit: "BASIS_POINTS", sourceOfTruth: ["RevenueMovement"], numerator: "MRR final da coorte inicial", denominator: "MRR inicial da coorte", formula: "MRR final da coorte / MRR inicial", factTimestamp: "effectiveAt", periodRule: "Coorte ativa no início e movimentos até o corte.", cohortRule: "Assinaturas com MRR positivo no início; New MRR de novas logos é excluído.", supportedDimensions: ["owner", "equipe", "coorte de ativação"], coverageRule: "NO_DENOMINATOR sem MRR inicial.", limitations: [], drilldownRule: "Assinaturas e movimentos da coorte inicial.", desiredDirection: "UP" }),
  definition({ id: "retention.logo_churn", name: "Logo churn", description: "Contas da coorte inicial encerradas.", objective: "Medir perda de clientes ativos.", unit: "BASIS_POINTS", sourceOfTruth: ["RevenueMovement", "ChurnEvent"], numerator: "Contas iniciais com saldo final zero e churn confirmado", denominator: "Contas com MRR positivo no início", formula: "logos churn / logos iniciais", factTimestamp: "ChurnEvent.effectiveAt", periodRule: "Churn confirmado no período.", cohortRule: "Contas ativas no início.", supportedDimensions: ["owner", "equipe", "coorte"], coverageRule: "Não inferir churn apenas por inatividade.", limitations: [], drilldownRule: "Eventos confirmados de churn da coorte.", desiredDirection: "DOWN" }),
  definition({ id: "retention.renewal_rate", name: "Taxa de renovação", description: "Renovações concluídas sobre decisões finais.", objective: "Medir preservação contratual.", unit: "BASIS_POINTS", sourceOfTruth: ["RenewalEvent"], numerator: "RENEWED", denominator: "RENEWED + NOT_RENEWED + CANCELLED", formula: "renovadas / decididas", factTimestamp: "occurredAt", periodRule: "Última decisão final no período.", cohortRule: "Renovações decididas.", supportedDimensions: ["owner", "equipe", "conta"], coverageRule: "Pendentes não entram no denominador.", limitations: [], drilldownRule: "Eventos finais de renovação.", desiredDirection: "UP" }),
  definition({ id: "cash.received", name: "Receita recebida", description: "Recebimentos de cobranças e entradas avulsas liquidadas, líquidos de reversões no período.", objective: "Medir caixa confirmado no CRM.", unit: "CENTS", sourceOfTruth: ["Payment", "FinancialEntry"], numerator: "Confirmados + entradas avulsas liquidadas − reversões/chargebacks", denominator: null, formula: "Σ pagamento líquido", factTimestamp: "occurredAt/reversedAt", periodRule: "Eventos de caixa no intervalo.", cohortRule: null, supportedDimensions: ["owner", "equipe", "conta"], coverageRule: "Simulações excluídas. Entradas avulsas somente na visão WORKSPACE sem filtros e com permissão Financeiro.", limitations: ["Recebimentos manuais dependem da confirmação do operador; não representam conciliação bancária automática."], drilldownRule: "Pagamentos e reversões.", desiredDirection: "UP" }),
  definition({ id: "cash.delinquency", name: "Inadimplência operacional", description: "Saldo vencido não pago sobre total vencido.", objective: "Dar visibilidade ao risco de cobrança.", unit: "BASIS_POINTS", sourceOfTruth: ["Invoice", "PaymentEvent"], numerator: "Total vencido − pagamentos confirmados até asOf", denominator: "Total vencido elegível", formula: "saldo vencido / valor vencido", factTimestamp: "dueAt e Payment.occurredAt", periodRule: "Faturas emitidas e vencidas até asOf.", cohortRule: "Faturas vencidas não canceladas/voided.", supportedDimensions: ["owner", "equipe", "conta"], coverageRule: "PARTIAL para cortes históricos anteriores sem projeção imutável de status.", limitations: ["Métrica operacional, não contábil."], drilldownRule: "Faturas vencidas e pagamentos associados.", desiredDirection: "DOWN" }),
  ...([[
    "cadence.decision_maker_coverage", "Cobertura de decisor", "OpportunityEvidence/ECONOMIC_BUYER ou stakeholder decisor ativo",
  ], ["cadence.sponsor_coverage", "Cobertura de patrocinador", "OpportunityEvidence/SPONSOR ativo"], ["cadence.diagnosis_coverage", "Cobertura de diagnóstico", "OpportunityEvidence/DIAGNOSIS ativo"], ["cadence.pilot_coverage", "Cobertura de piloto", "OpportunityEvidence/PILOT_CRITERIA ou episódio PILOT concluído"], ["cadence.planned_wait_coverage", "Cobertura de espera pactuada", "OpportunityPlannedWait/PLANNED"], ["cadence.commitment_coverage", "Cobertura de compromisso", "Episódio ou trilha ativa/concluída"], ["cadence.stage_coverage", "Cobertura de estágio", "PipelineStage atual persistido"]] as const).map(([id, name, numerator]) => definition({ id, name, description: `${name} nas oportunidades autorizadas.`, objective: "Medir evidência da cadência longa sem inferir fatos ausentes.", unit: "BASIS_POINTS", sourceOfTruth: ["Opportunity", "OpportunityEvidence", "OpportunityAccountPlan"], numerator, denominator: "Oportunidades autorizadas no corte", formula: "oportunidades cobertas / oportunidades elegíveis × 10.000", factTimestamp: "createdAt/confirmedAt/updatedAt até asOf", periodRule: "Snapshot operacional no corte solicitado.", cohortRule: "Oportunidades agrupáveis por oferta e segmento:porte da conta.", supportedDimensions: ["owner", "equipe", "produto", "oferta", "ICP", "estágio"], coverageRule: "Sem oportunidades resulta NO_DENOMINATOR; ausência de evidência é descoberta, não zero inventado.", limitations: ["Estado histórico anterior não é reconstruído quando a fonte não possui versão temporal."], drilldownRule: "Oportunidades e fatos canônicos que compõem numerador e denominador.", desiredDirection: "UP" })),
  definition({ id: "delivery.service_project_delivered", name: "Serviço/projeto entregue", description: "Valor de linhas de implementação, projeto ou serviço com onboarding concluído.", objective: "Separar entrega operacional de contratação e recebimento.", unit: "CENTS", sourceOfTruth: ["ContractLineSnapshot", "OnboardingCase"], numerator: "Linhas elegíveis do contrato concluído", denominator: null, formula: "Σ totalCents das linhas de serviço com onboarding COMPLETED", factTimestamp: "OnboardingCase.completedAt", periodRule: "Conclusões no intervalo e até asOf.", cohortRule: "Contratos aceitos com linha de implementação, projeto ou serviço.", supportedDimensions: ["owner", "equipe", "produto", "oferta", "ICP"], coverageRule: "Somente conclusão persistida; ausência de onboarding não vira entrega.", limitations: ["Não equivale a reconhecimento contábil."], drilldownRule: "Contratos, linhas e caso de onboarding concluído.", desiredDirection: "UP" }),
  ...([[
    "cost.media", "Custo de mídia", "MarketingPerformanceFact.spendCents", "MarketingPerformanceFact.periodStart",
  ], ["cost.outbound", "Custo de outbound", "OutboundCampaignRecipient.costCents", "OutboundCampaignRecipient.createdAt"], ["cost.ai", "Custo de IA", "AIExecutionTrace.estimatedCostCents", "AIExecutionTrace.createdAt"]] as const).map(([id, name, numerator, factTimestamp]) => definition({ id, name, description: `${name} persistido no período.`, objective: "Expor consumo operacional por fonte.", unit: "CENTS", sourceOfTruth: [numerator.split(".")[0]!], numerator: `Σ ${numerator}`, denominator: null, formula: `Σ ${numerator}`, factTimestamp, periodRule: "Fatos no intervalo e até asOf.", cohortRule: null, supportedDimensions: ["fonte", "campanha", "owner", "equipe"], coverageRule: "A cobertura da fonte é publicada separadamente; custo ausente não é estimado.", limitations: ["Custo estimado de IA permanece identificado como estimativa."], drilldownRule: `Fatos de ${name.toLowerCase()} do período.`, desiredDirection: "DOWN" })),
  ...([[
    "quality.cadence_complete", "Qualidade da amostra de cadência", "Oportunidades com decisor, patrocinador, diagnóstico, piloto, compromisso e estágio",
  ], ["quality.media_cost", "Cobertura de custo de mídia", "Fatos de mídia com spendCents disponível"], ["quality.outbound_cost", "Cobertura de custo outbound", "Destinatários outbound com costCents persistido"], ["quality.ai_cost", "Cobertura de custo de IA", "Execuções de IA com estimatedCostCents"]] as const).map(([id, name, numerator]) => definition({ id, name, description: `${name} no recorte.`, objective: "Evidenciar a qualidade dos denominadores usados.", unit: "BASIS_POINTS", sourceOfTruth: ["OpportunityEvidence", "MarketingPerformanceFact", "OutboundCampaignRecipient", "AIExecutionTrace"], numerator, denominator: "Amostras da fonte no recorte", formula: "amostras completas / amostras observadas × 10.000", factTimestamp: "Timestamp oficial de cada fonte", periodRule: "Mesmo intervalo e asOf da métrica associada.", cohortRule: null, supportedDimensions: ["fonte", "owner", "equipe", "oferta", "ICP"], coverageRule: "Sem amostra resulta NO_DENOMINATOR.", limitations: [], drilldownRule: "Amostras completas e incompletas com motivo.", desiredDirection: "UP" })),
  ...([[
    "forecast.pipeline", "Forecast pipeline", "pipelineCents",
  ], ["forecast.best_case", "Forecast best case", "bestCaseCents"], ["forecast.commit", "Forecast commit", "commitCents"], ["forecast.weighted", "Pipeline ponderado", "weightedPipelineCents"]] as const).map(([id, name, field]) => definition({ id, name, description: `Valor ${name.toLowerCase()} do snapshot imutável.`, objective: "Preservar a leitura humana do forecast no corte.", unit: "CENTS", sourceOfTruth: ["ForecastSnapshot", "ForecastSnapshotItem"], numerator: `ForecastSnapshot.${field}`, denominator: null, formula: `valor persistido em ${field}`, factTimestamp: "ForecastSnapshot.asOf", periodRule: "Último snapshot compatível anterior ou igual a asOf.", cohortRule: "Oportunidades elegíveis do snapshot.", supportedDimensions: ["equipe", "função", "owner"], coverageRule: "Usa coverageState/coverageBps do snapshot; weighted é ausente sem cobertura manual completa.", limitations: ["Não é modelo preditivo."], drilldownRule: "Itens imutáveis do snapshot.", desiredDirection: "CONTEXT" })),
  definition({ id: "forecast.gap", name: "Gap para meta", description: "Meta menos forecast commit.", objective: "Mostrar distância até a quota.", unit: "CENTS", sourceOfTruth: ["ForecastSnapshot", "GoalQuota"], numerator: "goalTargetCents − commitCents", denominator: null, formula: "meta − commit", factTimestamp: "ForecastSnapshot.asOf", periodRule: "Snapshot do ciclo e versão de meta vinculada.", cohortRule: null, supportedDimensions: ["equipe", "função"], coverageRule: "UNAVAILABLE sem meta vinculada.", limitations: ["Gap negativo significa forecast acima da meta, não receita realizada."], drilldownRule: "Itens do forecast e quota vinculada.", desiredDirection: "DOWN" }),
  definition({ id: "goals.attainment", name: "Atingimento da meta", description: "Realizado sobre meta publicada no snapshot.", objective: "Medir progresso contra a versão congelada da meta.", unit: "BASIS_POINTS", sourceOfTruth: ["ForecastSnapshot", "GoalPlan", "GoalQuota"], numerator: "realizedCents", denominator: "goalTargetCents", formula: "realizado / meta × 10.000", factTimestamp: "ForecastSnapshot.asOf", periodRule: "Mesmo ciclo e corte do snapshot.", cohortRule: null, supportedDimensions: ["equipe", "função"], coverageRule: "UNAVAILABLE sem meta; NO_DENOMINATOR com meta zero.", limitations: ["Não projeta o fechamento."], drilldownRule: "Oportunidades realizadas e quota vinculada.", desiredDirection: "UP" }),
  definition({ id: "forecast.pipeline_coverage", name: "Cobertura de pipeline", description: "Pipeline elegível sobre meta restante.", objective: "Dimensionar cobertura necessária para o gap.", unit: "BASIS_POINTS", sourceOfTruth: ["ForecastSnapshot"], numerator: "pipelineCents", denominator: "max(meta − realizado, 0)", formula: "pipeline / meta restante × 10.000", factTimestamp: "ForecastSnapshot.asOf", periodRule: "Mesmo ciclo e corte.", cohortRule: "Oportunidades elegíveis do snapshot.", supportedDimensions: ["equipe", "função"], coverageRule: "UNAVAILABLE sem meta; NO_DENOMINATOR quando não existe meta restante.", limitations: ["Cobertura não é probabilidade de atingir meta."], drilldownRule: "Itens elegíveis e quota vinculada.", desiredDirection: "CONTEXT" }),
  definition({ id: "forecast.accuracy", name: "Acurácia do forecast", description: "Proximidade entre commit do corte e realizado final.", objective: "Avaliar disciplina do forecast fechado.", unit: "BASIS_POINTS", sourceOfTruth: ["ForecastSnapshot", "ForecastCycle"], numerator: "1 − erro absoluto normalizado", denominator: "max(realizado final, 1 centavo)", formula: "max(0, 1 − |commit − realizado| / max(realizado, 1))", factTimestamp: "Snapshot.asOf e ciclo fechado", periodRule: "Somente ciclo CLOSED; snapshot e realizado final imutáveis.", cohortRule: "Ciclo de forecast fechado.", supportedDimensions: ["equipe", "função"], coverageRule: "UNAVAILABLE em ciclo aberto ou sem snapshot final.", limitations: ["Realizado zero e commit zero resulta 100%; realizado zero com commit positivo resulta 0%."], drilldownRule: "Itens do snapshot fechado e vendas realizadas.", desiredDirection: "UP" }),
]);

export const revenueMetricRegistryById = new Map(revenueMetricRegistry.map((metric) => [metric.id, metric]));

export function getRevenueMetricDefinition(id: string): RevenueMetricDefinition | null {
  return revenueMetricRegistryById.get(id) ?? null;
}
