"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import type { GlobalSearchResponse } from "@/modules/workspace-experience/domain/workspace-experience-contracts";

export function GlobalSearch() {
  const [open, setOpen] = useState(false); const [query, setQuery] = useState(""); const [result, setResult] = useState<GlobalSearchResponse | null>(null); const [state, setState] = useState<"IDLE" | "LOADING" | "ERROR">("IDLE"); const input = useRef<HTMLInputElement>(null); const trigger = useRef<HTMLButtonElement>(null); const dialog = useRef<HTMLDivElement>(null);
  useEffect(() => { const handler = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") { event.preventDefault(); setState("IDLE"); setOpen(true); } if (event.key === "Escape" && open) { setOpen(false); trigger.current?.focus(); } if (event.key === "Tab" && open && dialog.current) { const focusable = [...dialog.current.querySelectorAll<HTMLElement>("a[href], button:not([disabled]), input:not([disabled])")]; const first = focusable[0]; const last = focusable.at(-1); if (event.shiftKey && document.activeElement === first && last) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last && first) { event.preventDefault(); first.focus(); } } }; document.addEventListener("keydown", handler); return () => document.removeEventListener("keydown", handler); }, [open]);
  useEffect(() => { if (open) requestAnimationFrame(() => input.current?.focus()); }, [open]);
  useEffect(() => { if (!open || query.trim().length < 2) return; const controller = new AbortController(); const timer = window.setTimeout(() => { void fetch(`/api/search?q=${encodeURIComponent(query.trim())}`, { cache: "no-store", signal: controller.signal }).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "Falha na busca."); setResult(body.result); setState("IDLE"); }).catch((error) => { if (error instanceof DOMException && error.name === "AbortError") return; setState("ERROR"); }); }, 250); return () => { window.clearTimeout(timer); controller.abort(); }; }, [open, query]);
  return <><button aria-expanded={open} aria-haspopup="dialog" className="global-search-trigger" onClick={() => { setState(query.trim().length >= 2 ? "LOADING" : "IDLE"); setOpen(true); }} ref={trigger} type="button"><span>Buscar</span><kbd>⌘ K</kbd></button>{open ? <div aria-label="Busca global" aria-modal="true" className="global-search" ref={dialog} role="dialog" onMouseDown={(event) => { if (event.target === event.currentTarget) { setOpen(false); trigger.current?.focus(); } }}><section><header><input aria-label="Buscar contas, contatos, leads e oportunidades" onChange={(event) => { const value = event.target.value; setQuery(value); if (value.trim().length < 2) { setResult(null); setState("IDLE"); } else { setState("LOADING"); } }} placeholder="Buscar no workspace…" ref={input} value={query} /><button aria-label="Fechar busca" onClick={() => { setOpen(false); trigger.current?.focus(); }} type="button">Esc</button></header><div aria-live="polite" className="global-search__results">{query.trim().length < 2 ? <p>Digite pelo menos 2 caracteres. Resultados respeitam seu escopo.</p> : state === "LOADING" ? <p>Buscando com segurança…</p> : state === "ERROR" ? <p role="alert">Não foi possível buscar agora.</p> : result && result.groups.length === 0 ? <p>Nenhum resultado autorizado.</p> : result?.groups.map((group) => <section key={group.type}><h2>{group.label}</h2>{group.items.map((item) => <Link href={item.href} key={`${item.type}:${item.id}`} onClick={() => setOpen(false)}><span><strong>{item.title}</strong><small>{item.context}</small></span>{item.hint ? <em>{item.hint}</em> : null}</Link>)}</section>)}</div></section></div> : null}</>;
}
