"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/ui/empty-state";
import { SectionHeader, StatCard, Surface } from "@/components/ui/surface";

type Initial = Readonly<{ label: string; externalEgress: false; databaseAccess: false; generatedAt: string; permissions: { canManage: boolean; canReview: boolean }; eligibleOwners: readonly { id: string; name: string }[]; summary: { machines: number; activeMachines: number; activeRecipes: number; pendingProposals: number; lastSuccessAt: string | null; lastFailureAt: string | null; eventsByStatus: Record<string, number> }; machines: readonly { id: string; name: string; purpose: string; status: string; tokenFingerprint: string; tokenVersion: number; revision: number; expiresAt: string; lastUsedAt: string | null; owner: { name: string }; scopes: readonly string[] }[]; recipes: readonly { id: string; key: string; name: string; purpose: string; status: string; revision: number; currentVersion: number; owner: string; trigger: string | null; action: string | null; requiresConfirmation: boolean }[]; proposals: readonly { id: string; kind: string; targetType: string; targetId: string; reason: string; status: string; createdAt: string; expiresAt: string; correlationId: string }[]; recentCommands: readonly { id: string; commandType: string; status: string; responseCode: string; correlationId: string; receivedAt: string }[]; catalog: readonly { key: string; name: string; trigger: string; action: string; confirmation: boolean }[] }>;
const fmt = (value: string | null) => value ? new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short", timeZone: "America/Sao_Paulo" }).format(new Date(value)) : "Sem execução";

export function N8nWorkspace({ initial }: Readonly<{ initial: Initial }>) {
  const router = useRouter(); const [pending, setPending] = useState(false); const [feedback, setFeedback] = useState<string | null>(null); const [credential, setCredential] = useState<string | null>(null); const owner = initial.eligibleOwners[0];
  async function post(action: string, data: unknown) { setPending(true); setFeedback(null); const response = await fetch("/api/integrations/n8n", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, data }) }); const body = await response.json(); setPending(false); if (!response.ok) { setFeedback(body.error?.message ?? "Não foi possível concluir a operação."); return null; } setFeedback("Operação local concluída e auditada."); router.refresh(); return body.result; }
  async function createMachine() { if (!owner) return; const expiresAt = new Date(Date.now() + 30 * 86_400_000).toISOString(); const result = await post("CREATE_MACHINE", { key: `n8n-local-${Date.now()}`, name: "n8n local", purpose: "Simular workflows governados sem egress externo.", ownerMemberId: owner.id, scopes: ["EVENTS_READ", "RECORDS_READ", "ACTIVITY_DRAFT_CREATE", "NEXT_ACTION_DRAFT_CREATE", "AUTOMATION_RESULT_WRITE", "ACTION_PROPOSAL_CREATE"], expiresAt }); if (result?.credential) setCredential(result.credential); }
  return <div className="space-y-5">
    <Surface tone="accent"><div className="flex flex-wrap items-start justify-between gap-4"><SectionHeader title={initial.label} description="Não há n8n instalado, URL pública, credencial real, egress ou acesso ao banco. Toda escrita vira resultado técnico ou proposta para decisão humana." />{initial.permissions.canManage && owner ? <Button disabled={pending} onClick={createMachine}>{pending ? "Criando…" : "Criar identidade local"}</Button> : null}</div></Surface>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Identidades ativas" value={initial.summary.activeMachines} hint={`${initial.summary.machines} cadastradas`} /><StatCard label="Receitas ativas" value={initial.summary.activeRecipes} hint={`${initial.catalog.length} modelos allowlisted`} /><StatCard label="Revisões pendentes" value={initial.summary.pendingProposals} hint="Confirmação humana no CRM" /><StatCard label="Último sucesso" value={fmt(initial.summary.lastSuccessAt)} hint="Dados persistidos" /></div>
    {feedback ? <p className="feedback-banner" role="status">{feedback}</p> : null}
    {credential ? <Surface tone="critical"><SectionHeader title="Credencial exibida uma única vez" description="Use-a somente no sandbox local. Ao sair desta tela, faça rotação para obter outra." /><code className="mt-3 block overflow-x-auto rounded-[var(--radius-control)] bg-[var(--color-surface-strong)] p-3 text-sm">{credential}</code></Surface> : null}
    <div className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]">
      <Surface><SectionHeader title="Identidades de máquina" description="Escopos explícitos, proprietário humano, expiração e kill switch por identidade." />{initial.machines.length === 0 ? <div className="mt-4"><EmptyState title="Nenhuma identidade criada" description="Um administrador pode criar a primeira credencial efêmera local." /></div> : <div className="mt-4 space-y-3">{initial.machines.map((machine) => <article key={machine.id} className="rounded-[var(--radius-panel)] bg-muted/45 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">{machine.name}</h3><p className="text-sm text-muted-foreground">{machine.purpose}</p></div><span className="status-badge" data-tone={machine.status === "ACTIVE" ? "success" : machine.status === "REVOKED" ? "danger" : "default"}>{machine.status}</span></div><dl className="mt-3 grid gap-2 text-sm sm:grid-cols-2"><div><dt className="text-muted-foreground">Responsável</dt><dd>{machine.owner.name}</dd></div><div><dt className="text-muted-foreground">Fingerprint</dt><dd className="font-mono">{machine.tokenFingerprint}</dd></div><div><dt className="text-muted-foreground">Expira</dt><dd>{fmt(machine.expiresAt)}</dd></div><div><dt className="text-muted-foreground">Último uso</dt><dd>{fmt(machine.lastUsedAt)}</dd></div></dl><details className="mt-3"><summary className="cursor-pointer text-sm font-semibold">Escopos e controles</summary><p className="mt-2 text-sm text-muted-foreground">{machine.scopes.join(" · ")}</p>{initial.permissions.canManage && machine.status !== "REVOKED" ? <div className="mt-3 flex gap-2"><Button variant="secondary" disabled={pending} onClick={() => post("SET_MACHINE_STATUS", { machineId: machine.id, revision: machine.revision, status: machine.status === "ACTIVE" ? "PAUSED" : "ACTIVE", reason: "Alteração explícita pelo painel local." })}>{machine.status === "ACTIVE" ? "Pausar" : "Ativar"}</Button><Button variant="destructive" disabled={pending} onClick={() => post("SET_MACHINE_STATUS", { machineId: machine.id, revision: machine.revision, status: "REVOKED", reason: "Revogação explícita pelo administrador." })}>Revogar</Button></div> : null}</details></article>)}</div>}</Surface>
      <Surface><SectionHeader title="Propostas aguardando decisão" description="Aprovar registra a decisão; a ação continua passando pelo serviço normal do CRM." />{initial.proposals.length === 0 ? <div className="mt-4"><EmptyState title="Nenhuma proposta pendente" description="A automação local ainda não sugeriu ação consequencial." /></div> : <div className="mt-4 space-y-3">{initial.proposals.map((proposal) => <article key={proposal.id} className="rounded-[var(--radius-control)] border border-border p-3 text-sm"><p className="font-semibold">{proposal.kind} · {proposal.targetType}</p><p className="mt-1 text-muted-foreground">{proposal.reason}</p>{initial.permissions.canReview ? <div className="mt-3 flex gap-2"><Button disabled={pending} onClick={() => post("REVIEW_PROPOSAL", { proposalId: proposal.id, decision: "APPROVED", reason: "Proposta revisada e aprovada por pessoa autorizada." })}>Aprovar</Button><Button variant="secondary" disabled={pending} onClick={() => post("REVIEW_PROPOSAL", { proposalId: proposal.id, decision: "REJECTED", reason: "Proposta revisada e rejeitada por pessoa autorizada." })}>Rejeitar</Button></div> : null}</article>)}</div>}</Surface>
    </div>
    <Surface><SectionHeader title="Catálogo curto de receitas" description="Modelos versionados com gatilhos e ações previamente permitidos." /><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{initial.catalog.map((recipe) => { const installed = initial.recipes.find((item) => item.key === recipe.key); return <article key={recipe.key} className="rounded-[var(--radius-panel)] bg-muted/45 p-4"><h3 className="font-semibold">{recipe.name}</h3><p className="mt-1 text-sm text-muted-foreground">{recipe.trigger} → {recipe.action}</p><p className="mt-2 text-xs font-medium">{recipe.confirmation ? "Exige confirmação humana" : "Sem mutação comercial direta"}</p><details className="mt-3 text-sm"><summary className="cursor-pointer font-semibold">Contrato e limites</summary><p className="mt-2 text-muted-foreground">Payload minimizado; idempotência obrigatória; profundidade máxima 4; fallback em quarentena; SQL, segredos e credenciais humanas proibidos.</p></details>{initial.permissions.canManage && owner && !installed ? <Button className="mt-3" variant="secondary" disabled={pending} onClick={() => post("CREATE_RECIPE", { catalogKey: recipe.key, ownerMemberId: owner.id })}>Adicionar receita</Button> : installed ? <p className="mt-3 text-sm">Estado: {installed.status} · v{installed.currentVersion}</p> : null}</article>; })}</div></Surface>
    <Surface><SectionHeader title="Observabilidade local" description="Comandos, rejeições, correlação e filas vêm dos registros persistidos." />{initial.recentCommands.length === 0 ? <div className="mt-4"><EmptyState title="Nenhuma execução registrada" description="Use a API local assinada para gerar o primeiro recibo determinístico." /></div> : <div className="mt-4 overflow-x-auto"><table className="data-table"><thead><tr><th>Comando</th><th>Status</th><th>Código</th><th>Correlação</th><th>Recebido</th></tr></thead><tbody>{initial.recentCommands.map((command) => <tr key={command.id}><td>{command.commandType}</td><td>{command.status}</td><td>{command.responseCode}</td><td className="font-mono text-xs">{command.correlationId}</td><td>{fmt(command.receivedAt)}</td></tr>)}</tbody></table></div>}</Surface>
  </div>;
}
