import Link from "next/link";

import { Button } from "@/components/ui/button";
import { SectionHeader, StatCard, Surface } from "@/components/ui/surface";
import type { getStage09ReadinessService } from "@/modules/integrations/application/stage09-readiness-service";

type Screen = Awaited<ReturnType<ReturnType<typeof getStage09ReadinessService>["screen"]>>;

const links: Record<string, string> = { EMAIL: "/integracoes/email", TELEPHONY: "/integracoes/telefonia", CALENDAR: "/integracoes/calendario", VIDEO: "/agenda", INSTAGRAM: "/integracoes/instagram" };
const readinessLabels: Record<string, string> = { VALIDATED_LOCALLY: "Validado localmente", EXTERNAL_BLOCKED: "Externo bloqueado", NOT_TESTED: "Não testado" };

export function ChannelReadinessWorkspace({ initial }: Readonly<{ initial: Screen }>) {
  const localProofs = initial.channels.filter((channel) => channel.readiness.some((item) => item.status === "VALIDATED_LOCALLY")).length;
  const homologated = initial.channels.filter((channel) => channel.externalValidation && channel.homologated).length;
  return <div className="space-y-5"><Surface tone={homologated === initial.channels.length ? "accent" : "critical"}><div className="flex flex-wrap items-start justify-between gap-4"><SectionHeader title={homologated ? `${homologated} provider(s) homologado(s)` : "Nenhum provider homologado"} description="A matriz separa evidências locais de credenciais, conta sandbox e validação externa ponta a ponta." /><span className="status-badge" data-tone="warning">Capacidade local: {localProofs}/{initial.channels.length}</span></div></Surface><div className="grid gap-3 sm:grid-cols-3"><StatCard label="Canais avaliados" value={initial.channels.length} hint="Matriz de aceite" /><StatCard label="Com prova local" value={localProofs} hint="Sem equivalência externa" /><StatCard label="Homologados" value={homologated} hint="Providers externos" /></div><div className="grid gap-5 xl:grid-cols-2">{initial.channels.map((channel) => <Surface key={channel.key}><div className="flex flex-wrap items-start justify-between gap-3"><SectionHeader title={channel.label} description={channel.decision.reason} /><span className="status-badge" data-tone={channel.homologated && channel.externalValidation ? "success" : "warning"}>{channel.homologated && channel.externalValidation ? "Homologado" : "Não homologado"}</span></div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm sm:grid-cols-4"><div><dt className="text-muted-foreground">Entradas</dt><dd className="text-lg font-semibold">{channel.proofs.inbound}</dd></div><div><dt className="text-muted-foreground">Saídas</dt><dd className="text-lg font-semibold">{channel.proofs.outbound}</dd></div><div><dt className="text-muted-foreground">Erros</dt><dd className="text-lg font-semibold">{channel.proofs.error}</dd></div><div><dt className="text-muted-foreground">Respostas</dt><dd className="text-lg font-semibold">{channel.proofs.reply}</dd></div></dl><div className="mt-4 space-y-2">{channel.readiness.map((item) => <div className="rounded-[var(--radius-control)] border bg-[var(--surface-subtle)] p-3" key={item.key}><div className="flex flex-wrap items-center justify-between gap-2"><strong className="text-sm">{item.key.replaceAll("_", " ")}</strong><span className="status-badge" data-tone={item.status === "VALIDATED_LOCALLY" ? "success" : item.status === "EXTERNAL_BLOCKED" ? "danger" : "warning"}>{readinessLabels[item.status]}</span></div><p className="mt-1 text-sm text-muted-foreground">{item.detail}</p></div>)}</div><Button asChild className="mt-4" size="sm" variant="secondary"><Link href={links[channel.key] ?? "/integracoes"}>Abrir evidências do canal</Link></Button></Surface>)}</div></div>;
}
