"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { Button } from "@/components/ui/button";

export function RevenueActions({subscriptionId,status}:{subscriptionId:string;status:string}){
  const router=useRouter();const [reason,setReason]=useState("");const [message,setMessage]=useState("");const [pending,setPending]=useState(false);
  async function act(action:"ACTIVATE"|"RENEW"|"SCHEDULE_CANCELLATION"|"CHURN"|"REACTIVATE") {if(reason.trim().length<3){setMessage("Informe um motivo com pelo menos 3 caracteres.");return;}setPending(true);setMessage("");const response=await fetch(`/api/revenue/subscriptions/${subscriptionId}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,effectiveAt:new Date().toISOString(),reason,idempotencyKey:`ui:${action}:${subscriptionId}:${Date.now()}`})});const body=await response.json().catch(()=>null);setPending(false);if(!response.ok){setMessage(body?.error?.message??"Não foi possível registrar a ação.");return;}setMessage("Ação registrada no ledger e na auditoria.");router.refresh();}
  return <section className="surface-panel"><h2>Ações controladas</h2><p className="helper-text">Contrato aceito não ativa receita automaticamente. Confirme cada mudança com motivo; pagamentos não são processados.</p><label className="field-label" htmlFor="revenue-reason">Motivo obrigatório</label><input id="revenue-reason" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Evidência operacional da alteração"/><div className="button-row">{status==="DRAFT"&&<Button disabled={pending} onClick={()=>act("ACTIVATE")}>Ativar assinatura</Button>}{status==="ACTIVE"&&<><Button disabled={pending} onClick={()=>act("RENEW")}>Registrar renovação</Button><Button variant="secondary" disabled={pending} onClick={()=>act("SCHEDULE_CANCELLATION")}>Agendar cancelamento</Button></>}{status==="CANCELLATION_SCHEDULED"&&<Button disabled={pending} onClick={()=>act("CHURN")}>Efetivar churn</Button>}{status==="CHURNED"&&<Button disabled={pending} onClick={()=>act("REACTIVATE")}>Reativar</Button>}</div>{message&&<p role="status">{message}</p>}</section>;
}
