import { redirect } from "next/navigation";
import { PaymentActions } from "@/app/pagamentos/[invoiceId]/payment-actions";
import { PageHeader } from "@/components/layout/page-header";
import { requirePageAuthentication } from "@/modules/auth/http/authentication-guards";
import { getPaymentService } from "@/modules/payments/application/payment-service";
import { AccessDeniedError } from "@/modules/users/permissions/authorization-errors";
export const dynamic="force-dynamic";
const money=(value:bigint)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(value)/100);
const when=(value:Date)=>value.toLocaleString("pt-BR",{timeZone:"America/Sao_Paulo"});
export default async function PaymentDetailPage({params}:{params:Promise<{invoiceId:string}>}){const context=await requirePageAuthentication();let data;try{data=await getPaymentService().detail(context,(await params).invoiceId);}catch(error){if(error instanceof AccessDeniedError)redirect("/acesso-negado");throw error;}const invoice=data.invoice;return <main className="page-canvas"><PageHeader eyebrow="Cobrança" title={invoice.invoiceNumber} description={`${invoice.accountNameSnapshot} · ${invoice.contractNumberSnapshot}`} meta={`${invoice.status} · revisão ${invoice.revision}`}/><section className="metric-grid"><article className="metric-card"><span>Total</span><strong>{money(invoice.totalCents)}</strong></article><article className="metric-card"><span>Pago confirmado</span><strong>{money(invoice.paidCents)}</strong></article><article className="metric-card"><span>Saldo</span><strong>{money(invoice.totalCents-invoice.paidCents)}</strong><small>Vence {invoice.dueAt.toLocaleDateString("pt-BR",{timeZone:"America/Sao_Paulo"})}</small></article></section><PaymentActions invoiceId={invoice.id} status={invoice.status} revision={invoice.revision} canManage={data.permissions.manage} canReprocess={data.permissions.reprocess} deadLetterAttempts={data.attempts.filter(item=>item.status==="DEAD_LETTER")}/><section className="surface-panel"><h2>Itens imutáveis da cobrança</h2><div className="table-scroll"><table><thead><tr><th>#</th><th>Descrição</th><th>Qtd.</th><th>Unitário</th><th>Total</th></tr></thead><tbody>{data.lines.map(line=><tr key={line.id}><td>{line.position}</td><td>{line.descriptionSnapshot}</td><td>{line.quantity}</td><td>{money(line.unitPriceCents)}</td><td>{money(line.totalCents)}</td></tr>)}</tbody></table></div></section><section className="surface-panel"><h2>Tentativas</h2>{data.attempts.length===0?<div className="empty-state"><p>Nenhuma tentativa iniciada.</p></div>:data.attempts.map(item=><p key={item.id}><strong>#{item.sequence} · {item.scenario}</strong> · {item.status} · {when(item.createdAt)}{item.errorCode?` · ${item.errorCode}`:""}</p>)}</section><section className="surface-panel"><h2>Pagamentos reconciliados</h2>{data.payments.length===0?<div className="empty-state"><p>Nenhum pagamento confirmado. Aceite do provider não equivale a pagamento.</p></div>:data.payments.map(item=><p key={item.id}><strong>{money(item.amountCents)}</strong> · {item.status} · {when(item.occurredAt)}</p>)}</section><section className="surface-panel"><h2>Histórico append-only</h2>{data.events.map(item=><p key={item.id}><strong>#{item.sequence} · {item.type}</strong> · {item.reason} · {when(item.occurredAt)}</p>)}</section>{data.issues.length?<section className="surface-panel"><h2>Divergências</h2>{data.issues.map(item=><p key={item.id}><strong>{item.reason}</strong> · {item.status} · revisão humana obrigatória</p>)}</section>:null}<p className="helper-text">Pagamento e receita são domínios separados. Esta tela não cria RevenueMovement.</p></main>}
