import type { PermissionScope } from "@/generated/prisma/client";
import { AccessRoleKeys, PermissionKeys, permissionCatalog, type PermissionKey } from "./permission-keys";

export type AccessRoleKey =
  (typeof AccessRoleKeys)[keyof typeof AccessRoleKeys];

export const defaultRoleDefinitions: ReadonlyArray<
  Readonly<{
    key: AccessRoleKey;
    name: string;
    description: string;
    grants: ReadonlyArray<readonly [PermissionKey, PermissionScope]>;
  }>
> = [
  {
    key: AccessRoleKeys.ADMINISTRATOR,
    name: "Administrador",
    description: "Administração completa da empresa.",
    grants: permissionCatalog.map(({ key }) => [key, "WORKSPACE"]),
  },
  {
    key: AccessRoleKeys.COMMERCIAL_MANAGER,
    name: "Gestor comercial",
    description: "Gestão dos dados e da distribuição de sua equipe.",
    grants: [
      [PermissionKeys.LEADS_READ, "TEAM"],
      [PermissionKeys.LEADS_WRITE, "TEAM"],
      [PermissionKeys.LEADS_ASSIGN, "TEAM"],
      [PermissionKeys.BULK_ACTIONS_EXECUTE, "TEAM"],
      [PermissionKeys.EXPORTS_EXECUTE, "TEAM"],
      [PermissionKeys.PORTABILITY_READ, "WORKSPACE"],
      [PermissionKeys.PORTABILITY_EXPORT, "WORKSPACE"],
      [PermissionKeys.PORTABILITY_MANAGE, "WORKSPACE"],
      [PermissionKeys.CONTACTS_READ, "TEAM"],
      [PermissionKeys.CONTACTS_REVIEW, "WORKSPACE"],
      [PermissionKeys.ACCOUNTS_READ, "WORKSPACE"],
      [PermissionKeys.ACCOUNTS_WRITE, "WORKSPACE"],
      [PermissionKeys.ACCOUNTS_LINK, "WORKSPACE"],
      [PermissionKeys.ACCOUNT_ROLES_MANAGE, "WORKSPACE"],
      [PermissionKeys.BUYING_COMMITTEE_MANAGE, "TEAM"],
      [PermissionKeys.ACCOUNTS_REVIEW, "WORKSPACE"],
      [PermissionKeys.ACCOUNTS_BACKFILL, "WORKSPACE"],
      [PermissionKeys.LIFECYCLE_READ, "TEAM"],
      [PermissionKeys.LIFECYCLE_TRANSITION, "TEAM"],
      [PermissionKeys.LIFECYCLE_OVERRIDE, "TEAM"],
      [PermissionKeys.OWNERSHIP_READ, "TEAM"],
      [PermissionKeys.OWNERSHIP_ASSIGN, "TEAM"],
      [PermissionKeys.OWNERSHIP_TRANSFER, "TEAM"],
      [PermissionKeys.OWNERSHIP_ACCEPT, "TEAM"],
      [PermissionKeys.PRIVACY_STATUS_READ, "TEAM"],
      [PermissionKeys.PRIVACY_CONSENT_RECORD, "TEAM"],
      [PermissionKeys.PRIVACY_DSR_READ, "WORKSPACE"],
      [PermissionKeys.PRIVACY_DSR_MANAGE, "TEAM"],
      [PermissionKeys.INTEGRATIONS_READ, "WORKSPACE"],
      [PermissionKeys.INTEGRATIONS_EXECUTE, "WORKSPACE"],
      [PermissionKeys.INTEGRATIONS_RUNS_READ, "WORKSPACE"],
      [PermissionKeys.INTEGRATIONS_N8N_READ, "WORKSPACE"],
      [PermissionKeys.INTEGRATIONS_N8N_REVIEW, "WORKSPACE"],
      [PermissionKeys.MARKETING_JOURNEY_READ, "WORKSPACE"],
      [PermissionKeys.MARKETING_DEFINITIONS_MANAGE, "WORKSPACE"],
      [PermissionKeys.MARKETING_MODELS_MANAGE, "WORKSPACE"],
      [PermissionKeys.MARKETING_ATTRIBUTION_EXECUTE, "WORKSPACE"],
      [PermissionKeys.MARKETING_MEDIA_READ, "WORKSPACE"],
      [PermissionKeys.MARKETING_MEDIA_IMPORT, "WORKSPACE"],
      [PermissionKeys.MARKETING_MEDIA_RECONCILE, "WORKSPACE"],
      [PermissionKeys.MARKETING_REVIEWS_MANAGE, "WORKSPACE"],
      [PermissionKeys.MARKETING_EVIDENCE_EXPORT, "WORKSPACE"],
      [PermissionKeys.OUTBOUND_CAMPAIGNS_READ, "WORKSPACE"],
      [PermissionKeys.OUTBOUND_CAMPAIGNS_MANAGE, "WORKSPACE"],
      [PermissionKeys.OUTBOUND_CAMPAIGNS_APPROVE, "WORKSPACE"],
      [PermissionKeys.OUTBOUND_CAMPAIGNS_EXECUTE, "WORKSPACE"],
      [PermissionKeys.GEOGRAPHY_READ, "WORKSPACE"],
      [PermissionKeys.GEOGRAPHY_MANAGE, "WORKSPACE"],
      [PermissionKeys.GEOGRAPHY_BACKFILL, "WORKSPACE"],
      [PermissionKeys.INBOX_READ, "TEAM"],
      [PermissionKeys.CONVERSATIONS_ASSIGN, "TEAM"],
      [PermissionKeys.CONVERSATIONS_MANAGE, "TEAM"],
      [PermissionKeys.MESSAGES_COMPOSE, "TEAM"],
      [PermissionKeys.MESSAGES_SEND, "TEAM"],
      [PermissionKeys.MESSAGES_REPLAY, "WORKSPACE"],
      [PermissionKeys.MESSAGES_VIEW_SENSITIVE, "TEAM"],
      [PermissionKeys.MESSAGE_TEMPLATES_MANAGE, "WORKSPACE"],
      [PermissionKeys.INTEGRATIONS_EMAIL_READ, "WORKSPACE"],
      [PermissionKeys.INTEGRATIONS_EMAIL_CONFIGURE, "WORKSPACE"],
      [PermissionKeys.INTEGRATIONS_EMAIL_PAUSE, "WORKSPACE"],
      [PermissionKeys.INTEGRATIONS_EMAIL_TEST_LOCAL, "WORKSPACE"],
      [PermissionKeys.EMAIL_SENDER_MANAGE, "WORKSPACE"],
      [PermissionKeys.EMAIL_DOMAIN_READ, "WORKSPACE"],
      [PermissionKeys.EMAIL_SUPPRESSION_READ, "WORKSPACE"],
      [PermissionKeys.EMAIL_SUPPRESSION_MANAGE, "WORKSPACE"],
      [PermissionKeys.EMAIL_EVENT_REPLAY, "WORKSPACE"],
      [PermissionKeys.TELEPHONY_READ, "WORKSPACE"],
      [PermissionKeys.TELEPHONY_START, "TEAM"],
      [PermissionKeys.TELEPHONY_CANCEL, "TEAM"],
      [PermissionKeys.TELEPHONY_DISPOSITION, "TEAM"],
      [PermissionKeys.TELEPHONY_REPLAY, "WORKSPACE"],
      [PermissionKeys.TELEPHONY_CONFIGURE, "WORKSPACE"],
      [PermissionKeys.TELEPHONY_VIEW_SENSITIVE, "TEAM"],
      [PermissionKeys.CALENDAR_READ, "WORKSPACE"],
      [PermissionKeys.CALENDAR_CONFIGURE, "WORKSPACE"],
      [PermissionKeys.CALENDAR_SYNC, "TEAM"],
      [PermissionKeys.CALENDAR_REPLAY, "WORKSPACE"],
      [PermissionKeys.CALENDAR_CONFLICT_READ, "WORKSPACE"],
      [PermissionKeys.CALENDAR_CONFLICT_RESOLVE, "WORKSPACE"],
      [PermissionKeys.TASKS_READ, "TEAM"],
      [PermissionKeys.TASKS_WRITE, "TEAM"],
      [PermissionKeys.MEETINGS_READ, "TEAM"],
      [PermissionKeys.MEETINGS_WRITE, "TEAM"],
      [PermissionKeys.OPPORTUNITIES_READ, "TEAM"],
      [PermissionKeys.OPPORTUNITIES_WRITE, "TEAM"],
      [PermissionKeys.CONTRACTS_READ, "TEAM"],
      [PermissionKeys.CONTRACTS_CREATE, "TEAM"],
      [PermissionKeys.CONTRACTS_DRAFT_WRITE, "TEAM"],
      [PermissionKeys.CONTRACTS_ISSUE, "TEAM"],
      [PermissionKeys.CONTRACTS_SEND_SIMULATE, "TEAM"],
      [PermissionKeys.CONTRACTS_ACCEPT_RECORD, "TEAM"],
      [PermissionKeys.CONTRACTS_REJECT, "TEAM"],
      [PermissionKeys.CONTRACTS_VOID, "TEAM"],
      [PermissionKeys.CONTRACTS_VERSION_CREATE, "TEAM"],
      [PermissionKeys.CONTRACTS_AUDIT_RECONCILE, "TEAM"],
      [PermissionKeys.REVENUE_READ, "TEAM"],
      [PermissionKeys.REVENUE_MANAGE, "TEAM"],
      [PermissionKeys.REVENUE_EVENTS_RECORD, "TEAM"],
      [PermissionKeys.REVENUE_CORRECT, "TEAM"],
      [PermissionKeys.PAYMENTS_READ, "TEAM"],
      [PermissionKeys.PAYMENTS_MANAGE, "TEAM"],
      [PermissionKeys.PAYMENTS_REPROCESS, "WORKSPACE"],
      [PermissionKeys.PAYMENTS_RECONCILE, "WORKSPACE"],
      [PermissionKeys.FINANCE_READ, "WORKSPACE"],
      [PermissionKeys.FINANCE_MANAGE, "WORKSPACE"],
      [PermissionKeys.FINANCE_COMMISSIONS, "WORKSPACE"],
      [PermissionKeys.ONBOARDING_READ, "TEAM"],
      [PermissionKeys.ONBOARDING_MANAGE, "TEAM"],
      [PermissionKeys.ONBOARDING_ACCEPT, "TEAM"],
      [PermissionKeys.ONBOARDING_EXECUTE, "TEAM"],
      [PermissionKeys.ONBOARDING_ASSIGN, "TEAM"],
      [PermissionKeys.ONBOARDING_CORRECT, "WORKSPACE"],
      [PermissionKeys.CUSTOMER_SUCCESS_READ, "TEAM"],
      [PermissionKeys.CUSTOMER_SUCCESS_PORTFOLIO_MANAGE, "TEAM"],
      [PermissionKeys.CUSTOMER_SUCCESS_PLAN_MANAGE, "TEAM"],
      [PermissionKeys.CUSTOMER_SUCCESS_EVIDENCE_RECORD, "TEAM"],
      [PermissionKeys.CUSTOMER_SUCCESS_HEALTH_EVALUATE, "TEAM"],
      [PermissionKeys.CUSTOMER_SUCCESS_CORRECT, "WORKSPACE"],
      [PermissionKeys.CUSTOMER_SERVICE_READ, "TEAM"],
      [PermissionKeys.CUSTOMER_SERVICE_CREATE, "TEAM"],
      [PermissionKeys.CUSTOMER_SERVICE_RESPOND, "TEAM"],
      [PermissionKeys.CUSTOMER_SERVICE_ASSIGN, "TEAM"],
      [PermissionKeys.CUSTOMER_SERVICE_RESOLVE, "TEAM"],
      [PermissionKeys.CUSTOMER_SERVICE_REOPEN, "TEAM"],
      [PermissionKeys.CUSTOMER_SERVICE_CONFIG_MANAGE, "WORKSPACE"],
      [PermissionKeys.CUSTOMER_SERVICE_SATISFACTION_READ, "TEAM"],
      [PermissionKeys.FARMER_READ, "TEAM"],
      [PermissionKeys.FARMER_RENEWALS_WRITE, "TEAM"],
      [PermissionKeys.FARMER_RENEWALS_CONFIRM, "TEAM"],
      [PermissionKeys.FARMER_EXPANSION_WRITE, "TEAM"],
      [PermissionKeys.FARMER_EXPANSION_CONFIRM, "TEAM"],
      [PermissionKeys.FARMER_REVENUE_CONFIRM, "TEAM"],
      [PermissionKeys.FARMER_CORRECT, "WORKSPACE"],
      [PermissionKeys.FARMER_CONFIG_MANAGE, "WORKSPACE"],
      [PermissionKeys.GOALS_READ, "TEAM"],
      [PermissionKeys.GOALS_MANAGE, "WORKSPACE"],
      [PermissionKeys.GOALS_PUBLISH, "WORKSPACE"],
      [PermissionKeys.GOALS_BACKFILL, "WORKSPACE"],
      [PermissionKeys.FORECAST_READ, "TEAM"],
      [PermissionKeys.FORECAST_SUBMIT, "TEAM"],
      [PermissionKeys.FORECAST_CONSOLIDATE, "TEAM"],
      [PermissionKeys.FORECAST_OVERRIDE, "TEAM"],
      [PermissionKeys.FORECAST_MANAGE, "WORKSPACE"],
      [PermissionKeys.FORECAST_BACKFILL, "WORKSPACE"],
      [PermissionKeys.DATA_QUALITY_READ, "WORKSPACE"],
      [PermissionKeys.DATA_QUALITY_RESOLVE, "WORKSPACE"],
      [PermissionKeys.DATA_QUALITY_MANAGE, "WORKSPACE"],
      [PermissionKeys.DATA_QUALITY_MERGE, "WORKSPACE"],
      [PermissionKeys.DATA_QUALITY_ROLLBACK, "WORKSPACE"],
      [PermissionKeys.OPERATIONS_READ, "WORKSPACE"],
      [PermissionKeys.OPERATIONS_MANAGE, "WORKSPACE"],
      [PermissionKeys.SECURITY_MONITOR_READ, "WORKSPACE"],
      [PermissionKeys.PRIVACY_OPERATIONS_MANAGE, "WORKSPACE"],
      [PermissionKeys.METRICS_READ, "TEAM"],
      [PermissionKeys.AUTOMATIONS_READ, "WORKSPACE"],
      [PermissionKeys.AUTOMATIONS_EXECUTE, "WORKSPACE"],
      [PermissionKeys.AUDIT_READ, "WORKSPACE"],
      [PermissionKeys.AUDIT_MANAGE, "WORKSPACE"],
      [PermissionKeys.AI_USE, "TEAM"],
      [PermissionKeys.AI_MANAGER_QUERY, "TEAM"],
      [PermissionKeys.AI_GOVERNANCE_READ, "WORKSPACE"],
      [PermissionKeys.AI_EVALUATIONS_RUN, "WORKSPACE"],
    ],
  },
  {
    key: AccessRoleKeys.SDR,
    name: "SDR",
    description: "Atendimento dos próprios leads, filas e tarefas.",
    grants: [
      [PermissionKeys.LEADS_READ, "OWN"],
      [PermissionKeys.LEADS_WRITE, "OWN"],
      [PermissionKeys.CONTACTS_READ, "OWN"],
      [PermissionKeys.ACCOUNTS_READ, "OWN"],
      [PermissionKeys.ACCOUNTS_LINK, "OWN"],
      [PermissionKeys.LIFECYCLE_READ, "OWN"],
      [PermissionKeys.OWNERSHIP_READ, "OWN"],
      [PermissionKeys.OWNERSHIP_TRANSFER, "OWN"],
      [PermissionKeys.OWNERSHIP_ACCEPT, "OWN"],
      [PermissionKeys.PRIVACY_STATUS_READ, "OWN"],
      [PermissionKeys.PRIVACY_CONSENT_RECORD, "OWN"],
      [PermissionKeys.TASKS_READ, "OWN"],
      [PermissionKeys.TASKS_WRITE, "OWN"],
      [PermissionKeys.MEETINGS_READ, "OWN"],
      [PermissionKeys.MEETINGS_WRITE, "OWN"],
      [PermissionKeys.DATA_QUALITY_READ, "OWN"],
      [PermissionKeys.DATA_QUALITY_RESOLVE, "OWN"],
      [PermissionKeys.MARKETING_JOURNEY_READ, "OWN"],
      [PermissionKeys.MARKETING_MEDIA_READ, "OWN"],
      [PermissionKeys.GEOGRAPHY_READ, "OWN"],
      [PermissionKeys.INBOX_READ, "OWN"],
      [PermissionKeys.MESSAGES_COMPOSE, "OWN"],
      [PermissionKeys.MESSAGES_SEND, "OWN"],
      [PermissionKeys.MESSAGES_VIEW_SENSITIVE, "OWN"],
      [PermissionKeys.TELEPHONY_READ, "OWN"],
      [PermissionKeys.TELEPHONY_START, "OWN"],
      [PermissionKeys.TELEPHONY_CANCEL, "OWN"],
      [PermissionKeys.TELEPHONY_DISPOSITION, "OWN"],
      [PermissionKeys.CALENDAR_READ, "OWN"],
      [PermissionKeys.CALENDAR_SYNC, "OWN"],
      [PermissionKeys.AI_USE, "OWN"],
      [PermissionKeys.AUTOMATIONS_READ, "OWN"],
    ],
  },
  {
    key: AccessRoleKeys.CLOSER,
    name: "Closer",
    description: "Condução das próprias reuniões e oportunidades.",
    grants: [
      [PermissionKeys.LEADS_READ, "OWN"],
      [PermissionKeys.LEADS_WRITE, "OWN"],
      [PermissionKeys.TASKS_READ, "OWN"],
      [PermissionKeys.TASKS_WRITE, "OWN"],
      [PermissionKeys.MEETINGS_READ, "OWN"],
      [PermissionKeys.MEETINGS_WRITE, "OWN"],
      [PermissionKeys.OPPORTUNITIES_READ, "OWN"],
      [PermissionKeys.OPPORTUNITIES_WRITE, "OWN"],
      [PermissionKeys.CONTRACTS_READ, "OWN"],
      [PermissionKeys.CONTRACTS_CREATE, "OWN"],
      [PermissionKeys.CONTRACTS_DRAFT_WRITE, "OWN"],
      [PermissionKeys.CONTRACTS_ISSUE, "OWN"],
      [PermissionKeys.CONTRACTS_SEND_SIMULATE, "OWN"],
      [PermissionKeys.CONTRACTS_ACCEPT_RECORD, "OWN"],
      [PermissionKeys.CONTRACTS_REJECT, "OWN"],
      [PermissionKeys.CONTRACTS_VERSION_CREATE, "OWN"],
      [PermissionKeys.ONBOARDING_READ, "OWN"],
      [PermissionKeys.ONBOARDING_ACCEPT, "OWN"],
      [PermissionKeys.ONBOARDING_EXECUTE, "OWN"],
      [PermissionKeys.CUSTOMER_SUCCESS_READ, "OWN"],
      [PermissionKeys.CUSTOMER_SUCCESS_PLAN_MANAGE, "OWN"],
      [PermissionKeys.CUSTOMER_SUCCESS_EVIDENCE_RECORD, "OWN"],
      [PermissionKeys.CUSTOMER_SUCCESS_HEALTH_EVALUATE, "OWN"],
      [PermissionKeys.CUSTOMER_SERVICE_READ, "OWN"],
      [PermissionKeys.CUSTOMER_SERVICE_CREATE, "OWN"],
      [PermissionKeys.CUSTOMER_SERVICE_RESPOND, "OWN"],
      [PermissionKeys.CUSTOMER_SERVICE_RESOLVE, "OWN"],
      [PermissionKeys.CUSTOMER_SERVICE_REOPEN, "OWN"],
      [PermissionKeys.CUSTOMER_SERVICE_SATISFACTION_READ, "OWN"],
      [PermissionKeys.FARMER_READ, "OWN"],
      [PermissionKeys.FARMER_RENEWALS_WRITE, "OWN"],
      [PermissionKeys.FARMER_RENEWALS_CONFIRM, "OWN"],
      [PermissionKeys.FARMER_EXPANSION_WRITE, "OWN"],
      [PermissionKeys.FARMER_EXPANSION_CONFIRM, "OWN"],
      [PermissionKeys.FARMER_REVENUE_CONFIRM, "OWN"],
      [PermissionKeys.CONTACTS_READ, "OWN"],
      [PermissionKeys.ACCOUNTS_READ, "OWN"],
      [PermissionKeys.ACCOUNTS_LINK, "OWN"],
      [PermissionKeys.ACCOUNT_ROLES_MANAGE, "OWN"],
      [PermissionKeys.BUYING_COMMITTEE_MANAGE, "OWN"],
      [PermissionKeys.LIFECYCLE_READ, "OWN"],
      [PermissionKeys.LIFECYCLE_TRANSITION, "OWN"],
      [PermissionKeys.OWNERSHIP_READ, "OWN"],
      [PermissionKeys.OWNERSHIP_TRANSFER, "OWN"],
      [PermissionKeys.OWNERSHIP_ACCEPT, "OWN"],
      [PermissionKeys.PRIVACY_STATUS_READ, "OWN"],
      [PermissionKeys.INBOX_READ, "OWN"],
      [PermissionKeys.MESSAGES_COMPOSE, "OWN"],
      [PermissionKeys.MESSAGES_SEND, "OWN"],
      [PermissionKeys.MESSAGES_VIEW_SENSITIVE, "OWN"],
      [PermissionKeys.TELEPHONY_READ, "OWN"],
      [PermissionKeys.TELEPHONY_START, "OWN"],
      [PermissionKeys.TELEPHONY_CANCEL, "OWN"],
      [PermissionKeys.TELEPHONY_DISPOSITION, "OWN"],
      [PermissionKeys.CALENDAR_READ, "OWN"],
      [PermissionKeys.CALENDAR_SYNC, "OWN"],
      [PermissionKeys.PRIVACY_CONSENT_RECORD, "OWN"],
      [PermissionKeys.DATA_QUALITY_READ, "OWN"],
      [PermissionKeys.DATA_QUALITY_RESOLVE, "OWN"],
      [PermissionKeys.MARKETING_JOURNEY_READ, "OWN"],
      [PermissionKeys.MARKETING_MEDIA_READ, "OWN"],
      [PermissionKeys.GEOGRAPHY_READ, "OWN"],
      [PermissionKeys.AI_USE, "OWN"],
      [PermissionKeys.AUTOMATIONS_READ, "OWN"],
    ],
  },
  {
    key: AccessRoleKeys.VIEWER,
    name: "Visualizador",
    description: "Consulta sem permissão de alteração.",
    grants: [
      [PermissionKeys.LEADS_READ, "WORKSPACE"],
      [PermissionKeys.CONTACTS_READ, "WORKSPACE"],
      [PermissionKeys.ACCOUNTS_READ, "WORKSPACE"],
      [PermissionKeys.LIFECYCLE_READ, "WORKSPACE"],
      [PermissionKeys.OWNERSHIP_READ, "WORKSPACE"],
      [PermissionKeys.PRIVACY_STATUS_READ, "WORKSPACE"],
      [PermissionKeys.TASKS_READ, "WORKSPACE"],
      [PermissionKeys.MEETINGS_READ, "WORKSPACE"],
      [PermissionKeys.OPPORTUNITIES_READ, "WORKSPACE"],
      [PermissionKeys.CONTRACTS_READ, "WORKSPACE"],
      [PermissionKeys.ONBOARDING_READ, "WORKSPACE"],
      [PermissionKeys.CUSTOMER_SUCCESS_READ, "WORKSPACE"],
      [PermissionKeys.CUSTOMER_SERVICE_READ, "WORKSPACE"],
      [PermissionKeys.CUSTOMER_SERVICE_SATISFACTION_READ, "WORKSPACE"],
      [PermissionKeys.FARMER_READ, "WORKSPACE"],
      [PermissionKeys.DATA_QUALITY_READ, "WORKSPACE"],
      [PermissionKeys.MARKETING_JOURNEY_READ, "WORKSPACE"],
      [PermissionKeys.MARKETING_MEDIA_READ, "WORKSPACE"],
      [PermissionKeys.GEOGRAPHY_READ, "WORKSPACE"],
      [PermissionKeys.INBOX_READ, "WORKSPACE"],
      [PermissionKeys.TELEPHONY_READ, "WORKSPACE"],
      [PermissionKeys.CALENDAR_READ, "WORKSPACE"],
      [PermissionKeys.CALENDAR_CONFLICT_READ, "WORKSPACE"],
    ],
  },
];
