export const PermissionKeys = Object.freeze({
  WORKSPACE_MANAGE: "workspace.manage",
  WORKSPACE_MEMBERS_MANAGE: "workspace.members.manage",
  WORKSPACE_PERMISSIONS_MANAGE: "workspace.permissions.manage",
  LEADS_READ: "leads.read",
  LEADS_WRITE: "leads.write",
  LEADS_ASSIGN: "leads.assign",
  BULK_ACTIONS_EXECUTE: "bulk_actions.execute",
  EXPORTS_EXECUTE: "exports.execute",
  PORTABILITY_READ: "portability.read",
  PORTABILITY_EXPORT: "portability.export",
  PORTABILITY_MANAGE: "portability.manage",
  CONTACTS_READ: "contacts.read",
  CONTACTS_REVIEW: "contacts.review",
  CONTACTS_BACKFILL: "contacts.backfill",
  ACCOUNTS_READ: "accounts.read",
  ACCOUNTS_WRITE: "accounts.write",
  ACCOUNTS_LINK: "accounts.link",
  ACCOUNT_ROLES_MANAGE: "accounts.roles.manage",
  BUYING_COMMITTEE_MANAGE: "accounts.committee.manage",
  ACCOUNTS_REVIEW: "accounts.review",
  ACCOUNTS_BACKFILL: "accounts.backfill",
  LIFECYCLE_READ: "lifecycle.read",
  LIFECYCLE_TRANSITION: "lifecycle.transition",
  LIFECYCLE_OVERRIDE: "lifecycle.override",
  OWNERSHIP_READ: "ownership.read",
  OWNERSHIP_ASSIGN: "ownership.assign",
  OWNERSHIP_TRANSFER: "ownership.transfer",
  OWNERSHIP_ACCEPT: "ownership.accept",
  OWNERSHIP_ADMIN: "ownership.admin",
  PRIVACY_STATUS_READ: "privacy.status.read",
  PRIVACY_CONSENT_RECORD: "privacy.consent.record",
  PRIVACY_CONSENT_CORRECT: "privacy.consent.correct",
  PRIVACY_PURPOSE_MANAGE: "privacy.purpose.manage",
  PRIVACY_LEGAL_APPROVE: "privacy.legal.approve",
  PRIVACY_RETENTION_MANAGE: "privacy.retention.manage",
  PRIVACY_RETENTION_EXECUTE: "privacy.retention.execute",
  PRIVACY_DSR_READ: "privacy.dsr.read",
  PRIVACY_DSR_MANAGE: "privacy.dsr.manage",
  PRIVACY_DSR_EXPORT: "privacy.dsr.export",
  PRIVACY_LEGAL_HOLD_MANAGE: "privacy.legal_hold.manage",
  PRIVACY_BACKFILL: "privacy.backfill",
  INTEGRATIONS_READ: "integrations.read",
  INTEGRATIONS_MANAGE: "integrations.manage",
  INTEGRATIONS_SECRETS_MANAGE: "integrations.secrets.manage",
  INTEGRATIONS_EXECUTE: "integrations.execute",
  INTEGRATIONS_RUNS_READ: "integrations.runs.read",
  INTEGRATIONS_REPLAY: "integrations.replay",
  INTEGRATIONS_MAPPINGS_MANAGE: "integrations.mappings.manage",
  INTEGRATIONS_N8N_READ: "integrations.n8n.read",
  INTEGRATIONS_N8N_MANAGE: "integrations.n8n.manage",
  INTEGRATIONS_N8N_REVIEW: "integrations.n8n.review",
  MARKETING_JOURNEY_READ: "marketing.journey.read",
  MARKETING_DEFINITIONS_MANAGE: "marketing.definitions.manage",
  MARKETING_MODELS_MANAGE: "marketing.models.manage",
  MARKETING_ATTRIBUTION_EXECUTE: "marketing.attribution.execute",
  MARKETING_REVIEWS_MANAGE: "marketing.reviews.manage",
  MARKETING_EVIDENCE_EXPORT: "marketing.evidence.export",
  MARKETING_MEDIA_READ: "marketing.media.read",
  MARKETING_MEDIA_IMPORT: "marketing.media.import",
  MARKETING_MEDIA_RECONCILE: "marketing.media.reconcile",
  OUTBOUND_CAMPAIGNS_READ: "outbound_campaigns.read",
  OUTBOUND_CAMPAIGNS_MANAGE: "outbound_campaigns.manage",
  OUTBOUND_CAMPAIGNS_APPROVE: "outbound_campaigns.approve",
  OUTBOUND_CAMPAIGNS_EXECUTE: "outbound_campaigns.execute",
  GEOGRAPHY_READ: "geography.read",
  GEOGRAPHY_MANAGE: "geography.manage",
  GEOGRAPHY_BACKFILL: "geography.backfill",
  INBOX_READ: "inbox.read",
  CONVERSATIONS_ASSIGN: "conversations.assign",
  CONVERSATIONS_MANAGE: "conversations.manage",
  MESSAGES_COMPOSE: "messages.compose",
  MESSAGES_SEND: "messages.send",
  MESSAGES_REPLAY: "messages.replay",
  MESSAGES_VIEW_SENSITIVE: "messages.view_sensitive",
  MESSAGE_TEMPLATES_MANAGE: "message_templates.manage",
  INTEGRATIONS_EMAIL_READ: "integrations.email.read",
  INTEGRATIONS_EMAIL_CONFIGURE: "integrations.email.configure",
  INTEGRATIONS_EMAIL_PAUSE: "integrations.email.pause",
  INTEGRATIONS_EMAIL_TEST_LOCAL: "integrations.email.test_local",
  EMAIL_SENDER_MANAGE: "email.sender.manage",
  EMAIL_DOMAIN_READ: "email.domain.read",
  EMAIL_SUPPRESSION_READ: "email.suppression.read",
  EMAIL_SUPPRESSION_MANAGE: "email.suppression.manage",
  EMAIL_EVENT_REPLAY: "email.event.replay",
  TELEPHONY_READ: "telephony.read",
  TELEPHONY_START: "telephony.start",
  TELEPHONY_CANCEL: "telephony.cancel",
  TELEPHONY_DISPOSITION: "telephony.disposition",
  TELEPHONY_REPLAY: "telephony.replay",
  TELEPHONY_CONFIGURE: "telephony.configure",
  TELEPHONY_VIEW_SENSITIVE: "telephony.view_sensitive",
  CALENDAR_READ: "calendar.read",
  CALENDAR_CONFIGURE: "calendar.configure",
  CALENDAR_SYNC: "calendar.sync",
  CALENDAR_REPLAY: "calendar.replay",
  CALENDAR_CONFLICT_READ: "calendar.conflict.read",
  CALENDAR_CONFLICT_RESOLVE: "calendar.conflict.resolve",
  TASKS_READ: "tasks.read",
  TASKS_WRITE: "tasks.write",
  MEETINGS_READ: "meetings.read",
  MEETINGS_WRITE: "meetings.write",
  MEETING_TRANSCRIPTS_READ: "meetings.transcripts.read",
  MEETING_TRANSCRIPTS_MANAGE: "meetings.transcripts.manage",
  OPPORTUNITIES_READ: "opportunities.read",
  OPPORTUNITIES_WRITE: "opportunities.write",
  CONTRACTS_READ: "contracts.read",
  CONTRACTS_CREATE: "contracts.create",
  CONTRACTS_DRAFT_WRITE: "contracts.draft.write",
  CONTRACTS_ISSUE: "contracts.issue",
  CONTRACTS_SEND_SIMULATE: "contracts.send.simulate",
  CONTRACTS_ACCEPT_RECORD: "contracts.accept.record",
  CONTRACTS_REJECT: "contracts.reject",
  CONTRACTS_VOID: "contracts.void",
  CONTRACTS_VERSION_CREATE: "contracts.version.create",
  CONTRACTS_TEMPLATES_MANAGE: "contracts.templates.manage",
  CONTRACTS_AUDIT_RECONCILE: "contracts.audit.reconcile",
  REVENUE_READ: "revenue.read",
  REVENUE_MANAGE: "revenue.manage",
  REVENUE_EVENTS_RECORD: "revenue.events.record",
  REVENUE_CORRECT: "revenue.correct",
  PAYMENTS_READ: "payments.read",
  PAYMENTS_MANAGE: "payments.manage",
  PAYMENTS_REPROCESS: "payments.reprocess",
  PAYMENTS_RECONCILE: "payments.reconcile",
  FINANCE_READ: "finance.read",
  FINANCE_MANAGE: "finance.manage",
  FINANCE_COMMISSIONS: "finance.commissions",
  ONBOARDING_READ: "onboarding.read",
  ONBOARDING_MANAGE: "onboarding.manage",
  ONBOARDING_ACCEPT: "onboarding.accept",
  ONBOARDING_EXECUTE: "onboarding.execute",
  ONBOARDING_ASSIGN: "onboarding.assign",
  ONBOARDING_CORRECT: "onboarding.correct",
  CUSTOMER_SUCCESS_READ: "customer_success.read",
  CUSTOMER_SUCCESS_PORTFOLIO_MANAGE: "customer_success.portfolio.manage",
  CUSTOMER_SUCCESS_PLAN_MANAGE: "customer_success.plan.manage",
  CUSTOMER_SUCCESS_EVIDENCE_RECORD: "customer_success.evidence.record",
  CUSTOMER_SUCCESS_HEALTH_EVALUATE: "customer_success.health.evaluate",
  CUSTOMER_SUCCESS_CORRECT: "customer_success.correct",
  CUSTOMER_SERVICE_READ: "customer_service.read",
  CUSTOMER_SERVICE_CREATE: "customer_service.create",
  CUSTOMER_SERVICE_RESPOND: "customer_service.respond",
  CUSTOMER_SERVICE_ASSIGN: "customer_service.assign",
  CUSTOMER_SERVICE_RESOLVE: "customer_service.resolve",
  CUSTOMER_SERVICE_REOPEN: "customer_service.reopen",
  CUSTOMER_SERVICE_CONFIG_MANAGE: "customer_service.config.manage",
  CUSTOMER_SERVICE_SATISFACTION_READ: "customer_service.satisfaction.read",
  FARMER_READ: "farmer.read",
  FARMER_RENEWALS_WRITE: "farmer.renewals.write",
  FARMER_RENEWALS_CONFIRM: "farmer.renewals.confirm",
  FARMER_EXPANSION_WRITE: "farmer.expansion.write",
  FARMER_EXPANSION_CONFIRM: "farmer.expansion.confirm",
  FARMER_REVENUE_CONFIRM: "farmer.revenue.confirm",
  FARMER_CORRECT: "farmer.correct",
  FARMER_CONFIG_MANAGE: "farmer.config.manage",
  GOALS_READ: "goals.read",
  GOALS_MANAGE: "goals.manage",
  GOALS_PUBLISH: "goals.publish",
  GOALS_BACKFILL: "goals.backfill",
  FORECAST_READ: "forecast.read",
  FORECAST_SUBMIT: "forecast.submit",
  FORECAST_CONSOLIDATE: "forecast.consolidate",
  FORECAST_OVERRIDE: "forecast.override",
  FORECAST_MANAGE: "forecast.manage",
  FORECAST_BACKFILL: "forecast.backfill",
  DATA_QUALITY_READ: "data_quality.read",
  DATA_QUALITY_RESOLVE: "data_quality.resolve",
  DATA_QUALITY_MANAGE: "data_quality.manage",
  DATA_QUALITY_MERGE: "data_quality.merge",
  DATA_QUALITY_ROLLBACK: "data_quality.rollback",
  OPERATIONS_READ: "operations.read",
  OPERATIONS_MANAGE: "operations.manage",
  SECURITY_MONITOR_READ: "security.monitor.read",
  PRIVACY_OPERATIONS_MANAGE: "privacy.operations.manage",
  METRICS_READ: "metrics.read",
  AUTOMATIONS_READ: "automations.read",
  AUTOMATIONS_EXECUTE: "automations.execute",
  AUTOMATIONS_MANAGE: "automations.manage",
  AUDIT_READ: "audit.read",
  AUDIT_MANAGE: "audit.manage",
  AI_USE: "ai.use",
  AI_MANAGER_QUERY: "ai.manager.query",
  AI_GOVERNANCE_READ: "ai.governance.read",
  AI_GOVERNANCE_MANAGE: "ai.governance.manage",
  AI_EVALUATIONS_RUN: "ai.evaluations.run",
} as const);

export type PermissionKey =
  (typeof PermissionKeys)[keyof typeof PermissionKeys];

export const AccessRoleKeys = Object.freeze({
  ADMINISTRATOR: "administrator",
  COMMERCIAL_MANAGER: "commercial_manager",
  SDR: "sdr",
  CLOSER: "closer",
  VIEWER: "viewer",
} as const);

export const permissionCatalog: ReadonlyArray<
  Readonly<{ key: PermissionKey; description: string }>
> = [
  { key: PermissionKeys.WORKSPACE_MANAGE, description: "Gerenciar workspace" },
  {
    key: PermissionKeys.WORKSPACE_MEMBERS_MANAGE,
    description: "Gerenciar membros e papéis",
  },
  {
    key: PermissionKeys.WORKSPACE_PERMISSIONS_MANAGE,
    description: "Gerenciar concessões de permissões",
  },
  { key: PermissionKeys.LEADS_READ, description: "Consultar leads" },
  { key: PermissionKeys.LEADS_WRITE, description: "Alterar leads" },
  { key: PermissionKeys.LEADS_ASSIGN, description: "Distribuir leads" },
  { key: PermissionKeys.BULK_ACTIONS_EXECUTE, description: "Executar ações em massa dentro do escopo autorizado" },
  { key: PermissionKeys.EXPORTS_EXECUTE, description: "Exportar dados dentro do escopo autorizado" },
  { key: PermissionKeys.PORTABILITY_READ, description: "Consultar portabilidade comercial" },
  { key: PermissionKeys.PORTABILITY_EXPORT, description: "Exportar contatos e negócios autorizados" },
  { key: PermissionKeys.PORTABILITY_MANAGE, description: "Gerenciar tags, campos e ações em massa" },
  {
    key: PermissionKeys.CONTACTS_READ,
    description: "Consultar a identidade canônica de contatos",
  },
  {
    key: PermissionKeys.CONTACTS_REVIEW,
    description: "Revisar colisões de identidade sem mesclagem automática",
  },
  {
    key: PermissionKeys.CONTACTS_BACKFILL,
    description: "Executar e controlar o backfill de contatos",
  },
  { key: PermissionKeys.ACCOUNTS_READ, description: "Consultar contas canônicas" },
  { key: PermissionKeys.ACCOUNTS_WRITE, description: "Criar e alterar contas canônicas" },
  { key: PermissionKeys.ACCOUNTS_LINK, description: "Vincular leads e oportunidades a contas" },
  { key: PermissionKeys.ACCOUNT_ROLES_MANAGE, description: "Gerenciar papéis temporais de contatos em contas" },
  { key: PermissionKeys.BUYING_COMMITTEE_MANAGE, description: "Gerenciar comitês de compra" },
  { key: PermissionKeys.ACCOUNTS_REVIEW, description: "Resolver revisões de identidade de contas" },
  { key: PermissionKeys.ACCOUNTS_BACKFILL, description: "Executar backfill governado de candidatos a conta" },
  { key: PermissionKeys.LIFECYCLE_READ, description: "Consultar lifecycle e histórico de receita" },
  { key: PermissionKeys.LIFECYCLE_TRANSITION, description: "Executar transições válidas de lifecycle" },
  { key: PermissionKeys.LIFECYCLE_OVERRIDE, description: "Corrigir lifecycle com confirmação e motivo" },
  { key: PermissionKeys.OWNERSHIP_READ, description: "Consultar responsabilidades por função" },
  { key: PermissionKeys.OWNERSHIP_ASSIGN, description: "Atribuir responsabilidade temporal" },
  { key: PermissionKeys.OWNERSHIP_TRANSFER, description: "Solicitar e cancelar transferências" },
  { key: PermissionKeys.OWNERSHIP_ACCEPT, description: "Aceitar ou rejeitar transferências recebidas" },
  { key: PermissionKeys.OWNERSHIP_ADMIN, description: "Administrar regras e backfill de lifecycle" },
  { key: PermissionKeys.PRIVACY_STATUS_READ, description: "Consultar decisão prática de privacidade" },
  { key: PermissionKeys.PRIVACY_CONSENT_RECORD, description: "Registrar consentimento, negativa ou revogação" },
  { key: PermissionKeys.PRIVACY_CONSENT_CORRECT, description: "Registrar correção de evento de consentimento" },
  { key: PermissionKeys.PRIVACY_PURPOSE_MANAGE, description: "Gerenciar finalidades e versões" },
  { key: PermissionKeys.PRIVACY_LEGAL_APPROVE, description: "Aprovar bases e políticas após revisão jurídica" },
  { key: PermissionKeys.PRIVACY_RETENTION_MANAGE, description: "Gerenciar políticas e ações de retenção" },
  { key: PermissionKeys.PRIVACY_RETENTION_EXECUTE, description: "Executar retenção previamente aprovada" },
  { key: PermissionKeys.PRIVACY_DSR_READ, description: "Consultar solicitações de titulares" },
  { key: PermissionKeys.PRIVACY_DSR_MANAGE, description: "Gerenciar solicitações de titulares" },
  { key: PermissionKeys.PRIVACY_DSR_EXPORT, description: "Gerar pacote mínimo autorizado do titular" },
  { key: PermissionKeys.PRIVACY_LEGAL_HOLD_MANAGE, description: "Criar e liberar legal holds limitados" },
  { key: PermissionKeys.PRIVACY_BACKFILL, description: "Executar backfill local de privacidade" },
  { key: PermissionKeys.INTEGRATIONS_READ, description: "Consultar conexões e capacidades de integração" },
  { key: PermissionKeys.INTEGRATIONS_MANAGE, description: "Configurar e pausar integrações locais" },
  { key: PermissionKeys.INTEGRATIONS_SECRETS_MANAGE, description: "Gerenciar somente referências de segredos" },
  { key: PermissionKeys.INTEGRATIONS_EXECUTE, description: "Executar testes e sincronizações locais" },
  { key: PermissionKeys.INTEGRATIONS_RUNS_READ, description: "Consultar execuções e tentativas de integração" },
  { key: PermissionKeys.INTEGRATIONS_REPLAY, description: "Solicitar replay controlado de integrações" },
  { key: PermissionKeys.INTEGRATIONS_MAPPINGS_MANAGE, description: "Revisar mapeamentos e conflitos externos" },
  { key: PermissionKeys.INTEGRATIONS_N8N_READ, description: "Consultar o sandbox local e receitas n8n" },
  { key: PermissionKeys.INTEGRATIONS_N8N_MANAGE, description: "Administrar identidades, escopos e receitas n8n" },
  { key: PermissionKeys.INTEGRATIONS_N8N_REVIEW, description: "Revisar propostas consequenciais originadas pelo n8n" },
  { key: PermissionKeys.MARKETING_JOURNEY_READ, description: "Consultar jornada e atribuição de aquisição" },
  { key: PermissionKeys.MARKETING_DEFINITIONS_MANAGE, description: "Gerenciar landing pages e formulários versionados" },
  { key: PermissionKeys.MARKETING_MODELS_MANAGE, description: "Gerenciar modelos versionados de atribuição" },
  { key: PermissionKeys.MARKETING_ATTRIBUTION_EXECUTE, description: "Executar cálculo e backfill de atribuição" },
  { key: PermissionKeys.MARKETING_REVIEWS_MANAGE, description: "Revisar divergências de aquisição" },
  { key: PermissionKeys.MARKETING_EVIDENCE_EXPORT, description: "Exportar evidências mínimas de atribuição" },
  { key: PermissionKeys.MARKETING_MEDIA_READ, description: "Consultar hierarquia e performance de mídia" },
  { key: PermissionKeys.MARKETING_MEDIA_IMPORT, description: "Pré-visualizar, confirmar e estornar importações locais de mídia" },
  { key: PermissionKeys.MARKETING_MEDIA_RECONCILE, description: "Executar e revisar reconciliação mídia versus CRM" },
  { key: PermissionKeys.OUTBOUND_CAMPAIGNS_READ, description: "Consultar campanhas de comunicação e recibos" },
  { key: PermissionKeys.OUTBOUND_CAMPAIGNS_MANAGE, description: "Configurar e pré-visualizar campanhas de comunicação" },
  { key: PermissionKeys.OUTBOUND_CAMPAIGNS_APPROVE, description: "Aprovar público congelado e ações pós-envio" },
  { key: PermissionKeys.OUTBOUND_CAMPAIGNS_EXECUTE, description: "Executar, cancelar e reprocessar campanhas de comunicação" },
  { key: PermissionKeys.GEOGRAPHY_READ, description: "Consultar inteligência geográfica agregada" },
  { key: PermissionKeys.GEOGRAPHY_MANAGE, description: "Versionar territórios e resolver divergências geográficas" },
  { key: PermissionKeys.GEOGRAPHY_BACKFILL, description: "Executar backfill geográfico conservador" },
  { key: PermissionKeys.INBOX_READ, description: "Consultar inbox e conversas autorizadas" },
  { key: PermissionKeys.CONVERSATIONS_ASSIGN, description: "Assumir e transferir conversas" },
  { key: PermissionKeys.CONVERSATIONS_MANAGE, description: "Resolver, reabrir e arquivar conversas" },
  { key: PermissionKeys.MESSAGES_COMPOSE, description: "Compor mensagens em conversas autorizadas" },
  { key: PermissionKeys.MESSAGES_SEND, description: "Enfileirar mensagens após decisão de privacidade" },
  { key: PermissionKeys.MESSAGES_REPLAY, description: "Reprocessar entrega simulada e eventos idempotentes" },
  { key: PermissionKeys.MESSAGES_VIEW_SENSITIVE, description: "Visualizar conteúdo sensível não redigido" },
  { key: PermissionKeys.MESSAGE_TEMPLATES_MANAGE, description: "Versionar templates locais de mensagem" },
  { key: PermissionKeys.INTEGRATIONS_EMAIL_READ, description: "Consultar a integração local de e-mail" },
  { key: PermissionKeys.INTEGRATIONS_EMAIL_CONFIGURE, description: "Configurar referências e sender de e-mail" },
  { key: PermissionKeys.INTEGRATIONS_EMAIL_PAUSE, description: "Pausar ou retomar o sink local de e-mail" },
  { key: PermissionKeys.INTEGRATIONS_EMAIL_TEST_LOCAL, description: "Executar cenários locais de e-mail sem egress" },
  { key: PermissionKeys.EMAIL_SENDER_MANAGE, description: "Gerenciar identidade autorizada do remetente" },
  { key: PermissionKeys.EMAIL_DOMAIN_READ, description: "Consultar observações de entregabilidade do domínio" },
  { key: PermissionKeys.EMAIL_SUPPRESSION_READ, description: "Consultar suppressions de e-mail" },
  { key: PermissionKeys.EMAIL_SUPPRESSION_MANAGE, description: "Registrar ou liberar suppression de e-mail" },
  { key: PermissionKeys.EMAIL_EVENT_REPLAY, description: "Reprocessar eventos locais de e-mail" },
  { key: PermissionKeys.TELEPHONY_READ, description: "Consultar ligações dentro do escopo autorizado" },
  { key: PermissionKeys.TELEPHONY_START, description: "Iniciar uma ligação no simulador local" },
  { key: PermissionKeys.TELEPHONY_CANCEL, description: "Cancelar uma ligação ainda não terminal" },
  { key: PermissionKeys.TELEPHONY_DISPOSITION, description: "Registrar resultado comercial da ligação" },
  { key: PermissionKeys.TELEPHONY_REPLAY, description: "Reprocessar uma falha terminal de telefonia local" },
  { key: PermissionKeys.TELEPHONY_CONFIGURE, description: "Configurar e pausar a telefonia local" },
  { key: PermissionKeys.TELEPHONY_VIEW_SENSITIVE, description: "Visualizar referência telefônica sem máscara" },
  { key: PermissionKeys.CALENDAR_READ, description: "Consultar sincronização de reuniões com calendário" },
  { key: PermissionKeys.CALENDAR_CONFIGURE, description: "Configurar ou pausar o calendário local" },
  { key: PermissionKeys.CALENDAR_SYNC, description: "Sincronizar reuniões autorizadas" },
  { key: PermissionKeys.CALENDAR_REPLAY, description: "Reprocessar falhas terminais de calendário" },
  { key: PermissionKeys.CALENDAR_CONFLICT_READ, description: "Consultar conflitos de sincronização" },
  { key: PermissionKeys.CALENDAR_CONFLICT_RESOLVE, description: "Resolver conflitos de calendário com motivo" },
  { key: PermissionKeys.TASKS_READ, description: "Consultar tarefas" },
  { key: PermissionKeys.TASKS_WRITE, description: "Alterar tarefas" },
  { key: PermissionKeys.MEETINGS_READ, description: "Consultar reuniões" },
  { key: PermissionKeys.MEETINGS_WRITE, description: "Alterar reuniões" },
  { key: PermissionKeys.MEETING_TRANSCRIPTS_READ, description: "Consultar transcrições e resumos de reunião com consentimento" },
  { key: PermissionKeys.MEETING_TRANSCRIPTS_MANAGE, description: "Registrar artefatos de transcrição com consentimento e retenção" },
  {
    key: PermissionKeys.OPPORTUNITIES_READ,
    description: "Consultar oportunidades",
  },
  {
    key: PermissionKeys.OPPORTUNITIES_WRITE,
    description: "Alterar oportunidades",
  },
  { key: PermissionKeys.CONTRACTS_READ, description: "Consultar contratos comerciais" },
  { key: PermissionKeys.CONTRACTS_CREATE, description: "Criar contrato a partir de oportunidade" },
  { key: PermissionKeys.CONTRACTS_DRAFT_WRITE, description: "Revisar rascunhos contratuais" },
  { key: PermissionKeys.CONTRACTS_ISSUE, description: "Emitir versão contratual imutável" },
  { key: PermissionKeys.CONTRACTS_SEND_SIMULATE, description: "Registrar envio somente simulado" },
  { key: PermissionKeys.CONTRACTS_ACCEPT_RECORD, description: "Registrar aceite manual local" },
  { key: PermissionKeys.CONTRACTS_REJECT, description: "Registrar rejeição de contrato" },
  { key: PermissionKeys.CONTRACTS_VOID, description: "Anular contrato com justificativa" },
  { key: PermissionKeys.CONTRACTS_VERSION_CREATE, description: "Criar versão substituta de contrato" },
  { key: PermissionKeys.CONTRACTS_TEMPLATES_MANAGE, description: "Gerenciar templates contratuais" },
  { key: PermissionKeys.CONTRACTS_AUDIT_RECONCILE, description: "Auditar e reconciliar contratos" },
  { key: PermissionKeys.REVENUE_READ, description: "Consultar assinaturas e ledger de receita" },
  { key: PermissionKeys.REVENUE_MANAGE, description: "Gerenciar ciclo de assinaturas" },
  { key: PermissionKeys.REVENUE_EVENTS_RECORD, description: "Registrar movimentos de receita" },
  { key: PermissionKeys.REVENUE_CORRECT, description: "Corrigir movimentos por estorno explícito" },
  { key: PermissionKeys.PAYMENTS_READ, description: "Consultar cobranças e pagamentos reconciliados" },
  { key: PermissionKeys.PAYMENTS_MANAGE, description: "Emitir cobranças e iniciar tentativas no sandbox local" },
  { key: PermissionKeys.PAYMENTS_REPROCESS, description: "Reprocessar tentativas e receipts em falha terminal" },
  { key: PermissionKeys.PAYMENTS_RECONCILE, description: "Resolver divergências de pagamento com evidência" },
  { key: PermissionKeys.FINANCE_READ, description: "Consultar o módulo financeiro integrado" },
  { key: PermissionKeys.FINANCE_MANAGE, description: "Gerenciar lançamentos, contas e categorias financeiras" },
  { key: PermissionKeys.FINANCE_COMMISSIONS, description: "Gerenciar regras e liquidações de comissões" },
  { key: PermissionKeys.ONBOARDING_READ, description: "Consultar handoffs e onboardings" },
  { key: PermissionKeys.ONBOARDING_MANAGE, description: "Preparar e enviar handoffs" },
  { key: PermissionKeys.ONBOARDING_ACCEPT, description: "Aceitar ou rejeitar handoffs" },
  { key: PermissionKeys.ONBOARDING_EXECUTE, description: "Executar marcos e ativação" },
  { key: PermissionKeys.ONBOARDING_ASSIGN, description: "Reatribuir onboarding" },
  { key: PermissionKeys.ONBOARDING_CORRECT, description: "Corrigir ou cancelar onboarding" },
  { key: PermissionKeys.CUSTOMER_SUCCESS_READ, description: "Consultar carteira e saúde de clientes" },
  { key: PermissionKeys.CUSTOMER_SUCCESS_PORTFOLIO_MANAGE, description: "Atribuir e reatribuir carteira de Customer Success" },
  { key: PermissionKeys.CUSTOMER_SUCCESS_PLAN_MANAGE, description: "Criar e conduzir planos de sucesso" },
  { key: PermissionKeys.CUSTOMER_SUCCESS_EVIDENCE_RECORD, description: "Registrar evidências de resultados do cliente" },
  { key: PermissionKeys.CUSTOMER_SUCCESS_HEALTH_EVALUATE, description: "Calcular saúde por regra publicada" },
  { key: PermissionKeys.CUSTOMER_SUCCESS_CORRECT, description: "Executar correções governadas de Customer Success" },
  { key: PermissionKeys.CUSTOMER_SERVICE_READ, description: "Consultar solicitações de clientes" },
  { key: PermissionKeys.CUSTOMER_SERVICE_CREATE, description: "Registrar solicitações de clientes" },
  { key: PermissionKeys.CUSTOMER_SERVICE_RESPOND, description: "Responder e atualizar solicitações de clientes" },
  { key: PermissionKeys.CUSTOMER_SERVICE_ASSIGN, description: "Atribuir solicitações de clientes" },
  { key: PermissionKeys.CUSTOMER_SERVICE_RESOLVE, description: "Resolver e fechar solicitações de clientes" },
  { key: PermissionKeys.CUSTOMER_SERVICE_REOPEN, description: "Reabrir solicitações de clientes" },
  { key: PermissionKeys.CUSTOMER_SERVICE_CONFIG_MANAGE, description: "Publicar políticas de SLA e pesquisas" },
  { key: PermissionKeys.CUSTOMER_SERVICE_SATISFACTION_READ, description: "Consultar satisfação e comentários autorizados" },
  { key: PermissionKeys.FARMER_READ, description: "Consultar carteira Farmer, renovações e decisões" },
  { key: PermissionKeys.FARMER_RENEWALS_WRITE, description: "Preparar renovação, risco e próxima ação" },
  { key: PermissionKeys.FARMER_RENEWALS_CONFIRM, description: "Confirmar decisão humana de renovação" },
  { key: PermissionKeys.FARMER_EXPANSION_WRITE, description: "Registrar e revisar sinais de expansão" },
  { key: PermissionKeys.FARMER_EXPANSION_CONFIRM, description: "Criar ou vincular oportunidade de expansão" },
  { key: PermissionKeys.FARMER_REVENUE_CONFIRM, description: "Confirmar contração ou churn com impacto explícito" },
  { key: PermissionKeys.FARMER_CORRECT, description: "Reverter decisão financeira com movimento compensatório" },
  { key: PermissionKeys.FARMER_CONFIG_MANAGE, description: "Versionar motivos e políticas Farmer" },
  { key: PermissionKeys.GOALS_READ, description: "Consultar metas, quotas e atingimento dentro do escopo" },
  { key: PermissionKeys.GOALS_MANAGE, description: "Criar e revisar planos de metas em rascunho" },
  { key: PermissionKeys.GOALS_PUBLISH, description: "Publicar, substituir e retirar planos de metas" },
  { key: PermissionKeys.GOALS_BACKFILL, description: "Executar diagnóstico conservador de metas legadas" },
  { key: PermissionKeys.FORECAST_READ, description: "Consultar forecast, composição e cortes dentro do escopo" },
  { key: PermissionKeys.FORECAST_SUBMIT, description: "Registrar uma leitura humana versionada do próprio pipeline" },
  { key: PermissionKeys.FORECAST_CONSOLIDATE, description: "Publicar snapshot consolidado e reproduzível" },
  { key: PermissionKeys.FORECAST_OVERRIDE, description: "Registrar override gerencial explícito e comentado" },
  { key: PermissionKeys.FORECAST_MANAGE, description: "Criar e encerrar ciclos de forecast" },
  { key: PermissionKeys.FORECAST_BACKFILL, description: "Executar diagnóstico conservador de sinais legados de forecast" },
  { key: PermissionKeys.DATA_QUALITY_READ, description: "Consultar qualidade de dados e evidências mínimas" },
  { key: PermissionKeys.DATA_QUALITY_RESOLVE, description: "Tratar ocorrências de qualidade dentro do escopo" },
  { key: PermissionKeys.DATA_QUALITY_MANAGE, description: "Versionar e ativar regras de qualidade" },
  { key: PermissionKeys.DATA_QUALITY_MERGE, description: "Planejar e aplicar merge humano governado" },
  { key: PermissionKeys.DATA_QUALITY_ROLLBACK, description: "Reverter merge compatível com seu ledger" },
  { key: PermissionKeys.OPERATIONS_READ, description: "Consultar observabilidade operacional e SLOs" },
  { key: PermissionKeys.OPERATIONS_MANAGE, description: "Reconhecer alertas e conduzir incidentes" },
  { key: PermissionKeys.SECURITY_MONITOR_READ, description: "Consultar sinais agregados de segurança" },
  { key: PermissionKeys.PRIVACY_OPERATIONS_MANAGE, description: "Conduzir solicitações e retenção governada" },
  { key: PermissionKeys.METRICS_READ, description: "Consultar métricas" },
  {
    key: PermissionKeys.AUTOMATIONS_READ,
    description: "Consultar execuções de automações",
  },
  {
    key: PermissionKeys.AUTOMATIONS_EXECUTE,
    description: "Executar e reprocessar automações manualmente",
  },
  {
    key: PermissionKeys.AUTOMATIONS_MANAGE,
    description: "Ativar, pausar e cancelar automações",
  },
  { key: PermissionKeys.AUDIT_READ, description: "Consultar auditoria" },
  {
    key: PermissionKeys.AUDIT_MANAGE,
    description: "Reconhecer e resolver achados de processo",
  },
  {
    key: PermissionKeys.AI_USE,
    description: "Solicitar recomendações explicáveis de IA",
  },
  {
    key: PermissionKeys.AI_MANAGER_QUERY,
    description: "Consultar o Copilot gerencial com métricas autorizadas",
  },
  {
    key: PermissionKeys.AI_GOVERNANCE_READ,
    description: "Consultar versões, execuções, avaliações e decisões de IA",
  },
  {
    key: PermissionKeys.AI_GOVERNANCE_MANAGE,
    description: "Aprovar, desabilitar e restaurar versões governadas de IA",
  },
  {
    key: PermissionKeys.AI_EVALUATIONS_RUN,
    description: "Executar avaliações locais e determinísticas de IA",
  },
];
