-- CRM-39: local paid-media hierarchy, append-only facts and reconciliation.
CREATE TYPE "MarketingMediaStatus" AS ENUM ('ACTIVE','PAUSED','ARCHIVED','REVIEW_REQUIRED');
CREATE TYPE "MarketingPerformanceGranularity" AS ENUM ('HOURLY','DAILY','WEEKLY','MONTHLY');
CREATE TYPE "MarketingPerformanceFactStatus" AS ENUM ('CONFIRMED','VOIDED');
CREATE TYPE "MarketingImportMode" AS ENUM ('PREVIEW','CONFIRM','ROLLBACK');
CREATE TYPE "MarketingImportStatus" AS ENUM ('RUNNING','COMPLETED','PARTIAL','FAILED');
CREATE TYPE "MarketingImportItemOutcome" AS ENUM ('VALID','CREATED','SUPERSEDED','DUPLICATE','REJECTED','VOIDED');
CREATE TYPE "MarketingReconciliationStatus" AS ENUM ('RUNNING','COMPLETED','PARTIAL','FAILED');
CREATE TYPE "MarketingReconciliationIssueStatus" AS ENUM ('OPEN','ACKNOWLEDGED','RESOLVED');

CREATE TABLE "marketing_channels" ("id" UUID PRIMARY KEY,"workspaceId" UUID NOT NULL,"key" TEXT NOT NULL,"name" TEXT NOT NULL,"status" "MarketingMediaStatus" NOT NULL DEFAULT 'ACTIVE',"createdByActorId" UUID NOT NULL,"updatedByActorId" UUID NOT NULL,"createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMPTZ(3) NOT NULL,"deletedAt" TIMESTAMPTZ(3));
CREATE TABLE "marketing_ad_accounts" ("id" UUID PRIMARY KEY,"workspaceId" UUID NOT NULL,"channelId" UUID NOT NULL,"key" TEXT NOT NULL,"name" TEXT NOT NULL,"currency" TEXT NOT NULL DEFAULT 'BRL',"timeZone" TEXT NOT NULL DEFAULT 'America/Sao_Paulo',"status" "MarketingMediaStatus" NOT NULL DEFAULT 'ACTIVE',"createdByActorId" UUID NOT NULL,"updatedByActorId" UUID NOT NULL,"createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMPTZ(3) NOT NULL,"deletedAt" TIMESTAMPTZ(3));
CREATE TABLE "marketing_campaigns" ("id" UUID PRIMARY KEY,"workspaceId" UUID NOT NULL,"channelId" UUID NOT NULL,"adAccountId" UUID,"legacyAcquisitionCampaignId" UUID,"key" TEXT NOT NULL,"name" TEXT NOT NULL,"status" "MarketingMediaStatus" NOT NULL DEFAULT 'ACTIVE',"startsAt" TIMESTAMPTZ(3),"endsAt" TIMESTAMPTZ(3),"createdByActorId" UUID NOT NULL,"updatedByActorId" UUID NOT NULL,"createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMPTZ(3) NOT NULL,"deletedAt" TIMESTAMPTZ(3));
CREATE TABLE "marketing_ad_groups" ("id" UUID PRIMARY KEY,"workspaceId" UUID NOT NULL,"campaignId" UUID NOT NULL,"key" TEXT NOT NULL,"name" TEXT NOT NULL,"status" "MarketingMediaStatus" NOT NULL DEFAULT 'ACTIVE',"createdByActorId" UUID NOT NULL,"updatedByActorId" UUID NOT NULL,"createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMPTZ(3) NOT NULL,"deletedAt" TIMESTAMPTZ(3));
CREATE TABLE "marketing_ads" ("id" UUID PRIMARY KEY,"workspaceId" UUID NOT NULL,"adGroupId" UUID NOT NULL,"key" TEXT NOT NULL,"name" TEXT NOT NULL,"status" "MarketingMediaStatus" NOT NULL DEFAULT 'ACTIVE',"createdByActorId" UUID NOT NULL,"updatedByActorId" UUID NOT NULL,"createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMPTZ(3) NOT NULL,"deletedAt" TIMESTAMPTZ(3));
CREATE TABLE "marketing_creatives" ("id" UUID PRIMARY KEY,"workspaceId" UUID NOT NULL,"campaignId" UUID NOT NULL,"adId" UUID,"legacyAcquisitionCreativeId" UUID,"key" TEXT NOT NULL,"name" TEXT NOT NULL,"status" "MarketingMediaStatus" NOT NULL DEFAULT 'ACTIVE',"createdByActorId" UUID NOT NULL,"updatedByActorId" UUID NOT NULL,"createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMPTZ(3) NOT NULL,"deletedAt" TIMESTAMPTZ(3));
CREATE TABLE "marketing_performance_import_runs" ("id" UUID PRIMARY KEY,"workspaceId" UUID NOT NULL,"mode" "MarketingImportMode" NOT NULL,"status" "MarketingImportStatus" NOT NULL DEFAULT 'RUNNING',"sourceFileName" TEXT NOT NULL,"sourceContentHash" TEXT NOT NULL,"sourcePreviewRunId" UUID,"idempotencyKey" TEXT NOT NULL,"correlationId" TEXT NOT NULL,"rowCount" INTEGER NOT NULL DEFAULT 0,"validCount" INTEGER NOT NULL DEFAULT 0,"rejectedCount" INTEGER NOT NULL DEFAULT 0,"createdCount" INTEGER NOT NULL DEFAULT 0,"supersededCount" INTEGER NOT NULL DEFAULT 0,"requestedByActorId" UUID NOT NULL,"startedAt" TIMESTAMPTZ(3) NOT NULL,"finishedAt" TIMESTAMPTZ(3),"errorMessage" TEXT,"createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CHECK ("rowCount">=0 AND "validCount">=0 AND "rejectedCount">=0 AND "createdCount">=0 AND "supersededCount">=0));
CREATE TABLE "marketing_performance_facts" ("id" UUID PRIMARY KEY,"workspaceId" UUID NOT NULL,"importRunId" UUID NOT NULL,"channelId" UUID NOT NULL,"adAccountId" UUID,"campaignId" UUID,"adGroupId" UUID,"adId" UUID,"creativeId" UUID,"granularity" "MarketingPerformanceGranularity" NOT NULL,"grainKey" TEXT NOT NULL,"revision" INTEGER NOT NULL,"status" "MarketingPerformanceFactStatus" NOT NULL DEFAULT 'CONFIRMED',"supersedesFactId" UUID,"periodStart" TIMESTAMPTZ(3) NOT NULL,"periodEnd" TIMESTAMPTZ(3) NOT NULL,"timeZone" TEXT NOT NULL,"currency" TEXT NOT NULL,"spendCents" BIGINT NOT NULL,"impressions" BIGINT NOT NULL,"reach" BIGINT NOT NULL,"clicks" BIGINT NOT NULL,"linkClicks" BIGINT NOT NULL,"landingPageViews" BIGINT NOT NULL,"reportedLeads" BIGINT NOT NULL,"reportedPurchases" BIGINT NOT NULL,"reportedRevenueCents" BIGINT NOT NULL,"sourceRowNumber" INTEGER NOT NULL,"sourceEvidence" JSONB NOT NULL,"createdByActorId" UUID NOT NULL,"createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CHECK ("revision">0 AND "periodEnd">"periodStart" AND "spendCents">=0 AND "impressions">=0 AND "reach">=0 AND "clicks">=0 AND "linkClicks">=0 AND "landingPageViews">=0 AND "reportedLeads">=0 AND "reportedPurchases">=0 AND "reportedRevenueCents">=0));
CREATE TABLE "marketing_performance_import_items" ("id" UUID PRIMARY KEY,"workspaceId" UUID NOT NULL,"runId" UUID NOT NULL,"rowNumber" INTEGER NOT NULL,"outcome" "MarketingImportItemOutcome" NOT NULL,"factId" UUID,"reasonCode" TEXT,"normalizedRow" JSONB,"createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CHECK ("rowNumber">0));
CREATE TABLE "marketing_reconciliation_rule_versions" ("id" UUID PRIMARY KEY,"workspaceId" UUID NOT NULL,"version" INTEGER NOT NULL,"absoluteTolerance" INTEGER NOT NULL,"relativeToleranceBps" INTEGER NOT NULL,"configHash" TEXT NOT NULL,"reason" TEXT NOT NULL,"createdByActorId" UUID NOT NULL,"createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CHECK ("version">0 AND "absoluteTolerance">=0 AND "relativeToleranceBps" BETWEEN 0 AND 10000));
CREATE TABLE "marketing_reconciliation_runs" ("id" UUID PRIMARY KEY,"workspaceId" UUID NOT NULL,"ruleVersionId" UUID NOT NULL,"status" "MarketingReconciliationStatus" NOT NULL DEFAULT 'RUNNING',"periodStart" TIMESTAMPTZ(3) NOT NULL,"periodEnd" TIMESTAMPTZ(3) NOT NULL,"idempotencyKey" TEXT NOT NULL,"issueCount" INTEGER NOT NULL DEFAULT 0,"requestedByActorId" UUID NOT NULL,"startedAt" TIMESTAMPTZ(3) NOT NULL,"finishedAt" TIMESTAMPTZ(3),"createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CHECK ("periodEnd">"periodStart" AND "issueCount">=0));
CREATE TABLE "marketing_reconciliation_issues" ("id" UUID PRIMARY KEY,"workspaceId" UUID NOT NULL,"runId" UUID NOT NULL,"campaignId" UUID,"creativeId" UUID,"issueCode" TEXT NOT NULL,"severity" TEXT NOT NULL,"status" "MarketingReconciliationIssueStatus" NOT NULL DEFAULT 'OPEN',"mediaValue" BIGINT NOT NULL,"crmValue" BIGINT NOT NULL,"absoluteDifference" BIGINT NOT NULL,"relativeDifferenceBps" INTEGER,"evidence" JSONB NOT NULL,"acknowledgedAt" TIMESTAMPTZ(3),"acknowledgedByActorId" UUID,"resolvedAt" TIMESTAMPTZ(3),"resolvedByActorId" UUID,"resolutionReason" TEXT,"createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CHECK ("mediaValue">=0 AND "crmValue">=0 AND "absoluteDifference">=0));
CREATE TABLE "marketing_hierarchy_backfill_runs" ("id" UUID PRIMARY KEY,"workspaceId" UUID NOT NULL,"mode" "MarketingBackfillMode" NOT NULL,"status" "MarketingBackfillStatus" NOT NULL DEFAULT 'PENDING',"ruleVersion" TEXT NOT NULL,"candidateCount" INTEGER NOT NULL DEFAULT 0,"createdCount" INTEGER NOT NULL DEFAULT 0,"existingCount" INTEGER NOT NULL DEFAULT 0,"divergentCount" INTEGER NOT NULL DEFAULT 0,"idempotencyKey" TEXT NOT NULL,"requestedByActorId" UUID NOT NULL,"startedAt" TIMESTAMPTZ(3),"finishedAt" TIMESTAMPTZ(3),"createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE UNIQUE INDEX "marketing_channels_workspace_id" ON "marketing_channels"("workspaceId","id"); CREATE UNIQUE INDEX "marketing_channels_workspace_key" ON "marketing_channels"("workspaceId","key");
CREATE UNIQUE INDEX "marketing_ad_accounts_workspace_id" ON "marketing_ad_accounts"("workspaceId","id"); CREATE UNIQUE INDEX "marketing_ad_accounts_workspace_channel_key" ON "marketing_ad_accounts"("workspaceId","channelId","key");
CREATE UNIQUE INDEX "marketing_campaigns_workspace_id" ON "marketing_campaigns"("workspaceId","id"); CREATE UNIQUE INDEX "marketing_campaigns_workspace_channel_key" ON "marketing_campaigns"("workspaceId","channelId","key"); CREATE UNIQUE INDEX "marketing_campaigns_workspace_legacy" ON "marketing_campaigns"("workspaceId","legacyAcquisitionCampaignId");
CREATE UNIQUE INDEX "marketing_ad_groups_workspace_id" ON "marketing_ad_groups"("workspaceId","id"); CREATE UNIQUE INDEX "marketing_ad_groups_workspace_campaign_key" ON "marketing_ad_groups"("workspaceId","campaignId","key");
CREATE UNIQUE INDEX "marketing_ads_workspace_id" ON "marketing_ads"("workspaceId","id"); CREATE UNIQUE INDEX "marketing_ads_workspace_group_key" ON "marketing_ads"("workspaceId","adGroupId","key");
CREATE UNIQUE INDEX "marketing_creatives_workspace_id" ON "marketing_creatives"("workspaceId","id"); CREATE UNIQUE INDEX "marketing_creatives_workspace_campaign_key" ON "marketing_creatives"("workspaceId","campaignId","key"); CREATE UNIQUE INDEX "marketing_creatives_workspace_legacy" ON "marketing_creatives"("workspaceId","legacyAcquisitionCreativeId");
CREATE UNIQUE INDEX "marketing_import_runs_workspace_id" ON "marketing_performance_import_runs"("workspaceId","id"); CREATE UNIQUE INDEX "marketing_import_runs_workspace_key" ON "marketing_performance_import_runs"("workspaceId","idempotencyKey"); CREATE INDEX "marketing_import_runs_workspace_status" ON "marketing_performance_import_runs"("workspaceId","status","createdAt");
CREATE UNIQUE INDEX "marketing_facts_workspace_id" ON "marketing_performance_facts"("workspaceId","id"); CREATE UNIQUE INDEX "marketing_facts_workspace_grain_revision" ON "marketing_performance_facts"("workspaceId","grainKey","revision"); CREATE INDEX "marketing_facts_workspace_period" ON "marketing_performance_facts"("workspaceId","periodStart","periodEnd","status"); CREATE INDEX "marketing_facts_workspace_dimensions" ON "marketing_performance_facts"("workspaceId","channelId","campaignId","creativeId","periodStart");
CREATE UNIQUE INDEX "marketing_import_items_workspace_row" ON "marketing_performance_import_items"("workspaceId","runId","rowNumber");
CREATE UNIQUE INDEX "marketing_reconciliation_rules_workspace_id" ON "marketing_reconciliation_rule_versions"("workspaceId","id"); CREATE UNIQUE INDEX "marketing_reconciliation_rules_workspace_version" ON "marketing_reconciliation_rule_versions"("workspaceId","version");
CREATE UNIQUE INDEX "marketing_reconciliation_runs_workspace_id" ON "marketing_reconciliation_runs"("workspaceId","id"); CREATE UNIQUE INDEX "marketing_reconciliation_runs_workspace_key" ON "marketing_reconciliation_runs"("workspaceId","idempotencyKey"); CREATE INDEX "marketing_reconciliation_issues_workspace_status" ON "marketing_reconciliation_issues"("workspaceId","status","severity","createdAt"); CREATE UNIQUE INDEX "marketing_hierarchy_backfill_workspace_key" ON "marketing_hierarchy_backfill_runs"("workspaceId","idempotencyKey");

ALTER TABLE "marketing_channels" ADD FOREIGN KEY ("workspaceId") REFERENCES "workspaces"("id") ON DELETE RESTRICT;
ALTER TABLE "marketing_ad_accounts" ADD FOREIGN KEY ("workspaceId","channelId") REFERENCES "marketing_channels"("workspaceId","id") ON DELETE RESTRICT;
ALTER TABLE "marketing_campaigns" ADD FOREIGN KEY ("workspaceId","channelId") REFERENCES "marketing_channels"("workspaceId","id") ON DELETE RESTRICT;
ALTER TABLE "marketing_campaigns" ADD FOREIGN KEY ("workspaceId","adAccountId") REFERENCES "marketing_ad_accounts"("workspaceId","id") ON DELETE RESTRICT;
ALTER TABLE "marketing_campaigns" ADD FOREIGN KEY ("workspaceId","legacyAcquisitionCampaignId") REFERENCES "acquisition_campaigns"("workspaceId","id") ON DELETE RESTRICT;
ALTER TABLE "marketing_ad_groups" ADD FOREIGN KEY ("workspaceId","campaignId") REFERENCES "marketing_campaigns"("workspaceId","id") ON DELETE RESTRICT;
ALTER TABLE "marketing_ads" ADD FOREIGN KEY ("workspaceId","adGroupId") REFERENCES "marketing_ad_groups"("workspaceId","id") ON DELETE RESTRICT;
ALTER TABLE "marketing_creatives" ADD FOREIGN KEY ("workspaceId","campaignId") REFERENCES "marketing_campaigns"("workspaceId","id") ON DELETE RESTRICT;
ALTER TABLE "marketing_creatives" ADD FOREIGN KEY ("workspaceId","adId") REFERENCES "marketing_ads"("workspaceId","id") ON DELETE RESTRICT;
ALTER TABLE "marketing_creatives" ADD FOREIGN KEY ("workspaceId","legacyAcquisitionCreativeId") REFERENCES "acquisition_creatives"("workspaceId","id") ON DELETE RESTRICT;
ALTER TABLE "marketing_performance_import_runs" ADD FOREIGN KEY ("workspaceId","sourcePreviewRunId") REFERENCES "marketing_performance_import_runs"("workspaceId","id") ON DELETE RESTRICT;
ALTER TABLE "marketing_performance_facts" ADD FOREIGN KEY ("workspaceId","importRunId") REFERENCES "marketing_performance_import_runs"("workspaceId","id") ON DELETE RESTRICT;
ALTER TABLE "marketing_performance_facts" ADD FOREIGN KEY ("workspaceId","channelId") REFERENCES "marketing_channels"("workspaceId","id") ON DELETE RESTRICT;
ALTER TABLE "marketing_performance_facts" ADD FOREIGN KEY ("workspaceId","campaignId") REFERENCES "marketing_campaigns"("workspaceId","id") ON DELETE RESTRICT;
ALTER TABLE "marketing_performance_facts" ADD FOREIGN KEY ("workspaceId","creativeId") REFERENCES "marketing_creatives"("workspaceId","id") ON DELETE RESTRICT;
ALTER TABLE "marketing_performance_facts" ADD FOREIGN KEY ("workspaceId","supersedesFactId") REFERENCES "marketing_performance_facts"("workspaceId","id") ON DELETE RESTRICT;
ALTER TABLE "marketing_performance_import_items" ADD FOREIGN KEY ("workspaceId","runId") REFERENCES "marketing_performance_import_runs"("workspaceId","id") ON DELETE RESTRICT;
ALTER TABLE "marketing_performance_import_items" ADD FOREIGN KEY ("workspaceId","factId") REFERENCES "marketing_performance_facts"("workspaceId","id") ON DELETE RESTRICT;
ALTER TABLE "marketing_reconciliation_runs" ADD FOREIGN KEY ("workspaceId","ruleVersionId") REFERENCES "marketing_reconciliation_rule_versions"("workspaceId","id") ON DELETE RESTRICT;
ALTER TABLE "marketing_reconciliation_issues" ADD FOREIGN KEY ("workspaceId","runId") REFERENCES "marketing_reconciliation_runs"("workspaceId","id") ON DELETE RESTRICT;

CREATE OR REPLACE FUNCTION prevent_marketing_fact_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'marketing performance facts are append-only'; END $$;
CREATE TRIGGER marketing_facts_append_only BEFORE UPDATE OR DELETE ON "marketing_performance_facts" FOR EACH ROW EXECUTE FUNCTION prevent_marketing_fact_mutation();
