"use client";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/ui/empty-state";
import { StatusBadge } from "@/components/ui/status-badge";

type Milestone = Readonly<{ id:string; key:string; name:string; status:"PENDING"|"COMPLETED"|"SKIPPED"; required:boolean; dueAt:string; evidence:string|null; revision:number }>;
type Item = Readonly<{ id:string; accountId:string; ownerMemberId:string|null; teamId:string|null; queueId:string|null; state:"ACTIVE"|"PAUSED"|"ENDED"|"REVIEW_REQUIRED"; priority:number; nextActionDescription:string|null; nextActionAt:string|null; revision:number; account:Readonly<{id:string;name:string;segment:string;status:string}>; health:Readonly<{id:string;status:"HEALTHY"|"ATTENTION"|"RISK"|"INSUFFICIENT";score:number|null;explanation:string;missingSignalCount:number;cutoffAt:string}>|null; plan:(Readonly<{id:string;title:string;objective:string;status:"DRAFT"|"ACTIVE"|"BLOCKED"|"COMPLETED"|"CANCELLED";targetAt:string;nextActionDescription:string;nextActionAt:string;revision:number;blockedReason:string|null}> & {milestones:readonly Milestone[]})|null }>;
export type CustomerSuccessScreenView = Readonly<{generatedAt:string;timeZone:string;total:number;metrics:Readonly<{active:number;healthy:number;attention:number;risk:number;insufficient:number;overdue:number}>;formulas:Readonly<{overdue:string;health:string}>;items:readonly Item[];members:readonly Readonly<{id:string;name:string}>[];teams:readonly Readonly<{id:string;name:string}>[];queues:readonly Readonly<{id:string;name:string;teamId:string|null}>[];permissions:Readonly<{managePortfolio:boolean;managePlan:boolean;assessHealth:boolean;correct:boolean}>}>;
const inputClass="mt-1 w-full rounded-[var(--radius-control)] border bg-background px-3 py-2 text-sm";
const healthLabel={HEALTHY:"Saudável",ATTENTION:"Atenção",RISK:"Risco",INSUFFICIENT:"Dados insuficientes"} as const;
const healthTone={HEALTHY:"success",ATTENTION:"warning",RISK:"danger",INSUFFICIENT:"neutral"} as const;
const fmt=(value:string|null,tz:string)=>value?new Date(value).toLocaleString("pt-BR",{timeZone:tz,dateStyle:"short",timeStyle:"short"}):"Não definida";
const idem=(prefix:string)=>`${prefix}:${crypto.randomUUID()}`;
async function assertOk(response:Response){const body=await response.json().catch(()=>({})) as {error?:{message?:string}};if(!response.ok)throw new Error(body.error?.message??"Não foi possível concluir a operação.");}

export function CustomerSuccessWorkspace({screen}:Readonly<{screen:CustomerSuccessScreenView}>){
 const router=useRouter(); const [pending,setPending]=useState(false); const [notice,setNotice]=useState<{kind:"success"|"error";message:string}|null>(null);
 async function run(call:()=>Promise<Response>,message:string){setPending(true);setNotice(null);try{await assertOk(await call());setNotice({kind:"success",message});router.refresh();}catch(error){setNotice({kind:"error",message:error instanceof Error?error.message:"Falha inesperada."});}finally{setPending(false);}}
 async function reassign(event:FormEvent<HTMLFormElement>,item:Item){event.preventDefault();const form=new FormData(event.currentTarget);const owner=String(form.get("ownerMemberId")??"");await run(()=>fetch("/api/customer-success",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"ASSIGN_PORTFOLIO",payload:{accountId:item.accountId,ownerMemberId:owner||null,queueId:owner?null:String(form.get("queueId")||"")||null,teamId:String(form.get("teamId")||"")||null,priority:Number(form.get("priority")),nextActionDescription:String(form.get("nextActionDescription")),nextActionAt:String(form.get("nextActionAt")),reason:String(form.get("reason")),idempotencyKey:idem("portfolio")}})}),"Carteira reatribuída com histórico preservado.");}
 async function createPlan(event:FormEvent<HTMLFormElement>,item:Item){event.preventDefault();const form=new FormData(event.currentTarget);await run(()=>fetch("/api/customer-success",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"CREATE_PLAN",payload:{accountId:item.accountId,title:String(form.get("title")),objective:String(form.get("objective")),targetAt:String(form.get("targetAt")),nextActionDescription:String(form.get("nextActionDescription")),nextActionAt:String(form.get("nextActionAt")),reason:String(form.get("reason")),idempotencyKey:idem("plan")}})}),"Plano criado a partir da versão publicada.");}
 async function assess(item:Item){await run(()=>fetch("/api/customer-success",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"ASSESS_HEALTH",payload:{accountId:item.accountId,idempotencyKey:idem("health")}})}),"Saúde recalculada com evidências e ausência de dados separadas.");}
 async function actPlan(item:Item,action:string,milestone?:Milestone){const reason=window.prompt("Informe o motivo desta ação (mínimo de 8 caracteres).");if(!reason||reason.trim().length<8)return;const evidence=milestone?window.prompt("Registre a evidência observada."):undefined;if(milestone&&(!evidence||evidence.trim().length<3))return;const blockedReason=action==="BLOCK"?window.prompt("Descreva o bloqueio observado.")??undefined:undefined;await run(()=>fetch(`/api/customer-success/plans/${item.plan!.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,expectedRevision:milestone?.revision??item.plan!.revision,reason:reason.trim(),milestoneId:milestone?.id,evidence:evidence?.trim(),blockedReason,idempotencyKey:idem(`plan-${action.toLowerCase()}`)})}),"Plano atualizado com evento e auditoria.");}
 const metrics=[["Carteira ativa",screen.metrics.active,"?state=ACTIVE"],["Saudáveis",screen.metrics.healthy,"?health=HEALTHY"],["Atenção",screen.metrics.attention,"?health=ATTENTION"],["Em risco",screen.metrics.risk,"?health=RISK"],["Dados insuficientes",screen.metrics.insufficient,"?health=INSUFFICIENT"],["Ação vencida",screen.metrics.overdue,"?overdue=true"]] as const;
 return <div className="space-y-5">
  <section aria-label="Indicadores da carteira" className="grid gap-3 sm:grid-cols-3 xl:grid-cols-6">{metrics.map(([label,value,href])=><Link className="surface-panel p-4 transition-colors hover:bg-[var(--surface-subtle)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2" href={`/customer-success${href}`} key={label}><p className="text-sm text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-bold tabular-nums">{value}</p><span className="text-xs text-muted-foreground">Abrir registros</span></Link>)}</section>
  {notice?<p className={notice.kind==="error"?"feedback feedback-error":"feedback feedback-success"} role={notice.kind==="error"?"alert":"status"}>{notice.message}</p>:null}
  {screen.items.length===0?<EmptyState title="Nenhuma conta na carteira" description="Execute o backfill governado ou atribua uma conta autorizada; nenhum responsável será inferido."/>:<section className="grid gap-4 xl:grid-cols-2">{screen.items.map(item=><article className="surface-panel p-5" key={item.id}>
   <header className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs text-muted-foreground">P{item.priority} · {item.account.segment}</p><h2 className="text-lg font-semibold">{item.account.name}</h2><p className="text-sm text-muted-foreground">Próxima ação: {item.nextActionDescription??"Ausente"} · {fmt(item.nextActionAt,screen.timeZone)}</p></div>{item.health?<StatusBadge tone={healthTone[item.health.status]}>{healthLabel[item.health.status]}{item.health.score===null?"":` · ${item.health.score}`}</StatusBadge>:<StatusBadge tone="neutral">Sem avaliação</StatusBadge>}</header>
   <div className="mt-4 rounded-[var(--radius-panel)] bg-[var(--surface-subtle)] p-4"><p className="font-medium">Saúde explicável</p><p className="mt-1 text-sm text-muted-foreground">{item.health?.explanation??"Nenhuma avaliação persistida."}</p>{item.health?.missingSignalCount?<p className="mt-2 text-sm text-amber-800">{item.health.missingSignalCount} sinal(is) obrigatório(s) ausente(s) ou vencido(s).</p>:null}{screen.permissions.assessHealth?<Button className="mt-3" disabled={pending} onClick={()=>assess(item)} size="sm" variant="secondary">Recalcular saúde</Button>:null}</div>
   {item.plan?<div className="mt-4"><div className="flex items-center justify-between gap-2"><div><p className="font-medium">{item.plan.title}</p><p className="text-sm text-muted-foreground">{item.plan.objective}</p></div><StatusBadge tone={item.plan.status==="BLOCKED"?"danger":"info"}>{item.plan.status}</StatusBadge></div><ol className="mt-3 space-y-2">{item.plan.milestones.map(m=><li className="flex items-center justify-between gap-3 border-b py-2" key={m.id}><span className="text-sm">{m.name}{m.required?" · obrigatório":""}<small className="block text-muted-foreground">{m.status==="COMPLETED"?`Evidência: ${m.evidence}`:`Prazo ${fmt(m.dueAt,screen.timeZone)}`}</small></span>{m.status!=="COMPLETED"&&screen.permissions.managePlan?<Button disabled={pending} onClick={()=>actPlan(item,"COMPLETE_MILESTONE",m)} size="sm" variant="secondary">Concluir</Button>:null}</li>)}</ol>{screen.permissions.managePlan?<div className="mt-3 flex flex-wrap gap-2">{item.plan.status==="DRAFT"?<Button disabled={pending} onClick={()=>actPlan(item,"ACTIVATE")} size="sm">Ativar</Button>:null}{item.plan.status==="ACTIVE"?<><Button disabled={pending} onClick={()=>actPlan(item,"COMPLETE")} size="sm">Concluir plano</Button><Button disabled={pending} onClick={()=>actPlan(item,"BLOCK")} size="sm" variant="secondary">Bloquear</Button></>:null}{item.plan.status==="BLOCKED"?<Button disabled={pending} onClick={()=>actPlan(item,"UNBLOCK")} size="sm">Retomar</Button>:null}</div>:null}</div>:screen.permissions.managePlan?<details className="mt-4"><summary className="cursor-pointer font-medium">Criar plano de sucesso</summary><form className="mt-3 grid gap-3" onSubmit={event=>createPlan(event,item)}><label className="text-sm">Título<input className={inputClass} defaultValue="Plano de resultado inicial" name="title" required/></label><label className="text-sm">Objetivo<textarea className={inputClass} defaultValue="Comprovar adoção e resultado observado com o cliente." minLength={8} name="objective" required/></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Meta até<input className={inputClass} name="targetAt" required type="datetime-local"/></label><label className="text-sm">Próxima ação em<input className={inputClass} name="nextActionAt" required type="datetime-local"/></label></div><label className="text-sm">Próxima ação<input className={inputClass} defaultValue="Confirmar objetivo de sucesso" name="nextActionDescription" required/></label><input name="reason" type="hidden" value="Plano criado explicitamente pelo responsável da carteira."/><Button disabled={pending} type="submit">Criar plano</Button></form></details>:null}
   {screen.permissions.managePortfolio?<details className="mt-4 border-t pt-3"><summary className="cursor-pointer text-sm font-medium">Reatribuir carteira</summary><form className="mt-3 grid gap-3 sm:grid-cols-2" onSubmit={event=>reassign(event,item)}><label className="text-sm">Responsável<select className={inputClass} defaultValue={item.ownerMemberId??""} name="ownerMemberId"><option value="">Usar fila</option>{screen.members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label className="text-sm">Fila<select className={inputClass} defaultValue={item.queueId??""} name="queueId"><option value="">Nenhuma</option>{screen.queues.map(q=><option key={q.id} value={q.id}>{q.name}</option>)}</select></label><label className="text-sm">Equipe<select className={inputClass} defaultValue={item.teamId??""} name="teamId"><option value="">Sem equipe</option>{screen.teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label className="text-sm">Prioridade<select className={inputClass} defaultValue={item.priority} name="priority"><option value="1">P1</option><option value="2">P2</option><option value="3">P3</option></select></label><label className="text-sm sm:col-span-2">Próxima ação<input className={inputClass} defaultValue={item.nextActionDescription??""} name="nextActionDescription" required/></label><label className="text-sm">Prazo<input className={inputClass} name="nextActionAt" required type="datetime-local"/></label><label className="text-sm">Motivo<input className={inputClass} minLength={8} name="reason" required/></label><Button disabled={pending} type="submit">Confirmar reatribuição</Button></form></details>:null}
  </article>)}</section>}
  <p className="helper-text">Atualizado em {fmt(screen.generatedAt,screen.timeZone)}. Saúde: {screen.formulas.health}. Atraso: {screen.formulas.overdue}.</p>
 </div>;
}
