"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState, type FormEvent, type ReactNode } from "react";

import { AccessibleDialog } from "@/components/ui/accessible-dialog";
import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/ui/empty-state";
import { Icon } from "@/components/ui/icon";
import { StatusBadge } from "@/components/ui/status-badge";
import styles from "./finance-workspace.module.css";

export type FinanceSection = "dashboard" | "lancamentos" | "entradas" | "despesas" | "fluxo-caixa" | "dre" | "contas" | "pagar-receber" | "comissoes" | "categorias";
export type FinanceScreenView = Readonly<Record<string, unknown>>;

type Row = Record<string, unknown>;
type DialogKind = "entry" | "account" | "category" | "commission" | null;

const tabs: readonly Readonly<{ id: FinanceSection; label: string }>[] = [
  { id: "dashboard", label: "Dashboard" }, { id: "lancamentos", label: "Lançamentos" }, { id: "entradas", label: "Entradas" },
  { id: "despesas", label: "Despesas" }, { id: "fluxo-caixa", label: "Fluxo de Caixa" }, { id: "dre", label: "DRE" },
  { id: "contas", label: "Contas" }, { id: "pagar-receber", label: "A Pagar / Receber" }, { id: "comissoes", label: "Comissões" }, { id: "categorias", label: "Categorias" },
];
const monthNames = ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"];

function object(value: unknown): Row { return value && typeof value === "object" && !Array.isArray(value) ? value as Row : {}; }
function list(value: unknown): Row[] { return Array.isArray(value) ? value.filter((item): item is Row => Boolean(item) && typeof item === "object" && !Array.isArray(item)) : []; }
function pickList(source: Row, ...keys: string[]) { for (const key of keys) { const value = list(source[key]); if (value.length || Array.isArray(source[key])) return value; } return []; }
function text(value: unknown, fallback = "—") { return typeof value === "string" && value.trim() ? value : typeof value === "number" ? String(value) : fallback; }
function cents(value: unknown) { try { return typeof value === "bigint" ? value : BigInt(typeof value === "number" ? Math.round(value) : typeof value === "string" && /^-?\d+$/.test(value) ? value : "0"); } catch { return 0n; } }
function money(value: unknown) { const amount = cents(value); const abs = amount < 0n ? -amount : amount; return `${amount < 0n ? "−" : ""}R$ ${new Intl.NumberFormat("pt-BR").format(abs / 100n)},${(abs % 100n).toString().padStart(2, "0")}`; }
function date(value: unknown) { if (typeof value !== "string" && !(value instanceof Date)) return "—"; const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? "—" : new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeZone: "America/Sao_Paulo" }).format(parsed); }
function reaisToCents(value: FormDataEntryValue | null, allowZero = false) { const parsed = Number(String(value ?? "").trim().replace(/\./g, "").replace(",", ".")); if (!Number.isFinite(parsed) || parsed < 0 || (!allowZero && parsed === 0)) throw new Error(allowZero ? "Informe um valor monetário válido." : "Informe um valor maior que zero."); return String(Math.round(parsed * 100)); }
function apiMessage(body: unknown, fallback: string) { const root = object(body); const error = object(root.error); return text(error.message, fallback); }
function statusTone(status: string): "success" | "warning" | "danger" | "info" | "neutral" { if (["PAID", "RECEIVED", "SETTLED", "ACTIVE", "APPROVED"].includes(status)) return "success"; if (["OVERDUE", "REVERSED", "CANCELLED"].includes(status)) return "danger"; if (["PLANNED", "PENDING", "OPEN", "PARTIALLY_PAID", "DUE"].includes(status)) return "warning"; return "neutral"; }
function statusLabel(status: string) { return ({ PAID: "Pago", RECEIVED: "Recebido", SETTLED: "Liquidado", PLANNED: "Previsto", OPEN: "Em aberto", PENDING: "Pendente", OVERDUE: "Vencido", PARTIALLY_PAID: "Parcial", CANCELLED: "Cancelado", REVERSED: "Estornado", ACTIVE: "Ativa", APPROVED: "Aprovada", DRAFT: "Rascunho" } as Record<string, string>)[status] ?? status; }

function Panel({ title, description, action, children, className = "" }: Readonly<{ title: string; description?: string; action?: ReactNode; children: ReactNode; className?: string | undefined }>) {
  return <section className={`${styles.panel} ${className}`}><header className={styles.panelHeader}><div><h2>{title}</h2>{description ? <p>{description}</p> : null}</div>{action}</header>{children}</section>;
}

function MetricCard({ label, value, hint, tone = "neutral" }: Readonly<{ label: string; value: string; hint: string; tone?: string }>) {
  return <article className={styles.metric} data-tone={tone}><div><span>{label}</span><Icon name={tone === "positive" ? "tendencia" : tone === "negative" ? "alerta" : "receita"} size={15} /></div><strong>{value}</strong><small>{hint}</small></article>;
}

function EntryTable({ rows, empty, onSettle }: Readonly<{ rows: Row[]; empty: string; onSettle?: ((row: Row) => void) | undefined }>) {
  if (!rows.length) return <EmptyState compact title={empty} description="Os registros aparecerão aqui quando houver fatos no período selecionado." />;
  return <div className={styles.tableWrap}><table><thead><tr><th>Descrição</th><th>Cliente / fornecedor</th><th>Categoria</th><th>Competência</th><th>Vencimento</th><th>Status</th><th className={styles.number}>Valor</th>{onSettle ? <th>Ações</th> : null}</tr></thead><tbody>{rows.map((row, index) => { const status = text(row.status, "OPEN"); const canSettle = row.type === "MANUAL" && ["PLANNED", "OPEN", "PENDING", "PARTIALLY_PAID", "OVERDUE", "DUE"].includes(status); return <tr key={text(row.id, String(index))}><td><strong>{text(row.description ?? row.name)}</strong><small>{text(row.sourceLabel ?? row.source, "Manual")}</small></td><td>{text(row.counterparty ?? row.counterpartyName ?? row.accountName ?? row.customerName)}</td><td>{text(row.categoryName ?? row.category)}</td><td>{date(row.competenceAt ?? row.competenceDate ?? row.occurredAt)}</td><td>{date(row.dueAt ?? row.dueDate)}</td><td><StatusBadge tone={statusTone(status)}>{statusLabel(status)}</StatusBadge></td><td className={styles.number}>{money(row.amountCents ?? row.totalCents)}</td>{onSettle ? <td>{canSettle ? <Button onClick={() => onSettle(row)} size="sm" variant="secondary">Liquidar</Button> : "—"}</td> : null}</tr>; })}</tbody></table></div>;
}

export function FinanceWorkspace({ initialScreen, section, month, year }: Readonly<{ initialScreen: FinanceScreenView; section: FinanceSection; month: number; year: number }>) {
  const router = useRouter();
  const screen = object(initialScreen);
  const metrics = object(screen.metrics ?? screen.summary);
  const permissions = object(screen.permissions);
  const entries = pickList(screen, "entries", "launches", "transactions");
  const accounts = pickList(screen, "accounts", "financialAccounts");
  const categories = pickList(screen, "categories");
  const sellers = pickList(screen, "sellers", "members", "commissionSellers");
  const commissions = pickList(screen, "commissions");
  const cashFlow = pickList(screen, "cashFlow", "cashFlowSeries", "cashflow");
  const dre = pickList(screen, "dre", "dreLines", "incomeStatement");
  const [dialog, setDialog] = useState<DialogKind>(null);
  const [settling, setSettling] = useState<Row | null>(null);
  const [busy, setBusy] = useState(false);
  const [notice, setNotice] = useState<{ kind: "error" | "success"; message: string } | null>(null);
  const canManage = permissions.manage !== false && permissions.entriesManage !== false;
  const income = entries.filter((row) => text(row.direction ?? row.nature, "") === "INCOME");
  const expenses = entries.filter((row) => text(row.direction ?? row.nature, "") === "EXPENSE");
  const pending = entries.filter((row) => ["PLANNED", "OPEN", "PENDING", "PARTIALLY_PAID", "OVERDUE", "DUE"].includes(text(row.status, "")));
  const href = (id: FinanceSection) => `/financeiro?section=${id}&month=${month}&year=${year}`;
  const currentYear = new Date().getFullYear();

  async function command(payload: Record<string, unknown>, success: string) {
    setBusy(true); setNotice(null);
    try {
      const response = await fetch("/api/finance", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) });
      const body: unknown = await response.json().catch(() => null);
      if (!response.ok) throw new Error(apiMessage(body, "Não foi possível concluir a operação."));
      setNotice({ kind: "success", message: success }); setDialog(null); setSettling(null); router.refresh();
    } catch (error) { setNotice({ kind: "error", message: error instanceof Error ? error.message : "Falha inesperada." }); }
    finally { setBusy(false); }
  }

  function submitEntry(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); void command({ action: "CREATE_ENTRY", direction: data.get("direction"), status: "PLANNED", description: data.get("description"), counterparty: data.get("counterparty") || null, amountCents: reaisToCents(data.get("amount")), competenceAt: data.get("competenceAt"), dueAt: data.get("dueAt"), settledAt: null, categoryId: data.get("categoryId"), financialAccountId: data.get("financialAccountId"), customerAccountId: null, idempotencyKey: `finance-entry-ui:${crypto.randomUUID()}` }, "Lançamento criado com sucesso."); }
  function submitAccount(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); void command({ action: "CREATE_ACCOUNT", name: data.get("name"), type: data.get("type"), openingBalanceCents: reaisToCents(data.get("openingBalance"), true) }, "Conta criada com sucesso."); }
  function submitCategory(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); void command({ action: "CREATE_CATEGORY", name: data.get("name"), key: data.get("key"), kind: data.get("kind"), dreGroup: data.get("dreGroup") || null }, "Categoria criada com sucesso."); }
  function submitCommission(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); void command({ action: "CREATE_COMMISSION_RULE", sellerMemberId: data.get("sellerMemberId"), percentageBps: Number(data.get("percentageBps")), effectiveFrom: data.get("effectiveFrom") }, "Regra de comissão criada com sucesso."); }
  function submitSettlement(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!settling) return; const data = new FormData(event.currentTarget); void command({ action: "SETTLE_ENTRY", entryId: settling.id, status: "SETTLED", settledAt: data.get("settledAt"), expectedRevision: Number(settling.revision ?? 1) }, "Liquidação registrada com sucesso."); }

  const dashboardMetrics = [
    ["Caixa total atual", metrics.cashBalanceCents ?? metrics.currentCashCents, "Saldo conciliado", "neutral"],
    ["Entradas do mês", metrics.incomeCents ?? metrics.inflowsCents, "Recebimentos confirmados", "positive"],
    ["Saídas do mês", metrics.expenseCents ?? metrics.outflowsCents, "Pagamentos confirmados", "negative"],
    ["Resultado do mês", metrics.resultCents ?? metrics.netCashCents, "Entradas menos saídas", cents(metrics.resultCents ?? metrics.netCashCents) >= 0n ? "positive" : "negative"],
    ["Total gasto", metrics.totalExpenseCents ?? metrics.expenseCents, "Por competência", "negative"],
    ["Comissões", metrics.commissionCents ?? metrics.commissionsCents, "Geradas e pagas", "neutral"],
  ] as const;

  return <div className={styles.workspace}>
    <header className={styles.hero}><div><p>Gestão financeira</p><h1>Financeiro</h1><span>Caixa, resultados, recebimentos e comissões conectados ao CRM.</span></div><div><small>Atualizado em</small><strong>{date(screen.generatedAt ?? new Date().toISOString())}</strong></div></header>
    <nav aria-label="Seções do financeiro" className={styles.tabs}>{tabs.map((tab) => <Link aria-current={section === tab.id ? "page" : undefined} href={href(tab.id)} key={tab.id}>{tab.label}</Link>)}</nav>
    <form className={styles.period} method="get"><input name="section" type="hidden" value={section}/><select aria-label="Mês" defaultValue={month} name="month">{monthNames.map((label, index) => <option key={label} value={index + 1}>{label}</option>)}</select><select aria-label="Ano" defaultValue={year} name="year">{Array.from({ length: 7 }, (_, index) => currentYear - 3 + index).map((value) => <option key={value}>{value}</option>)}</select><Button size="sm" type="submit" variant="secondary">Atualizar</Button>{canManage ? <Button onClick={() => setDialog("entry")} size="sm" type="button"><Icon name="mais" size={14}/> Novo lançamento</Button> : null}</form>
    {notice ? <p className={notice.kind === "error" ? styles.error : styles.success} role={notice.kind === "error" ? "alert" : "status"}>{notice.message}</p> : null}

    {section === "dashboard" ? <Dashboard metrics={metrics} cards={dashboardMetrics} cashFlow={cashFlow} expenses={expenses} href={href} /> : null}
    {section === "lancamentos" ? <Panel title="Todos os lançamentos" description={`${entries.length} registros no período`}><EntryTable empty="Nenhum lançamento encontrado" onSettle={canManage ? setSettling : undefined} rows={entries}/></Panel> : null}
    {section === "entradas" ? <Panel title="Entradas" description="Receitas previstas e recebimentos confirmados" action={canManage ? <Button onClick={() => setDialog("entry")} size="sm">Nova entrada</Button> : null}><EntryTable empty="Nenhuma entrada no período" onSettle={canManage ? setSettling : undefined} rows={income}/></Panel> : null}
    {section === "despesas" ? <Panel title="Despesas" description="Custos, despesas recorrentes e pagamentos" action={canManage ? <Button onClick={() => setDialog("entry")} size="sm">Nova despesa</Button> : null}><EntryTable empty="Nenhuma despesa no período" onSettle={canManage ? setSettling : undefined} rows={expenses}/></Panel> : null}
    {section === "fluxo-caixa" ? <CashFlow rows={cashFlow} metrics={metrics}/> : null}
    {section === "dre" ? <Dre rows={dre} metrics={metrics}/> : null}
    {section === "contas" ? <Accounts rows={accounts} canManage={canManage} onCreate={() => setDialog("account")}/> : null}
    {section === "pagar-receber" ? <PayablesReceivables rows={pending} canManage={canManage} onSettle={setSettling}/> : null}
    {section === "comissoes" ? <Commissions rows={commissions} metrics={metrics} canManage={permissions.commissionsManage !== false} onCreate={() => setDialog("commission")} command={command}/> : null}
    {section === "categorias" ? <Categories rows={categories} canManage={canManage} onCreate={() => setDialog("category")}/> : null}

    {dialog ? <FinanceDialog accounts={accounts} busy={busy} categories={categories} kind={dialog} onDismiss={() => setDialog(null)} onEntry={submitEntry} onAccount={submitAccount} onCategory={submitCategory} onCommission={submitCommission} sellers={sellers}/> : null}
    {settling ? <SettlementDialog busy={busy} entry={settling} onDismiss={() => setSettling(null)} onSubmit={submitSettlement}/> : null}
  </div>;
}

function Dashboard({ metrics, cards, cashFlow, expenses, href }: Readonly<{ metrics: Row; cards: readonly (readonly [string, unknown, string, string])[]; cashFlow: Row[]; expenses: Row[]; href: (id: FinanceSection) => string }>) {
  const result = cents(metrics.resultCents ?? metrics.netCashCents);
  return <><div className={result >= 0n ? styles.positiveBanner : styles.negativeBanner}><Icon name="tendencia" size={20}/><div><strong>{result >= 0n ? "Saúde positiva" : "Atenção ao caixa"}</strong><span>Resultado {money(result)} · margem {text(metrics.marginPercent ?? metrics.margin, "indisponível")}</span></div></div>
    {text(metrics.alert, "") ? <p className={styles.alert}><Icon name="alerta" size={15}/>{text(metrics.alert, "")}</p> : null}
    <section aria-label="Resumo financeiro" className={styles.metrics}>{cards.map(([label, value, hint, tone]) => <MetricCard hint={hint} key={label} label={label} tone={tone} value={money(value)}/>)}</section>
    <div className={styles.openGrid}><Link href={href("pagar-receber")}><span>Contas a pagar em aberto</span><strong data-negative>{money(metrics.payableOpenCents)}</strong><small>Ver detalhes →</small></Link><Link href={href("pagar-receber")}><span>Contas a receber em aberto</span><strong data-positive>{money(metrics.receivableOpenCents)}</strong><small>Ver detalhes →</small></Link><Panel className={styles.projection} title="Fluxo projetado · 30 dias"><MiniLine rows={cashFlow}/><small>Saldo projetado {money(metrics.projectedCashCents)}</small></Panel></div>
    <div className={styles.chartGrid}><Panel title="Receitas vs despesas" description="Últimos movimentos do período"><CashBars rows={cashFlow}/></Panel><Panel title="Distribuição de despesas" description="Participação por categoria"><ExpenseDistribution rows={expenses}/></Panel></div></>;
}

function CashBars({ rows }: Readonly<{ rows: Row[] }>) { if (!rows.length) return <EmptyState compact title="Sem série de caixa" description="A série aparecerá após os primeiros lançamentos liquidados."/>; const max = rows.reduce((value, row) => { const next = Number(cents(row.incomeCents ?? row.inflowCents) + cents(row.expenseCents ?? row.outflowCents)); return Math.max(value, next); }, 1); return <div className={styles.bars}>{rows.slice(-12).map((row, index) => <div key={text(row.bucket ?? row.date, String(index))}><div><i style={{ height: `${Math.max(2, Number(cents(row.incomeCents ?? row.inflowCents)) / max * 100)}%` }}/><i data-expense style={{ height: `${Math.max(2, Number(cents(row.expenseCents ?? row.outflowCents)) / max * 100)}%` }}/></div><small>{text(row.label ?? row.bucket ?? row.date)}</small></div>)}</div>; }
function MiniLine({ rows }: Readonly<{ rows: Row[] }>) { const values = rows.slice(-20).map((row) => Number(cents(row.balanceCents ?? row.projectedBalanceCents))); if (!values.length) return <div className={styles.lineEmpty}/>; const min = Math.min(...values), max = Math.max(...values), span = max - min || 1; const points = values.map((value, index) => `${index / Math.max(1, values.length - 1) * 100},${45 - (value - min) / span * 38}`).join(" "); return <svg aria-label="Evolução do saldo projetado" className={styles.miniLine} role="img" viewBox="0 0 100 50" preserveAspectRatio="none"><polyline fill="none" points={points} stroke="currentColor" strokeWidth="2" vectorEffect="non-scaling-stroke"/></svg>; }
function ExpenseDistribution({ rows }: Readonly<{ rows: Row[] }>) { const grouped = new Map<string, bigint>(); for (const row of rows) { const key = text(row.categoryName ?? row.category, "Sem categoria"); grouped.set(key, (grouped.get(key) ?? 0n) + cents(row.amountCents)); } const values = [...grouped].sort((a,b) => Number(b[1]-a[1])).slice(0,6); const total = values.reduce((sum, item) => sum + item[1], 0n); if (!values.length) return <EmptyState compact title="Sem despesas" description="A distribuição será calculada por categoria."/>; return <ul className={styles.distribution}>{values.map(([label,value]) => <li key={label}><span>{label}</span><progress max={Number(total || 1n)} value={Number(value)}/><strong>{money(value)}</strong></li>)}</ul>; }
function CashFlow({ rows, metrics }: Readonly<{ rows: Row[]; metrics: Row }>) { return <><section className={styles.metrics}><MetricCard label="Saldo inicial" value={money(metrics.openingBalanceCents)} hint="Início do período"/><MetricCard label="Entradas realizadas" value={money(metrics.inflowsCents ?? metrics.incomeCents)} hint="Caixa confirmado" tone="positive"/><MetricCard label="Saídas realizadas" value={money(metrics.outflowsCents ?? metrics.expenseCents)} hint="Caixa confirmado" tone="negative"/><MetricCard label="Saldo final" value={money(metrics.closingBalanceCents ?? metrics.cashBalanceCents)} hint="Fechamento projetado"/></section><Panel title="Fluxo realizado e projetado" description="Caixa por data efetiva de liquidação"><CashBars rows={rows}/>{rows.length ? <div className={styles.tableWrap}><table><thead><tr><th>Período</th><th>Entradas</th><th>Saídas</th><th>Saldo</th></tr></thead><tbody>{rows.map((row,index) => <tr key={text(row.bucket ?? row.date,String(index))}><td>{text(row.label ?? row.bucket ?? row.date)}</td><td>{money(row.incomeCents ?? row.inflowCents)}</td><td>{money(row.expenseCents ?? row.outflowCents)}</td><td>{money(row.balanceCents ?? row.projectedBalanceCents)}</td></tr>)}</tbody></table></div> : null}</Panel></>; }
function Dre({ rows, metrics }: Readonly<{ rows: Row[]; metrics: Row }>) { return <><p className={styles.info}>DRE gerencial por competência. Recebimentos e pagamentos pertencem ao fluxo de caixa.</p><Panel title="Demonstrativo de Resultado" description="Valores classificados pelas categorias do período">{rows.length ? <div className={styles.dre}>{rows.map((row,index) => <div data-total={row.total === true || undefined} key={text(row.id ?? row.categoryId ?? row.code,String(index))}><span>{text(row.label ?? row.name ?? row.category)}</span><strong>{money(row.amountCents ?? row.valueCents ?? row.resultCents)}</strong></div>)}</div> : <EmptyState compact title="DRE indisponível" description="Classifique receitas e despesas para formar o demonstrativo."/>}</Panel><section className={styles.metrics}><MetricCard label="Receita líquida" value={money(metrics.netRevenueCents ?? metrics.incomeCents)} hint="Competência" tone="positive"/><MetricCard label="Margem bruta" value={money(metrics.grossProfitCents ?? metrics.resultCents)} hint="Após custos diretos"/><MetricCard label="Resultado líquido" value={money(metrics.netIncomeCents ?? metrics.resultCents)} hint="Fechamento gerencial" tone={cents(metrics.netIncomeCents ?? metrics.resultCents)>=0n?"positive":"negative"}/></section></>; }
function Accounts({ rows, canManage, onCreate }: Readonly<{ rows: Row[]; canManage: boolean; onCreate: () => void }>) { return <Panel title="Contas financeiras" description="Bancos, carteiras e caixas usados nas liquidações" action={canManage ? <Button onClick={onCreate} size="sm">Nova conta</Button> : null}>{rows.length ? <div className={styles.accountGrid}>{rows.map((row,index) => <article key={text(row.id,String(index))}><div><Icon name="receita" size={18}/><StatusBadge tone={text(row.status,"ACTIVE") === "ACTIVE" ? "success" : "neutral"}>{statusLabel(text(row.status,"ACTIVE"))}</StatusBadge></div><span>{text(row.type,"Conta")}</span><h3>{text(row.name)}</h3><strong>{money(row.balanceCents ?? row.currentBalanceCents)}</strong><small>Saldo disponível</small></article>)}</div> : <EmptyState compact title="Nenhuma conta cadastrada" description="Crie uma conta para registrar entradas e saídas de caixa."/>}</Panel>; }
function PayablesReceivables({ rows, canManage, onSettle }: Readonly<{ rows: Row[]; canManage: boolean; onSettle: (row: Row) => void }>) { const receivable = rows.filter((row) => text(row.direction ?? row.nature, "") === "INCOME"); const payable = rows.filter((row) => text(row.direction ?? row.nature, "") === "EXPENSE"); return <div className={styles.twoColumns}><Panel title="Contas a receber" description={`${receivable.length} títulos em aberto`}><EntryTable empty="Nada a receber" onSettle={canManage ? onSettle : undefined} rows={receivable}/></Panel><Panel title="Contas a pagar" description={`${payable.length} títulos em aberto`}><EntryTable empty="Nada a pagar" onSettle={canManage ? onSettle : undefined} rows={payable}/></Panel></div>; }
function Commissions({ rows, metrics, canManage, onCreate, command }: Readonly<{ rows: Row[]; metrics: Row; canManage: boolean; onCreate: () => void; command: (payload: Record<string, unknown>, success: string) => Promise<void> }>) { return <><section className={styles.metrics}><MetricCard label="Geradas" value={money(metrics.commissionGeneratedCents ?? metrics.commissionCents)} hint="No período"/><MetricCard label="Pendentes" value={money(metrics.commissionPendingCents)} hint="Aguardando aprovação" tone="negative"/><MetricCard label="Pagas" value={money(metrics.commissionPaidCents)} hint="Caixa realizado" tone="positive"/></section><Panel title="Comissões por venda" description="Regra, base e vendedor preservados em cada cálculo" action={canManage ? <div className={styles.inlineActions}><Button onClick={() => void command({ action: "RECONCILE_COMMISSIONS" }, "Comissões conciliadas com as vendas ganhas.")} size="sm" variant="secondary">Conciliar vendas</Button><Button onClick={onCreate} size="sm">Nova regra</Button></div> : null}>{rows.length ? <div className={styles.tableWrap}><table><thead><tr><th>Vendedor</th><th>Venda</th><th>Percentual</th><th>Base</th><th>Status</th><th>Comissão</th><th>Ações</th></tr></thead><tbody>{rows.map((row,index) => { const status=text(row.status,"PENDING"); const next = status === "PENDING" ? "APPROVED" : status === "APPROVED" ? "PAID" : null; return <tr key={text(row.id,String(index))}><td>{text(row.memberName ?? row.sellerName)}</td><td>{text(row.opportunityId)}</td><td>{text(row.percentageBps, "0")} bps</td><td>{money(row.basisCents)}</td><td><StatusBadge tone={statusTone(status)}>{statusLabel(status)}</StatusBadge></td><td>{money(row.amountCents)}</td><td>{canManage && next ? <Button onClick={() => void command({ action:"UPDATE_COMMISSION", commissionId:row.id, status:next, expectedRevision:Number(row.revision ?? 1) }, next === "APPROVED" ? "Comissão aprovada." : "Comissão marcada como paga.")} size="sm" variant="secondary">{next === "APPROVED" ? "Aprovar" : "Marcar paga"}</Button> : "—"}</td></tr>; })}</tbody></table></div> : <EmptyState compact title="Nenhuma comissão calculada" description="Crie uma regra e concilie as vendas ganhas para calcular as comissões."/>}</Panel></>; }
function Categories({ rows, canManage, onCreate }: Readonly<{ rows: Row[]; canManage: boolean; onCreate: () => void }>) { return <Panel title="Categorias financeiras" description="Classificação das receitas, despesas e linhas da DRE" action={canManage ? <Button onClick={onCreate} size="sm">Nova categoria</Button> : null}>{rows.length ? <div className={styles.tableWrap}><table><thead><tr><th>Categoria</th><th>Código</th><th>Natureza</th><th>Grupo DRE</th><th>Status</th></tr></thead><tbody>{rows.map((row,index) => <tr key={text(row.id,String(index))}><td><strong>{text(row.name)}</strong><small>{text(row.parentName, "Categoria principal")}</small></td><td>{text(row.code)}</td><td>{text(row.nature)}</td><td>{text(row.dreGroup)}</td><td><StatusBadge tone={row.active === false ? "neutral" : "success"}>{row.active === false ? "Arquivada" : "Ativa"}</StatusBadge></td></tr>)}</tbody></table></div> : <EmptyState compact title="Nenhuma categoria cadastrada" description="Crie categorias para organizar o caixa e formar a DRE."/>}</Panel>; }

function FinanceDialog({ kind, busy, accounts, categories, sellers, onDismiss, onEntry, onAccount, onCategory, onCommission }: Readonly<{ kind: Exclude<DialogKind,null>; busy:boolean; accounts:Row[]; categories:Row[]; sellers:Row[]; onDismiss:()=>void; onEntry:(event:FormEvent<HTMLFormElement>)=>void; onAccount:(event:FormEvent<HTMLFormElement>)=>void; onCategory:(event:FormEvent<HTMLFormElement>)=>void; onCommission:(event:FormEvent<HTMLFormElement>)=>void }>) {
  const title = { entry:"Novo lançamento", account:"Nova conta financeira", category:"Nova categoria", commission:"Nova regra de comissão" }[kind]; const submit = { entry:onEntry, account:onAccount, category:onCategory, commission:onCommission }[kind];
  return <AccessibleDialog busy={busy} labelledBy="finance-dialog-title" onDismiss={onDismiss}><h2 id="finance-dialog-title">{title}</h2><form className={styles.form} onSubmit={submit}>
    {kind === "entry" ? <><label>Natureza<select name="direction" required><option value="INCOME">Entrada</option><option value="EXPENSE">Despesa</option></select></label><label>Descrição<input name="description" required/></label><label>Valor (R$)<input inputMode="decimal" name="amount" placeholder="0,00" required/></label><label>Competência<input name="competenceAt" required type="date"/></label><label>Vencimento<input name="dueAt" required type="date"/></label><label>Categoria<select name="categoryId" required><option value="">Selecione</option>{categories.map((row,index)=><option key={text(row.id,String(index))} value={text(row.id,"")}>{text(row.name)}</option>)}</select></label><label>Conta<select name="financialAccountId" required><option value="">Selecione</option>{accounts.map((row,index)=><option key={text(row.id,String(index))} value={text(row.id,"")}>{text(row.name)}</option>)}</select></label><label>Cliente ou fornecedor<input name="counterparty"/></label></> : null}
    {kind === "account" ? <><label>Nome<input name="name" required/></label><label>Tipo<select name="type"><option value="BANK">Conta bancária</option><option value="CASH">Caixa</option><option value="OTHER">Outra</option></select></label><label>Saldo inicial (R$)<input defaultValue="0,00" inputMode="decimal" name="openingBalance" required/></label></> : null}
    {kind === "category" ? <><label>Nome<input name="name" required/></label><label>Chave<input name="key" pattern="[a-z][a-z0-9_]*" required/></label><label>Natureza<select name="kind"><option value="INCOME">Receita</option><option value="EXPENSE">Despesa</option></select></label><label>Grupo DRE<input name="dreGroup" placeholder="Ex.: Receita bruta"/></label></> : null}
    {kind === "commission" ? <><label>Vendedor<select name="sellerMemberId" required><option value="">Selecione</option>{sellers.map((row,index)=><option key={text(row.id,String(index))} value={text(row.id,"")}>{text(row.name ?? row.displayName)}</option>)}</select></label><label>Percentual (basis points)<input defaultValue="500" min="0" max="10000" name="percentageBps" required type="number"/></label><label>Vigência<input name="effectiveFrom" required type="date"/></label></> : null}
    <div className={styles.formActions}><Button disabled={busy} type="submit">{busy ? "Salvando…" : "Salvar"}</Button><Button disabled={busy} onClick={onDismiss} type="button" variant="secondary">Cancelar</Button></div></form></AccessibleDialog>;
}
function SettlementDialog({ entry, busy, onDismiss, onSubmit }: Readonly<{ entry:Row; busy:boolean; onDismiss:()=>void; onSubmit:(event:FormEvent<HTMLFormElement>)=>void }>) { return <AccessibleDialog busy={busy} labelledBy="settlement-dialog-title" onDismiss={onDismiss}><h2 id="settlement-dialog-title">Liquidar lançamento</h2><p className={styles.dialogIntro}>{text(entry.description)} · valor {money(entry.amountCents)}</p><form className={styles.form} onSubmit={onSubmit}><label>Data efetiva<input name="settledAt" required type="date"/></label><div className={styles.formActions}><Button disabled={busy} type="submit">{busy?"Registrando…":"Confirmar liquidação"}</Button><Button disabled={busy} onClick={onDismiss} type="button" variant="secondary">Cancelar</Button></div></form></AccessibleDialog>; }
