import Link from "next/link";

import type { getProspectingWorkspaceService } from "@/modules/prospecting/application/prospecting-workspace-service";
import styles from "@/app/email-agente/prospecting-workspace.module.css";
import { ProspectingSettingsActions } from "@/app/email-agente/prospecting-settings-actions";

export const prospectingViews = ["pipeline", "stock", "activities", "metrics"] as const;
export type ProspectingView = (typeof prospectingViews)[number];
type Screen = Awaited<ReturnType<ReturnType<typeof getProspectingWorkspaceService>["getScreen"]>>;

const viewLabels: Record<ProspectingView, string> = { pipeline: "Pipeline", stock: "Estoque", activities: "Atividades", metrics: "Métricas" };
const statusLabels: Record<string, string> = { RECEIVED: "Recebido", REVIEW_REQUIRED: "Revisão", READY: "Pronto", REJECTED: "Rejeitado", PLANNED: "Planejado", RELEASED: "Liberado", PENDING_D1: "Gate D1", ACTIVE: "Ativa", PAUSED: "Pausada", CONVERSATION_STARTED: "Conversa", MEETING_SCHEDULED: "Reunião", CLOSED_NO_RESPONSE: "Sem retorno", DISCARDED: "Descartada" };
const channelLabels: Readonly<Record<string, string>> = { CALL: "Ligação", INSTAGRAM_MESSAGE: "Mensagem no Instagram", INSTAGRAM_FOLLOW: "Seguir no Instagram" };
const resultLabels: Readonly<Record<string, string>> = { CONNECTED: "Conectou", CALLBACK_REQUESTED: "Pediu retorno", WHATSAPP_SHARED: "Passou contato/WhatsApp", NO_ANSWER: "Não atendeu", BUSY: "Ocupado", VOICEMAIL: "Caixa postal", WRONG_NUMBER: "Número incorreto", CHANNEL_UNAVAILABLE: "Canal indisponível", SENT: "Enviada", FAILED: "Falhou", PROFILE_NOT_FOUND: "Perfil não encontrado", COMPLETED: "Concluído", ALREADY_FOLLOWING: "Já seguia", SEM_RESULTADO: "Sem resultado" };
const emailDayLabels: Readonly<Record<string, string>> = { "email-1": "D0", "email-2": "D3", "email-3": "D7", "email-4": "D12", "email-5": "D18", "email-6": "D25" };

function date(value: string | null, timeZone: string) { return value ? new Intl.DateTimeFormat("pt-BR", { timeZone, dateStyle: "short", timeStyle: "short" }).format(new Date(value)) : "—"; }

export function ProspectingNav({ active }: Readonly<{ active: ProspectingView }>) {
  return <nav aria-label="Áreas da Prospecção Ativa" className={styles.tabs}>{prospectingViews.map((view) => <Link data-active={view === active} href={`/email-agente?view=${view}`} key={view}>{viewLabels[view]}</Link>)}</nav>;
}

export function ProspectingOverview({ screen }: Readonly<{ screen: Screen }>) {
  return <>
    <div className={styles.grid}>
      <article className={styles.card}><h2>Estoque pronto</h2><div className={styles.metric}>{screen.overview.stock.ready}</div><p>{screen.overview.stock.coverageDays} dias estimados de cobertura</p></article>
      <article className={styles.card}><h2>Liberações hoje</h2><div className={styles.metric}>{screen.overview.releasesToday}</div><p>Somente releases atômicos confirmados</p></article>
      <article className={styles.card}><h2>Políticos abordados</h2><div className={styles.metric}>{screen.overview.politiciansTouchedToday}</div><p>Cada político conta uma vez no dia local</p></article>
      <article className={styles.card}><h2>Leads na etapa reunião · 30 dias</h2><div className={styles.metric}>{screen.overview.meetingsThirtyDays}</div><p>Políticos distintos movidos para Reunião marcada no período</p></article>
    </div>
    <section className={styles.section}><div className={styles.sectionHeader}><div><h2>Pipeline operacional</h2><p>Sete etapas por chave estável.</p></div><Link className={styles.link} href="/email-agente?view=pipeline">Abrir pipeline</Link></div><div className={styles.stageBar}>{screen.overview.pipeline?.stages.map((stage) => <div className={styles.stage} key={stage.id}><strong>{stage.leads}</strong><span>{stage.name}</span></div>) ?? <p className={styles.empty}>Pipeline ainda não inicializado.</p>}</div></section>
    <section className={styles.section}><div className={styles.sectionHeader}><div><h2>Saúde e bloqueios</h2><p>Alertas derivados de fatos persistidos, sem expor PII.</p></div></div><div className={styles.alerts}>{screen.overview.alerts.length ? screen.overview.alerts.map((alert) => <article className={styles.alert} data-level={alert.level} key={alert.code}><strong>{alert.message}</strong><span>{alert.action}</span></article>) : <article className={styles.card}>Nenhum alerta operacional.</article>}</div></section>
    <section className={styles.section}><div className={styles.sectionHeader}><div><h2>Capacidade projetada</h2><p>Realizado, tarefas abertas e releases planejados por vendedor/data.</p></div><Link className={styles.link} href="/email-agente?view=metrics">Abrir métricas</Link></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Data</th><th>Vendedor</th><th>Realizado</th><th>Agendado</th><th>Planejado</th><th>Projeção</th></tr></thead><tbody>{screen.capacity.slice(0, 30).map((row) => <tr key={`${row.memberId}:${row.localDate}`}><td>{row.localDate}</td><td>{row.memberName}</td><td>{row.realized}</td><td>{row.scheduled}</td><td>{row.planned}</td><td><span className={styles.status}>{row.projected}/{row.limit}{row.overCapacity ? " · excesso" : ""}</span></td></tr>)}</tbody></table>{screen.capacity.length === 0 ? <p className={styles.empty}>Nenhuma carga projetada nos próximos 30 dias.</p> : null}</div></section>
    <section className={styles.section}><div className={styles.grid}><article className={styles.card}><h3>Open-Dot Pesquisa</h3><div className={styles.gate}><i className={styles.dot} data-ok={Boolean(screen.overview.lastResearch)} /><span>{screen.overview.lastResearch ? `Último contato ${date(screen.overview.lastResearch.receivedAt, screen.timeZone)}` : "Sem heartbeat recebido"}</span></div></article><article className={styles.card}><h3>Open-Dot E-mail</h3><div className={styles.gate}><i className={styles.dot} data-ok={Boolean(screen.overview.lastEmailClient)} /><span>{screen.overview.lastEmailClient ? `Último contato ${date(screen.overview.lastEmailClient.receivedAt, screen.timeZone)}` : "Sem heartbeat recebido"}</span></div></article></div></section>
  </>;
}

export function ProspectingStock({ screen }: Readonly<{ screen: Screen }>) {
  const pages = Math.max(1, Math.ceil(screen.stock.total / screen.stock.pageSize));
  return <>
    <section className={styles.card}><form className={styles.filters}><input name="view" type="hidden" value="stock" /><label>Status<select defaultValue={screen.stock.filters.status ?? ""} name="status"><option value="">Todos</option>{["RECEIVED","REVIEW_REQUIRED","READY","REJECTED","PLANNED","RELEASED"].map((value) => <option key={value} value={value}>{statusLabels[value] ?? value}</option>)}</select></label><label>Cargo<select defaultValue={screen.stock.filters.role ?? ""} name="role"><option value="">Todos</option><option value="MAYOR">Prefeito</option><option value="COUNCILOR">Vereador</option></select></label><label>UF<input defaultValue={screen.stock.filters.stateCode ?? ""} maxLength={2} name="stateCode" style={{border:"1px solid var(--border)",borderRadius:"var(--radius-control)",padding:".55rem",width:"5rem"}} /></label><button className={styles.button} type="submit">Filtrar</button></form></section>
    <section className={styles.section}><div className={styles.sectionHeader}><div><h2>Estoque anterior ao Lead</h2><p>{screen.stock.total} candidato(s) · página {screen.stock.page} de {pages}</p></div></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Político</th><th>Município</th><th>Status</th><th>Contatos verificados</th><th>Evidências</th><th>Liberação</th></tr></thead><tbody>{screen.stock.items.map((item) => <tr key={item.id}><td><strong>{item.politicianName}</strong><br />{item.role === "MAYOR" ? "Prefeito" : "Vereador"}</td><td>{item.municipalityName}/{item.stateCode}<br />{item.population.toLocaleString("pt-BR")} hab.</td><td><span className={styles.status}>{statusLabels[item.status] ?? item.status}</span><br />{item.reviewReasonCode ?? item.rejectionReasonCode ?? ""}</td><td>Gabinete: {item.phone ?? "Restrito"}<br />{item.normalizedEmail ?? "Restrito"}{item.politicianPhone || item.politicianEmail ? <><br />Político (público): {item.politicianPhone ?? "—"} · {item.politicianEmail ?? "—"}</> : null}{item.advisorPhone || item.advisorEmail ? <><br />Assessor: {item.advisorPhone ?? "—"} · {item.advisorEmail ?? "—"}</> : null}{item.whatsapp ? <><br />WhatsApp: {item.whatsapp} · {item.whatsappScope}</> : null}{item.instagram ? <><br />Instagram: {item.instagram} · {item.instagramScope}</> : null}</td><td>{item.sourceCount} fonte(s)<br />Mandato verificado {date(item.mandateVerifiedAt, screen.timeZone)}</td><td>{item.plannedReleaseDate ?? item.releasedAt?.slice(0,10) ?? "—"}{item.leadId ? <><br /><Link className={styles.link} href={`/leads/${item.leadId}/historico`}>Abrir card</Link></> : null}</td></tr>)}</tbody></table>{screen.stock.items.length === 0 ? <p className={styles.empty}>Nenhum candidato neste recorte.</p> : null}</div><div style={{display:"flex",justifyContent:"space-between",marginTop:".7rem"}}>{screen.stock.page > 1 ? <Link className={styles.link} href={`/email-agente?view=stock&page=${screen.stock.page-1}`}>Anterior</Link> : <span />}{screen.stock.page < pages ? <Link className={styles.link} href={`/email-agente?view=stock&page=${screen.stock.page+1}`}>Próxima</Link> : null}</div></section>
  </>;
}

export function ProspectingActivities({ screen }: Readonly<{ screen: Screen }>) {
  const pages = Math.max(1, Math.ceil(screen.activities.total / screen.activities.pageSize));
  return <section><div className={styles.sectionHeader}><div><h2>Atividades manuais da cadência</h2><p>As mesmas tarefas persistidas e priorizadas para cada vendedor no Meu Dia · página {screen.activities.page} de {pages}.</p></div><Link className={styles.link} href="/meu-dia">Abrir Meu Dia</Link></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Prazo</th><th>Político</th><th>Ação</th><th>Estado</th><th>Resultado</th></tr></thead><tbody>{screen.activities.items.map((task) => <tr key={task.id}><td>{date(task.dueAt, screen.timeZone)}</td><td><Link className={styles.link} href={`/leads/${task.leadId}/historico`}>{task.lead.fullName}</Link><br />{task.lead.jobTitle}</td><td>{task.title}<br />{task.kind}</td><td><span className={styles.status}>{task.status}</span></td><td>{task.result ?? "—"}</td></tr>)}</tbody></table>{screen.activities.items.length === 0 ? <p className={styles.empty}>Nenhuma atividade manual encontrada.</p> : null}</div><div style={{display:"flex",justifyContent:"space-between",marginTop:".7rem"}}>{screen.activities.page > 1 ? <Link className={styles.link} href={`/email-agente?view=activities&activityPage=${screen.activities.page-1}`}>Anterior</Link> : <span />}{screen.activities.page < pages ? <Link className={styles.link} href={`/email-agente?view=activities&activityPage=${screen.activities.page+1}`}>Próxima</Link> : null}</div></section>;
}

export function ProspectingEmails({ screen }: Readonly<{ screen: Screen }>) {
  const pages = Math.max(1, Math.ceil(screen.email.pagination.total / screen.email.pagination.pageSize));
  return <><div className={styles.sectionHeader}><div><h2>Ordens de e-mail</h2><p>O CRM agenda e autoriza; o Open-Dot executa após revalidação · página {screen.email.pagination.page} de {pages}.</p></div><Link className={styles.link} href="/inbox?channels=EMAIL">Abrir caixa de e-mail</Link></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Agendamento</th><th>Etapa</th><th>Status</th><th>Tentativas</th><th>Configuração</th></tr></thead><tbody>{screen.email.jobs.map((job) => <tr key={job.id}><td>{date(job.scheduledAt, screen.timeZone)}<br />Expira {date(job.expiresAt, screen.timeZone)}</td><td>{job.stepKey}</td><td><span className={styles.status}>{job.status}</span><br />{job.lastErrorCode}</td><td>{job.attemptCount}</td><td>{job.templateVersionId ? "Template ✓" : "Sem template"} · {job.senderProfileId ? "Remetente ✓" : "Sem remetente"}</td></tr>)}</tbody></table>{screen.email.jobs.length === 0 ? <p className={styles.empty}>Nenhuma ordem materializada.</p> : null}</div><div style={{display:"flex",justifyContent:"space-between",marginTop:".7rem"}}>{screen.email.pagination.page > 1 ? <Link className={styles.link} href={`/email-agente?view=emails&emailPage=${screen.email.pagination.page-1}`}>Anterior</Link> : <span />}{screen.email.pagination.page < pages ? <Link className={styles.link} href={`/email-agente?view=emails&emailPage=${screen.email.pagination.page+1}`}>Próxima</Link> : null}</div></>;
}

export function ProspectingMetrics({ screen }: Readonly<{ screen: Screen }>) {
  return <>
    <div className={styles.sectionHeader}><div><h2>Indicadores da Prospecção Ativa</h2><p>Ligações, envios, reuniões e resultados vêm do log comercial; a fila mostra as tarefas abertas.</p></div><div><Link className={styles.link} href="/email-agente?view=activities">Ver registro de atividades</Link> · <Link className={styles.link} href="/dashboard?preset=MONTH">Abrir Indicadores</Link></div></div>
    <div className={styles.grid}>
      <article className={styles.card}><h2>Abordados hoje</h2><div className={styles.metric}>{screen.metrics.politiciansTouchedToday}</div><p>Políticos distintos com ligação, mensagem ou novo seguimento registrado</p></article>
      <article className={styles.card}><h2>Contatos efetivos hoje</h2><div className={styles.metric}>{screen.metrics.effectiveContactsToday}</div><p>Leads distintos com ligação atendida ou resposta humana</p></article>
      <article className={styles.card}><h2>Liberações · 30 dias</h2><div className={styles.metric}>{screen.metrics.releasesThirtyDays}</div><p>Fonte: releases confirmados</p></article>
      <article className={styles.card}><h2>Conversas por liberação · 30 dias</h2><div className={styles.metric}>{screen.metrics.responseRateThirtyDays === null ? "—" : `${screen.metrics.responseRateThirtyDays}%`}</div><p>{screen.metrics.conversationsThirtyDays} conversas iniciadas / {screen.metrics.releasesThirtyDays} liberações; eventos do período, sem coorte de lead</p></article>
      <article className={styles.card}><h2>Reuniões na agenda · 30 dias</h2><div className={styles.metric}>{screen.metrics.meetingsCreatedThirtyDays}</div><p>Agendamentos criados pelos vendedores</p></article>
      <article className={styles.card}><h2>Leads na etapa reunião · 30 dias</h2><div className={styles.metric}>{screen.metrics.meetingsThirtyDays}</div><p>Políticos distintos movidos para Reunião marcada, com ou sem reunião na Agenda</p></article>
    </div>
    <section className={styles.section}>
      <div className={styles.sectionHeader}><div><h2>Produção de hoje por vendedor</h2><p>Atividades registradas no dia local. Cada político conta uma vez por vendedor; e-mails automáticos são atribuídos ao responsável da cadência.</p></div></div>
      <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Vendedor</th><th>Políticos</th><th>Contatos efetivos</th><th>Ligações</th><th>Resultados das ligações</th><th>Instagram</th><th>E-mails enviados</th><th>Reuniões marcadas</th></tr></thead><tbody>{screen.metrics.dailyBySeller.map((row) => <tr key={row.memberId}><td><strong>{row.memberName}</strong></td><td>{row.politiciansWorked}</td><td>{row.effectiveContacts}</td><td>{row.callsCompleted} feitas</td><td>{row.callsConnected} ligações atendidas · {row.callsCallbackRequested} pediram retorno · {row.callsWhatsappShared} passaram WhatsApp · {row.callsUnanswered} sem atendimento ({row.callsNoAnswer} não atenderam, {row.callsBusy} ocupadas, {row.callsVoicemail} caixa postal, {row.callsUnansweredOther} outras) · {row.callsFailed} falhas ({row.callsWrongNumber} número incorreto, {row.callsChannelUnavailable} sem canal, {row.callsFailedOther} outras) · {row.callsWithoutOutcome} sem desfecho</td><td>{row.instagramMessagesSent} mensagens · {row.instagramFollowsCompleted} seguidos · {row.instagramFollowsAlreadyFollowing} já seguidos · {row.instagramMessagesProfileNotFound + row.instagramFollowsProfileNotFound} não encontrados · {row.instagramMessagesFailed + row.instagramFollowsFailed} falhas</td><td>{row.emailsSent}</td><td>{row.meetingsScheduled}</td></tr>)}</tbody></table>{screen.metrics.dailyBySeller.length === 0 ? <p className={styles.empty}>Nenhum vendedor de prospecção está disponível neste recorte.</p> : null}</div>
    </section>
    <section className={styles.section} aria-labelledby="prospecting-email-cadence-title">
      <div className={styles.sectionHeader}><div><h2 id="prospecting-email-cadence-title">E-mails por etapa · 30 dias</h2><p>Eventos persistidos da cadência, separados do Email 1 ao Email 6.</p></div></div>
      <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Etapa</th><th>Programados</th><th>Enviados</th><th>Entregues</th><th>Respostas</th><th>Devolvidos</th><th>Falhas</th><th>Expirados</th><th>Cancelados</th><th>Spam</th><th>Descadastros</th></tr></thead><tbody>{screen.metrics.emailCadence.map((row) => <tr key={row.stepKey}><td><strong>Email {row.stepNumber}</strong><br />D{row.dayOffset}</td><td>{row.scheduled}</td><td><strong>{row.sent}</strong></td><td>{row.delivered}</td><td>{row.replied}</td><td>{row.bounced}</td><td>{row.failed}</td><td>{row.expired}</td><td>{row.cancelled}</td><td>{row.complaints}</td><td>{row.unsubscribed}</td></tr>)}</tbody></table></div>
    </section>
    <p className={styles.empty}>Período: {date(screen.metrics.period.start, screen.timeZone)} até {date(screen.metrics.period.end, screen.timeZone)} · fuso {screen.metrics.period.timeZone}. Última evidência observada: {date(screen.metrics.lastSourceObservedAt, screen.timeZone)}.</p>
    <section className={styles.section}>
      <div className={styles.grid}>
        <article className={styles.card}><h3>Resultados por atividade · 30 dias</h3>{screen.metrics.manualResultCounts.map((row) => <p key={`${row.channel}:${row.result}`}>{channelLabels[row.channel] ?? row.channel} · {resultLabels[row.result] ?? row.result}: <strong>{row.count}</strong></p>)}</article>
        <article className={styles.card}><h3>Conclusão manual por canal</h3>{screen.metrics.manualCompletionCounts.map((row) => <p key={row.channel}>{channelLabels[row.channel] ?? row.channel}: <strong>{row.count}</strong></p>)}</article>
        <article className={styles.card}><h3>Estoque por status</h3>{screen.metrics.candidateCounts.map((row) => <p key={row.status}>{statusLabels[row.status] ?? row.status}: <strong>{row.count}</strong></p>)}</article>
        <article className={styles.card}><h3>Cadências</h3>{screen.metrics.cadenceCounts.map((row) => <p key={row.status}>{statusLabels[row.status] ?? row.status}: <strong>{row.count}</strong></p>)}</article>
        <article className={styles.card}><h3>Motivos de parada</h3>{screen.metrics.discardReasons.map((row) => <p key={row.reason}>{row.reason}: <strong>{row.count}</strong></p>)}</article>
        <article className={styles.card}><h3>E-mails</h3>{screen.metrics.emailCounts.map((row) => <p key={row.status}>{row.status}: <strong>{row.count}</strong></p>)}</article>
      </div>
    </section>
    <section className={styles.section}><div className={styles.sectionHeader}><div><h2>Capacidade por data</h2><p>Projeção reconciliada de Tasks e ProspectRelease.</p></div></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Data</th><th>Vendedor</th><th>Realizado</th><th>Agendado</th><th>Planejado</th><th>Total / limite</th></tr></thead><tbody>{screen.capacity.map((row) => <tr key={`${row.memberId}:${row.localDate}`}><td>{row.localDate}</td><td>{row.memberName}</td><td>{row.realized}</td><td>{row.scheduled}</td><td>{row.planned}</td><td>{row.projected}/{row.limit}{row.overCapacity ? " · excesso" : ""}</td></tr>)}</tbody></table></div></section>
  </>;
}

export function ProspectingSettings({ screen }: Readonly<{ screen: Screen }>) {
  const setting = screen.settings;
  const templateByStep = new Map<string, (typeof screen.email.templates)[number]>();
  for (const template of screen.email.templates) {
    if (template.published && !templateByStep.has(template.stepKey)) templateByStep.set(template.stepKey, template);
  }
  const publishedTemplates = [...templateByStep.values()].sort((left, right) => left.stepKey.localeCompare(right.stepKey));
  return <>
    <div className={styles.grid}>
      <article className={styles.card}><h2>Liberação diária</h2><div className={styles.gate}><i className={styles.dot} data-ok={Boolean(setting?.releaseEnabled)} /><span>{setting?.releaseEnabled ? "Ativa" : "Pausada por padrão seguro"}</span></div><p>Meta padrão: {setting?.dailyCapacity ?? 75} políticos distintos por dia útil; a reserva legada não reduz essa meta.</p></article>
      <article className={styles.card}><h2>Egress de e-mail</h2><div className={styles.gate}><i className={styles.dot} data-ok={Boolean(setting?.emailEgressEnabled)} /><span>{setting?.emailEgressEnabled ? "Ativo" : "Bloqueado"}</span></div><p>Privacidade: {setting?.privacyApprovedAt ? "aprovada" : "pendente"}; canário: {setting?.canaryApprovedAt ? "aprovado" : "pendente"}.</p></article>
      <article className={styles.card}><h2>Janela</h2><div className={styles.metric} style={{fontSize:"1.25rem"}}>{setting?.emailWindowStart ?? "09:00"}–{setting?.emailWindowEnd ?? "17:00"}</div><p>Fuso {screen.timeZone}</p></article>
    </div>
    <section className={styles.section}>
      <div className={styles.sectionHeader}><div><h2>Vendedores persistidos</h2><p>Identidade resolvida por WorkspaceMember.id.</p></div></div>
      <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Ordem</th><th>Vendedor</th><th>Meta</th><th>Reserva legada</th><th>Remetente</th><th>Limite e-mail</th><th>Disponibilidade</th></tr></thead><tbody>{screen.sellers.map((seller) => <tr key={seller.id}><td>{seller.rotationPosition + 1}</td><td>{seller.name}<br /><small>{seller.memberId}</small></td><td>{seller.dailyCapacity}/dia útil</td><td>{seller.reservePercent}% · não desconta</td><td>{seller.senderProfileId ? "Mapeado" : "Pendente"}</td><td>{seller.dailyEmailLimit ?? "Pendente"}</td><td><span className={styles.status}>{seller.available ? "Disponível" : "Pausado/indisponível"}</span></td></tr>)}</tbody></table>{screen.sellers.length === 0 ? <p className={styles.empty}>Carlos, Jhon e Ede ainda não foram reconciliados no workspace.</p> : null}</div>
    </section>
    <section className={styles.section}>
      <div className={styles.grid}>
        <article className={styles.card}><h3>Templates</h3><div className={styles.metric}>{publishedTemplates.length}/6</div><p>Versões publicadas e imutáveis; envio depende dos gates.</p></article>
        <article className={styles.card}><h3>Remetentes</h3><div className={styles.metric}>{screen.email.senders.length}</div><p><Link className={styles.link} href="/integracoes/email">Configurar contas e reputação</Link></p></article>
      </div>
      <div className={styles.sectionHeader}><div><h2>Sequência de e-mails salva</h2><p>Conteúdo armazenado no CRM. O egress bloqueado impede qualquer envio.</p></div></div>
      <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Dia</th><th>Modelo</th><th>Assunto</th><th>Conteúdo</th></tr></thead><tbody>{publishedTemplates.map((template) => <tr key={template.id}><td>{emailDayLabels[template.stepKey] ?? "—"}</td><td>{template.stepKey} · v{template.version}</td><td>{template.subjectTemplate}</td><td><details><summary>Visualizar</summary><pre style={{marginTop:"0.75rem",maxWidth:"42rem",whiteSpace:"pre-wrap"}}>{template.bodyTemplate}</pre></details></td></tr>)}</tbody></table>{publishedTemplates.length === 0 ? <p className={styles.empty}>Nenhum template cadastrado.</p> : null}</div>
    </section>
    {screen.permissions.manage ? <ProspectingSettingsActions screen={{ settings: setting, sellers: screen.sellers, sellerOptions: screen.sellerOptions, senders: screen.email.senders }} /> : null}
  </>;
}
